// Plan 30 T1.1: the reaction quick set + the full emoji catalog.
//
// Plain static data, zero native dependency, so it works identically in Expo Go,
// a dev build, Hermes, and Node tests. The protocol accepts any single grapheme
// (see @mylife/sync isSingleEmojiGrapheme), so tuning QUICK_REACTIONS is a pure
// copy change with no schema impact. The catalog is a curated list of common
// emoji grouped by category, each with search keywords for the picker.

/** One catalog entry: the grapheme plus a searchable name and keywords. */
export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string[];
}

/** A named group of emoji rendered as one section in the picker. */
export interface EmojiCategory {
  id: string;
  label: string;
  emoji: EmojiEntry[];
}

/**
 * The six quick reactions (founder decision 2026-07-01), in exact order:
 * heart, thumbs up, laugh, wow, sad, party. Locked by the kit-core unit test.
 */
export const QUICK_REACTIONS: readonly string[] = ['❤️', '👍', '😂', '😮', '😢', '🎉'];

function e(char: string, name: string, ...keywords: string[]): EmojiEntry {
  return { char, name, keywords };
}

export const EMOJI_CATALOG: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emoji: [
      e('😀', 'grinning face', 'smile', 'happy', 'grin'),
      e('😃', 'smiley', 'happy', 'joy', 'smile'),
      e('😄', 'smile', 'happy', 'laugh'),
      e('😁', 'beaming face', 'grin', 'happy'),
      e('😆', 'laughing', 'haha', 'laugh', 'lol'),
      e('😅', 'sweat smile', 'phew', 'relief', 'laugh'),
      e('😂', 'joy', 'laugh', 'tears', 'lol', 'haha'),
      e('🤣', 'rofl', 'laugh', 'lol', 'rolling'),
      e('🙂', 'slight smile', 'happy'),
      e('🙃', 'upside down', 'silly', 'sarcasm'),
      e('😉', 'wink', 'flirt'),
      e('😊', 'blush', 'happy', 'smile'),
      e('😇', 'innocent', 'angel', 'halo'),
      e('🥰', 'smiling hearts', 'love', 'adore'),
      e('😍', 'heart eyes', 'love', 'crush'),
      e('🤩', 'star struck', 'wow', 'excited'),
      e('😘', 'blow kiss', 'love', 'kiss'),
      e('😗', 'kissing', 'kiss'),
      e('😚', 'kissing closed eyes', 'kiss'),
      e('😙', 'kissing smile', 'kiss'),
      e('😋', 'yum', 'tasty', 'delicious'),
      e('😛', 'tongue', 'silly', 'playful'),
      e('😜', 'winking tongue', 'silly', 'joke'),
      e('🤪', 'zany', 'goofy', 'crazy'),
      e('😝', 'squint tongue', 'silly'),
      e('🤑', 'money mouth', 'rich', 'dollar'),
      e('🤗', 'hug', 'hugging', 'embrace'),
      e('🤭', 'hand over mouth', 'oops', 'giggle'),
      e('🤫', 'shush', 'quiet', 'secret'),
      e('🤔', 'thinking', 'hmm', 'consider'),
      e('🤐', 'zipper mouth', 'quiet', 'secret'),
      e('🤨', 'raised eyebrow', 'skeptical', 'suspicious'),
      e('😐', 'neutral', 'meh', 'blank'),
      e('😑', 'expressionless', 'blank'),
      e('😶', 'no mouth', 'silent', 'blank'),
      e('😏', 'smirk', 'sly'),
      e('😒', 'unamused', 'meh', 'annoyed'),
      e('🙄', 'eye roll', 'annoyed', 'whatever'),
      e('😬', 'grimace', 'awkward'),
      e('😮‍💨', 'exhale', 'relief', 'sigh'),
      e('🤥', 'lying', 'pinocchio', 'liar'),
      e('😌', 'relieved', 'calm', 'content'),
      e('😔', 'pensive', 'sad', 'down'),
      e('😪', 'sleepy', 'tired'),
      e('🤤', 'drooling', 'hungry'),
      e('😴', 'sleeping', 'zzz', 'tired'),
      e('😷', 'mask', 'sick', 'ill'),
      e('🤒', 'thermometer', 'sick', 'fever'),
      e('🤕', 'bandage', 'hurt', 'injured'),
      e('🤢', 'nauseated', 'sick', 'gross'),
      e('🤮', 'vomiting', 'sick', 'puke'),
      e('🤧', 'sneezing', 'sick', 'tissue'),
      e('🥵', 'hot face', 'heat', 'sweat'),
      e('🥶', 'cold face', 'freezing', 'frozen'),
      e('🥴', 'woozy', 'dizzy', 'drunk'),
      e('😵', 'dizzy', 'faint', 'knocked out'),
      e('🤯', 'mind blown', 'shocked', 'wow', 'explode'),
      e('🤠', 'cowboy', 'hat', 'yeehaw'),
      e('🥳', 'partying', 'celebrate', 'party', 'birthday'),
      e('😎', 'sunglasses', 'cool', 'chill'),
      e('🤓', 'nerd', 'geek', 'glasses'),
      e('🧐', 'monocle', 'inspect', 'curious'),
      e('😕', 'confused', 'unsure'),
      e('😟', 'worried', 'concerned'),
      e('🙁', 'slight frown', 'sad'),
      e('😮', 'wow', 'surprised', 'shocked', 'open mouth'),
      e('😯', 'hushed', 'surprised'),
      e('😲', 'astonished', 'shocked', 'gasp'),
      e('😳', 'flushed', 'embarrassed', 'blush'),
      e('🥺', 'pleading', 'puppy eyes', 'please', 'begging'),
      e('😦', 'frowning open', 'sad'),
      e('😧', 'anguished', 'shocked'),
      e('😨', 'fearful', 'scared'),
      e('😰', 'anxious sweat', 'nervous', 'worried'),
      e('😥', 'sad relief', 'disappointed'),
      e('😢', 'cry', 'sad', 'tear'),
      e('😭', 'sobbing', 'cry', 'bawling', 'sad'),
      e('😱', 'scream', 'shocked', 'fear'),
      e('😖', 'confounded', 'frustrated'),
      e('😣', 'persevering', 'struggle'),
      e('😞', 'disappointed', 'sad'),
      e('😓', 'downcast sweat', 'sad'),
      e('😩', 'weary', 'tired', 'ugh'),
      e('😫', 'tired face', 'exhausted'),
      e('🥱', 'yawn', 'bored', 'tired'),
      e('😤', 'triumph', 'huff', 'proud'),
      e('😡', 'rage', 'angry', 'mad'),
      e('😠', 'angry', 'mad'),
      e('🤬', 'cursing', 'swear', 'angry'),
      e('😈', 'devil', 'mischief', 'evil'),
      e('👿', 'imp', 'angry devil'),
      e('💀', 'skull', 'dead', 'dying'),
      e('💩', 'poop', 'crap'),
      e('🤡', 'clown', 'joker'),
      e('👻', 'ghost', 'boo', 'spooky'),
      e('👽', 'alien', 'ufo'),
      e('🤖', 'robot', 'bot'),
      e('🎃', 'jack o lantern', 'halloween', 'pumpkin'),
    ],
  },
  {
    id: 'gestures',
    label: 'People & Gestures',
    emoji: [
      e('👍', 'thumbs up', 'yes', 'like', 'approve', 'ok'),
      e('👎', 'thumbs down', 'no', 'dislike'),
      e('👌', 'ok hand', 'perfect', 'okay'),
      e('🤌', 'pinched fingers', 'italian', 'chef kiss'),
      e('🤏', 'pinch', 'small', 'tiny'),
      e('✌️', 'victory', 'peace'),
      e('🤞', 'fingers crossed', 'luck', 'hope'),
      e('🤟', 'love you', 'rock'),
      e('🤘', 'horns', 'rock', 'metal'),
      e('🤙', 'call me', 'hang loose', 'shaka'),
      e('👈', 'point left', 'left'),
      e('👉', 'point right', 'right'),
      e('👆', 'point up', 'up'),
      e('👇', 'point down', 'down'),
      e('☝️', 'index up', 'one'),
      e('✋', 'raised hand', 'stop', 'high five'),
      e('🤚', 'back of hand', 'stop'),
      e('🖐️', 'hand fingers', 'five'),
      e('🖖', 'vulcan', 'spock', 'star trek'),
      e('👋', 'wave', 'hello', 'hi', 'bye'),
      e('🤝', 'handshake', 'deal', 'agree'),
      e('👏', 'clap', 'applause', 'bravo'),
      e('🙌', 'raised hands', 'praise', 'celebrate'),
      e('👐', 'open hands', 'hug'),
      e('🤲', 'palms up', 'pray', 'offer'),
      e('🙏', 'pray', 'thanks', 'please', 'namaste'),
      e('✊', 'raised fist', 'power', 'solidarity'),
      e('👊', 'fist bump', 'punch'),
      e('🤛', 'left fist', 'bump'),
      e('🤜', 'right fist', 'bump'),
      e('💪', 'flex', 'muscle', 'strong'),
      e('🦾', 'mechanical arm', 'strong', 'robot'),
      e('✍️', 'writing', 'write', 'pen'),
      e('🤳', 'selfie', 'photo'),
      e('💅', 'nails', 'manicure', 'sassy'),
      e('👀', 'eyes', 'looking', 'watch'),
      e('👁️', 'eye', 'look'),
      e('🧠', 'brain', 'smart', 'mind'),
      e('👶', 'baby', 'infant'),
      e('🧒', 'child', 'kid'),
      e('👦', 'boy', 'kid'),
      e('👧', 'girl', 'kid'),
      e('🧑', 'person', 'adult'),
      e('👨', 'man', 'guy'),
      e('👩', 'woman', 'lady'),
      e('🧓', 'older person', 'elder'),
      e('👴', 'old man', 'grandpa'),
      e('👵', 'old woman', 'grandma'),
      e('🧑‍🍳', 'cook', 'chef'),
      e('🧑‍💻', 'technologist', 'developer', 'coder'),
      e('🕺', 'dancing man', 'dance'),
      e('💃', 'dancing woman', 'dance'),
      e('🚶', 'walking', 'walk'),
      e('🏃', 'running', 'run'),
    ],
  },
  {
    id: 'nature',
    label: 'Animals & Nature',
    emoji: [
      e('🐶', 'dog', 'puppy', 'pet'),
      e('🐱', 'cat', 'kitten', 'pet'),
      e('🐭', 'mouse', 'rodent'),
      e('🐹', 'hamster', 'pet'),
      e('🐰', 'rabbit', 'bunny'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐨', 'koala'),
      e('🐯', 'tiger'),
      e('🦁', 'lion'),
      e('🐮', 'cow'),
      e('🐷', 'pig'),
      e('🐸', 'frog'),
      e('🐵', 'monkey'),
      e('🐔', 'chicken', 'hen'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🐤', 'chick', 'baby bird'),
      e('🦆', 'duck'),
      e('🦅', 'eagle'),
      e('🦉', 'owl'),
      e('🦇', 'bat'),
      e('🐺', 'wolf'),
      e('🐗', 'boar'),
      e('🐴', 'horse'),
      e('🦄', 'unicorn'),
      e('🐝', 'bee', 'honey'),
      e('🐛', 'bug', 'caterpillar'),
      e('🦋', 'butterfly'),
      e('🐌', 'snail'),
      e('🐞', 'ladybug'),
      e('🐢', 'turtle'),
      e('🐍', 'snake'),
      e('🐙', 'octopus'),
      e('🦑', 'squid'),
      e('🦀', 'crab'),
      e('🐠', 'fish', 'tropical'),
      e('🐟', 'fish'),
      e('🐬', 'dolphin'),
      e('🐳', 'whale'),
      e('🦈', 'shark'),
      e('🐊', 'crocodile'),
      e('🐅', 'tiger'),
      e('🦓', 'zebra'),
      e('🦍', 'gorilla'),
      e('🐘', 'elephant'),
      e('🦒', 'giraffe'),
      e('🐪', 'camel'),
      e('🌵', 'cactus', 'plant'),
      e('🌲', 'evergreen', 'tree'),
      e('🌳', 'tree'),
      e('🌴', 'palm tree'),
      e('🌱', 'seedling', 'plant', 'sprout'),
      e('🌿', 'herb', 'leaf'),
      e('☘️', 'shamrock', 'clover'),
      e('🍀', 'four leaf clover', 'luck'),
      e('🌸', 'blossom', 'flower', 'sakura'),
      e('🌹', 'rose', 'flower'),
      e('🌻', 'sunflower', 'flower'),
      e('🌼', 'daisy', 'flower'),
      e('🌷', 'tulip', 'flower'),
      e('🍄', 'mushroom'),
      e('🌍', 'earth', 'globe', 'world'),
      e('🌙', 'moon', 'night'),
      e('⭐', 'star'),
      e('🌟', 'glowing star', 'sparkle'),
      e('✨', 'sparkles', 'shiny', 'magic'),
      e('⚡', 'lightning', 'bolt', 'zap'),
      e('🔥', 'fire', 'lit', 'hot', 'flame'),
      e('🌈', 'rainbow'),
      e('☀️', 'sun', 'sunny'),
      e('⛅', 'partly cloudy', 'sun cloud'),
      e('☁️', 'cloud'),
      e('🌧️', 'rain', 'rainy'),
      e('⛄', 'snowman', 'snow'),
      e('❄️', 'snowflake', 'cold', 'snow'),
      e('💧', 'droplet', 'water'),
      e('🌊', 'wave', 'ocean', 'water'),
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    emoji: [
      e('🍎', 'apple', 'fruit'),
      e('🍏', 'green apple', 'fruit'),
      e('🍊', 'orange', 'fruit'),
      e('🍋', 'lemon', 'fruit'),
      e('🍌', 'banana', 'fruit'),
      e('🍉', 'watermelon', 'fruit'),
      e('🍇', 'grapes', 'fruit'),
      e('🍓', 'strawberry', 'fruit'),
      e('🫐', 'blueberries', 'fruit'),
      e('🍒', 'cherries', 'fruit'),
      e('🍑', 'peach', 'fruit'),
      e('🥭', 'mango', 'fruit'),
      e('🍍', 'pineapple', 'fruit'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi', 'fruit'),
      e('🍅', 'tomato'),
      e('🥑', 'avocado'),
      e('🍆', 'eggplant'),
      e('🥕', 'carrot'),
      e('🌽', 'corn'),
      e('🌶️', 'pepper', 'spicy', 'chili'),
      e('🥦', 'broccoli'),
      e('🧄', 'garlic'),
      e('🧅', 'onion'),
      e('🥔', 'potato'),
      e('🍞', 'bread'),
      e('🥐', 'croissant'),
      e('🥖', 'baguette', 'bread'),
      e('🧀', 'cheese'),
      e('🥚', 'egg'),
      e('🍳', 'fried egg', 'cooking'),
      e('🥞', 'pancakes', 'breakfast'),
      e('🧇', 'waffle'),
      e('🥓', 'bacon'),
      e('🍔', 'burger', 'hamburger'),
      e('🍟', 'fries', 'chips'),
      e('🍕', 'pizza'),
      e('🌭', 'hot dog'),
      e('🥪', 'sandwich'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🥙', 'pita', 'wrap'),
      e('🍜', 'ramen', 'noodles'),
      e('🍝', 'pasta', 'spaghetti'),
      e('🍲', 'stew', 'soup'),
      e('🍣', 'sushi'),
      e('🍤', 'shrimp', 'tempura'),
      e('🍚', 'rice'),
      e('🍛', 'curry'),
      e('🍦', 'ice cream', 'soft serve'),
      e('🍰', 'cake', 'slice'),
      e('🎂', 'birthday cake', 'party'),
      e('🧁', 'cupcake'),
      e('🍪', 'cookie'),
      e('🍩', 'donut', 'doughnut'),
      e('🍫', 'chocolate'),
      e('🍬', 'candy', 'sweet'),
      e('🍭', 'lollipop', 'candy'),
      e('🍿', 'popcorn'),
      e('☕', 'coffee', 'tea', 'hot drink'),
      e('🍵', 'tea', 'matcha'),
      e('🥤', 'soda', 'drink', 'cup'),
      e('🧋', 'bubble tea', 'boba'),
      e('🍺', 'beer'),
      e('🍻', 'cheers', 'beers', 'toast'),
      e('🥂', 'champagne', 'cheers', 'toast'),
      e('🍷', 'wine'),
      e('🍸', 'cocktail', 'martini'),
      e('🥃', 'whiskey', 'liquor'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities & Travel',
    emoji: [
      e('⚽', 'soccer', 'football'),
      e('🏀', 'basketball'),
      e('🏈', 'football', 'american'),
      e('⚾', 'baseball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby'),
      e('🎱', 'billiards', 'pool', 'eight ball'),
      e('🏓', 'ping pong', 'table tennis'),
      e('🏸', 'badminton'),
      e('🥅', 'goal', 'net'),
      e('🏒', 'hockey'),
      e('🏑', 'field hockey'),
      e('🥍', 'lacrosse'),
      e('🏏', 'cricket'),
      e('⛳', 'golf', 'flag'),
      e('🏹', 'archery', 'bow'),
      e('🎣', 'fishing'),
      e('🥊', 'boxing', 'glove'),
      e('🥋', 'martial arts', 'karate'),
      e('⛸️', 'ice skate', 'skating'),
      e('🎿', 'ski'),
      e('🛷', 'sled'),
      e('🏂', 'snowboard'),
      e('🏋️', 'weightlifting', 'gym', 'lift'),
      e('🤸', 'cartwheel', 'gymnastics'),
      e('🤾', 'handball'),
      e('🏌️', 'golfing'),
      e('🏄', 'surfing', 'surf'),
      e('🏊', 'swimming', 'swim'),
      e('🚴', 'cycling', 'bike'),
      e('🧗', 'climbing'),
      e('🏆', 'trophy', 'win', 'champion'),
      e('🥇', 'gold medal', 'first', 'win'),
      e('🥈', 'silver medal', 'second'),
      e('🥉', 'bronze medal', 'third'),
      e('🎖️', 'medal', 'honor'),
      e('🎯', 'target', 'bullseye', 'dart'),
      e('🎮', 'video game', 'gaming', 'controller'),
      e('🎲', 'dice', 'game'),
      e('🎸', 'guitar', 'music'),
      e('🎹', 'piano', 'keyboard', 'music'),
      e('🎺', 'trumpet', 'music'),
      e('🎻', 'violin', 'music'),
      e('🥁', 'drum', 'music'),
      e('🎤', 'microphone', 'sing', 'karaoke'),
      e('🎧', 'headphones', 'music', 'listen'),
      e('🎨', 'art', 'palette', 'paint'),
      e('🎬', 'movie', 'film', 'clapper'),
      e('🚗', 'car', 'auto'),
      e('🚕', 'taxi', 'cab'),
      e('🚌', 'bus'),
      e('🏎️', 'race car', 'fast'),
      e('🚓', 'police car'),
      e('🚑', 'ambulance'),
      e('🚒', 'fire truck'),
      e('🚲', 'bicycle', 'bike'),
      e('🛵', 'scooter', 'moped'),
      e('🏍️', 'motorcycle'),
      e('✈️', 'airplane', 'flight', 'travel'),
      e('🚀', 'rocket', 'launch', 'space'),
      e('🚁', 'helicopter'),
      e('⛵', 'sailboat', 'boat'),
      e('🚢', 'ship', 'cruise'),
      e('🚂', 'train', 'locomotive'),
      e('🗺️', 'map', 'travel'),
      e('🏝️', 'island', 'beach', 'vacation'),
      e('🏔️', 'mountain', 'snow'),
      e('🏕️', 'camping', 'tent'),
      e('🌋', 'volcano'),
      e('🗽', 'statue of liberty', 'new york'),
      e('🗼', 'tower', 'tokyo'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emoji: [
      e('⌚', 'watch', 'time'),
      e('📱', 'phone', 'mobile', 'smartphone'),
      e('💻', 'laptop', 'computer'),
      e('⌨️', 'keyboard'),
      e('🖥️', 'desktop', 'monitor', 'computer'),
      e('🖨️', 'printer'),
      e('🖱️', 'mouse', 'computer'),
      e('💾', 'floppy disk', 'save'),
      e('💿', 'cd', 'disc'),
      e('📷', 'camera', 'photo'),
      e('📸', 'camera flash', 'photo'),
      e('🎥', 'movie camera', 'film'),
      e('📺', 'tv', 'television'),
      e('📻', 'radio'),
      e('☎️', 'telephone', 'phone'),
      e('🔋', 'battery', 'power'),
      e('🔌', 'plug', 'power'),
      e('💡', 'idea', 'bulb', 'light'),
      e('🔦', 'flashlight', 'torch'),
      e('🕯️', 'candle'),
      e('💰', 'money bag', 'cash', 'rich'),
      e('💵', 'dollar', 'money', 'cash'),
      e('💳', 'credit card', 'payment'),
      e('💎', 'gem', 'diamond', 'jewel'),
      e('⚖️', 'scales', 'justice', 'balance'),
      e('🔧', 'wrench', 'tool', 'fix'),
      e('🔨', 'hammer', 'tool', 'build'),
      e('🛠️', 'tools', 'repair'),
      e('⚙️', 'gear', 'settings', 'cog'),
      e('🧰', 'toolbox'),
      e('🧲', 'magnet'),
      e('🔑', 'key', 'lock'),
      e('🔒', 'lock', 'secure', 'locked'),
      e('🔓', 'unlock', 'open'),
      e('🛡️', 'shield', 'protect', 'security'),
      e('🔗', 'link', 'chain'),
      e('📎', 'paperclip', 'attach'),
      e('📌', 'pushpin', 'pin'),
      e('📍', 'location pin', 'map'),
      e('✂️', 'scissors', 'cut'),
      e('📝', 'memo', 'note', 'write'),
      e('📅', 'calendar', 'date'),
      e('📆', 'tear calendar', 'date'),
      e('📋', 'clipboard', 'list'),
      e('📖', 'book', 'read'),
      e('📚', 'books', 'library', 'study'),
      e('✏️', 'pencil', 'write'),
      e('🖊️', 'pen', 'write'),
      e('📁', 'folder', 'files'),
      e('📂', 'open folder', 'files'),
      e('🗂️', 'dividers', 'organize'),
      e('📧', 'email', 'mail'),
      e('📬', 'mailbox', 'inbox'),
      e('📦', 'package', 'box', 'parcel'),
      e('🎁', 'gift', 'present'),
      e('🎈', 'balloon', 'party'),
      e('🎉', 'party popper', 'celebrate', 'tada', 'congrats'),
      e('🎊', 'confetti', 'celebrate', 'party'),
      e('🔔', 'bell', 'notification'),
      e('📣', 'megaphone', 'announce', 'loud'),
      e('🔍', 'search', 'magnify', 'find'),
      e('🧭', 'compass', 'direction'),
      e('⏰', 'alarm', 'clock', 'time'),
      e('⏳', 'hourglass', 'time', 'wait'),
      e('💊', 'pill', 'medicine'),
      e('🩹', 'bandage', 'plaster'),
      e('🔭', 'telescope', 'stars'),
      e('🔬', 'microscope', 'science'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emoji: [
      e('❤️', 'red heart', 'love', 'like'),
      e('🧡', 'orange heart', 'love'),
      e('💛', 'yellow heart', 'love'),
      e('💚', 'green heart', 'love'),
      e('💙', 'blue heart', 'love'),
      e('💜', 'purple heart', 'love'),
      e('🖤', 'black heart', 'love'),
      e('🤍', 'white heart', 'love'),
      e('🤎', 'brown heart', 'love'),
      e('💔', 'broken heart', 'heartbreak', 'sad'),
      e('❣️', 'heart exclamation', 'love'),
      e('💕', 'two hearts', 'love'),
      e('💞', 'revolving hearts', 'love'),
      e('💓', 'beating heart', 'love'),
      e('💗', 'growing heart', 'love'),
      e('💖', 'sparkling heart', 'love'),
      e('💘', 'heart arrow', 'cupid', 'love'),
      e('💝', 'heart gift', 'love'),
      e('💯', 'hundred', 'perfect', 'score', 'keep it'),
      e('💢', 'anger', 'mad'),
      e('💥', 'boom', 'collision', 'explosion'),
      e('💫', 'dizzy', 'stars'),
      e('💦', 'sweat drops', 'water'),
      e('💨', 'dash', 'wind', 'fast'),
      e('🕳️', 'hole'),
      e('💬', 'speech bubble', 'chat', 'talk'),
      e('💭', 'thought bubble', 'think'),
      e('🗯️', 'anger bubble', 'shout'),
      e('✅', 'check mark', 'done', 'yes', 'correct'),
      e('☑️', 'check box', 'done', 'tick'),
      e('✔️', 'check', 'done', 'yes'),
      e('❌', 'cross mark', 'no', 'wrong', 'x'),
      e('❎', 'cross box', 'no'),
      e('➕', 'plus', 'add'),
      e('➖', 'minus', 'subtract'),
      e('➗', 'divide'),
      e('❓', 'question', 'help'),
      e('❗', 'exclamation', 'important'),
      e('‼️', 'double exclamation', 'important'),
      e('⁉️', 'interrobang', 'surprise'),
      e('⚠️', 'warning', 'caution'),
      e('🚫', 'no entry', 'prohibited', 'ban'),
      e('🔞', 'no under 18', 'adult'),
      e('♻️', 'recycle', 'green'),
      e('✳️', 'asterisk'),
      e('❇️', 'sparkle'),
      e('⭕', 'circle', 'o'),
      e('🔴', 'red circle', 'record', 'dot'),
      e('🟠', 'orange circle'),
      e('🟡', 'yellow circle'),
      e('🟢', 'green circle', 'online'),
      e('🔵', 'blue circle'),
      e('🟣', 'purple circle'),
      e('⚫', 'black circle'),
      e('⚪', 'white circle'),
      e('🟥', 'red square'),
      e('🟩', 'green square'),
      e('🟦', 'blue square'),
      e('⬛', 'black square'),
      e('⬜', 'white square'),
      e('🔶', 'orange diamond'),
      e('🔷', 'blue diamond'),
      e('🔸', 'small orange diamond'),
      e('💠', 'diamond dot', 'cute'),
      e('🔺', 'red triangle up'),
      e('🔻', 'red triangle down'),
      e('♠️', 'spades', 'cards'),
      e('♥️', 'hearts', 'cards'),
      e('♦️', 'diamonds', 'cards'),
      e('♣️', 'clubs', 'cards'),
      e('🎵', 'music note', 'song'),
      e('🎶', 'music notes', 'song'),
      e('➡️', 'right arrow'),
      e('⬅️', 'left arrow'),
      e('⬆️', 'up arrow'),
      e('⬇️', 'down arrow'),
      e('🔄', 'refresh', 'sync', 'reload'),
      e('🔝', 'top', 'up'),
      e('🆗', 'ok button', 'okay'),
      e('🆕', 'new'),
      e('🆙', 'up button', 'level up'),
      e('💤', 'zzz', 'sleep'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    emoji: [
      e('🏁', 'checkered flag', 'race', 'finish'),
      e('🚩', 'triangular flag', 'red flag', 'marker'),
      e('🏳️', 'white flag', 'surrender'),
      e('🏴', 'black flag'),
      e('🏳️‍🌈', 'rainbow flag', 'pride', 'lgbtq'),
      e('🇺🇸', 'united states', 'usa', 'america', 'flag'),
      e('🇬🇧', 'united kingdom', 'uk', 'britain', 'flag'),
      e('🇨🇦', 'canada', 'flag'),
      e('🇲🇽', 'mexico', 'flag'),
      e('🇧🇷', 'brazil', 'flag'),
      e('🇫🇷', 'france', 'flag'),
      e('🇩🇪', 'germany', 'flag'),
      e('🇪🇸', 'spain', 'flag'),
      e('🇮🇹', 'italy', 'flag'),
      e('🇯🇵', 'japan', 'flag'),
      e('🇰🇷', 'south korea', 'korea', 'flag'),
      e('🇨🇳', 'china', 'flag'),
      e('🇮🇳', 'india', 'flag'),
      e('🇦🇺', 'australia', 'flag'),
      e('🇳🇬', 'nigeria', 'flag'),
      e('🇿🇦', 'south africa', 'flag'),
    ],
  },
];

/**
 * Category-filtered search for the picker (T1.5). An empty query returns the
 * whole catalog untouched; otherwise a case-insensitive match on the entry name
 * or any keyword keeps the entry, and categories with no surviving entry are
 * dropped. Pure and deterministic.
 */
export function searchEmojiCatalog(
  catalog: readonly EmojiCategory[],
  query: string,
): EmojiCategory[] {
  const q = query.trim().toLowerCase();
  // Fresh array (not the shared readonly alias) so a caller can never mutate the
  // module-level catalog through the returned value.
  if (q === '') return [...catalog];
  const out: EmojiCategory[] = [];
  for (const category of catalog) {
    const matches = category.emoji.filter((entry) =>
      entry.name.toLowerCase().includes(q)
      || entry.keywords.some((keyword) => keyword.toLowerCase().includes(q)),
    );
    if (matches.length > 0) out.push({ ...category, emoji: matches });
  }
  return out;
}
