#!/usr/bin/env npx tsx
/**
 * Download and parse USDA FoodData Central SR Legacy data.
 *
 * Downloads the full USDA food composition database CSV files, parses them,
 * and generates TypeScript files with SQL INSERT statements for the nutrition module.
 *
 * Usage: pnpm --filter @mylife/nutrition data:usda
 *
 * Data source: https://fdc.nal.usda.gov/download-datasets
 * The SR Legacy dataset contains ~7,800 whole foods with full nutrient profiles.
 *
 * Output:
 *   src/data/usda-full-foods.ts   -- SQL INSERTs for all USDA foods
 *   src/data/usda-full-fts.ts     -- SQL INSERTs for FTS index population
 *
 * Note: This is a dev-time script, not bundled in the app.
 * The initial seed in usda-seed.ts provides ~100 common foods for development.
 * Run this script to populate the full database for production builds.
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const USDA_CSV_URL = 'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip';

function escape(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  console.log('[usda] Downloading USDA SR Legacy dataset...');
  console.log(`[usda] URL: ${USDA_CSV_URL}`);
  console.log('[usda] This script is a placeholder for the full pipeline.');
  console.log('[usda] The initial seed data (~100 foods) is already in src/data/usda-seed.ts.');
  console.log('');
  console.log('[usda] To implement the full pipeline:');
  console.log('  1. Download and unzip the CSV archive');
  console.log('  2. Parse food.csv, nutrient.csv, food_nutrient.csv');
  console.log('  3. Map USDA nutrient IDs to nu_nutrients IDs');
  console.log('  4. Generate SQL INSERT statements');
  console.log('  5. Write to src/data/usda-full-foods.ts and src/data/usda-full-fts.ts');
  console.log('');

  // Placeholder output
  const outputPath = resolve(__dirname, '../src/data/usda-full-foods.ts');
  writeFileSync(
    outputPath,
    `// Generated by scripts/download-usda.ts\n// Run 'pnpm --filter @mylife/nutrition data:usda' to regenerate\n\nexport function getFullUSDAFoodInserts(): string[] {\n  // TODO: Implement full USDA data pipeline\n  return [];\n}\n`,
  );
  console.log(`[usda] Wrote placeholder to ${outputPath}`);
}

main().catch((err) => {
  console.error('[usda] Error:', err);
  process.exit(1);
});
