import type { ThemeProfile } from '../schema';

export const MINIMAL_INK: ThemeProfile = {
  id: 'minimal-ink',
  name: 'Minimal Ink',
  description: 'Pure white with Space Grotesk. List-first layout for focus-mode reading.',
  author: 'MyLife',
  version: '1.0.0',
  colorMode: 'light',
  colors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceElevated: '#FAFAFA',
    text: '#000000',
    textSecondary: '#3B3B3B',
    textTertiary: 'rgba(0,0,0,0.40)',
    border: 'rgba(0,0,0,0.08)',
    danger: '#CF1020',
    success: '#0F9D58',
    warning: '#F2A900',
    accent: '#000000',
    primary: '#000000',
    primaryContainer: '#F0F0F0',
  },
  glass: {
    cardFill: 'rgba(255,255,255,1)',
    cardBorder: 'rgba(0,0,0,0.08)',
    strongFill: 'rgba(255,255,255,1)',
    strongBorder: 'rgba(0,0,0,0.14)',
    dockFill: 'rgba(255,255,255,0.98)',
    dockBorder: 'rgba(0,0,0,0.08)',
    blurIntensity: 0,
  },
  fonts: {
    display: 'Space Grotesk',
    body: 'Space Grotesk',
  },
  typeScale: {
    heroTitle: { size: 40, weight: '700', lineHeight: 48 },
    heading: { size: 24, weight: '600', lineHeight: 32 },
    subheading: { size: 18, weight: '500', lineHeight: 24 },
    body: { size: 16, weight: '400', lineHeight: 26 },
    caption: { size: 13, weight: '400', lineHeight: 18 },
    label: { size: 11, weight: '600', lineHeight: 14, letterSpacing: 1.4 },
  },
  surfaces: {
    treatment: 'flat',
    cornerRadius: { card: 0, button: 0, icon: 0, tabBar: 0 },
    shadows: {
      card: 'none',
      elevated: 'none',
      pressed: 'none',
    },
  },
  layout: {
    dashboardStyle: 'list',
    moduleGridColumns: 3,
    tabBarStyle: 'minimal-dots',
    headerStyle: 'minimal',
    spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
  },
};
