import type { LucideIcon } from 'lucide-react';
import {
  BookOpen,
  Wallet,
  Car,
  GraduationCap,
  Shirt,
  Moon,
  Palette,
  MoonStar,
  Timer,
  Zap,
  MessageSquare,
  Users,
  Sprout,
  CheckCircle2,
  HeartPulse,
  Home,
  NotebookPen,
  Mail,
  Pill,
  Smile,
  ShoppingBag,
  Store,
  FileText,
  Utensils,
  CreditCard,
  PawPrint,
  ChefHat,
  PartyPopper,
  Sparkles,
  Waves,
  Mountain,
  Mic,
  BookA,
  Dumbbell,
  Smartphone,
  UtensilsCrossed,
  Trophy,
  Plane,
  Compass,
  Newspaper,
} from 'lucide-react';
import type { ModuleId } from '@mylife/module-registry';

/**
 * Maps each ModuleId to a Lucide React icon component.
 * Used in Sidebar, ModuleCard, and other hub UI that displays module icons.
 */
export const MODULE_ICON_MAP: Record<ModuleId, LucideIcon> = {
  books: BookOpen,
  budget: Wallet,
  car: Car,
  classes: GraduationCap,
  closet: Shirt,
  cycle: Moon,
  create: Palette,
  dining: UtensilsCrossed,
  fast: Timer,
  flash: Zap,
  forums: MessageSquare,
  friends: Users,
  garden: Sprout,
  habits: CheckCircle2,
  health: HeartPulse,
  homes: Home,
  journal: NotebookPen,
  mail: Mail,
  manhattan: Compass,
  market: Store,
  meds: Pill,
  mood: Smile,
  mynews: Newspaper,
  notes: FileText,
  nutrition: Utensils,
  payments: CreditCard,
  pets: PawPrint,
  presence: Smartphone,
  recipes: ChefHat,
  rsvp: PartyPopper,
  shop: ShoppingBag,
  sleep: MoonStar,
  sports: Trophy,
  stars: Sparkles,
  subs: CreditCard,
  surf: Waves,
  trails: Mountain,
  travel: Plane,
  voice: Mic,
  words: BookA,
  workouts: Dumbbell,
};
