/**
 * Honest per-locale completeness (plan 45 M3).
 *
 * The language picker must not present a locale as fully translated when a
 * meaningful number of its catalog values are still shipped in English. The
 * source of truth is i18n-value-completeness.json, regenerated by
 * scripts/check-i18n-values.mjs on every gate run and checked in. `identical`
 * counts catalog values byte-identical to EN that are NOT on the reviewed
 * loanword/brand allowlist; `partial` is true when that count exceeds the
 * gate's threshold.
 *
 * This is imported at build time (Metro bundles the JSON), so the label reflects
 * exactly what the gate last verified.
 */
import type { LanguageCode } from './languages';
import manifest from './i18n-value-completeness.json';

interface LocaleCompleteness {
  identical: number;
  partial: boolean;
}

const LOCALES = manifest.locales as Record<string, LocaleCompleteness>;

/** True when the locale still ships enough English values to warn the user. */
export function isLocalePartiallyEnglish(code: LanguageCode): boolean {
  return LOCALES[code]?.partial ?? false;
}

/** Count of non-allowlisted English (untranslated) values remaining for a locale. */
export function untranslatedValueCount(code: LanguageCode): number {
  return LOCALES[code]?.identical ?? 0;
}

export const VALUE_PARTIAL_THRESHOLD = manifest.partialThreshold as number;
