import type { ModuleDefinition } from '@mylife/module-registry';
import {
  ALL_TABLES,
  CREATE_INDEXES,
  V2_TABLES,
  V2_INDEXES,
  V3_TABLES,
  V3_INDEXES,
  V4_TABLES,
  V4_INDEXES,
} from './db/schema';
import { ST_ACCENT } from './ui/tokens';

export const STARS_MODULE: ModuleDefinition = {
  id: 'stars',
  name: 'MyStars',
  tagline: 'The cosmos in your pocket',
  icon: '⭐',
  accentColor: ST_ACCENT,
  tier: 'premium',
  storageType: 'sqlite',
  schemaVersion: 4,
  tablePrefix: 'st_',
  syncPolicy: {
    defaultScope: 'personal_replica',
    shareable: false,
    entityRules: [
      {
        tableName: 'birth_profiles',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'saved_charts',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'daily_readings',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'journal_entries',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
    ],
  },
  migrations: [
    {
      version: 1,
      description: 'Create stars tables: birth_profiles, transits, daily_readings, saved_charts',
      up: [...ALL_TABLES, ...CREATE_INDEXES],
      down: [
        'DROP TABLE IF EXISTS st_saved_charts',
        'DROP TABLE IF EXISTS st_daily_readings',
        'DROP TABLE IF EXISTS st_transits',
        'DROP TABLE IF EXISTS st_birth_profiles',
      ],
    },
    {
      version: 2,
      description: 'Add B+C feature tables: moon_calendar, compatibility_results, zodiac_events, transit_events, journal_entries, solar_returns, progressed_charts',
      up: [...V2_TABLES, ...V2_INDEXES],
      down: [
        'DROP TABLE IF EXISTS st_progressed_charts',
        'DROP TABLE IF EXISTS st_solar_returns',
        'DROP TABLE IF EXISTS st_journal_entries',
        'DROP TABLE IF EXISTS st_transit_events',
        'DROP TABLE IF EXISTS st_zodiac_events',
        'DROP TABLE IF EXISTS st_compatibility_results',
        'DROP TABLE IF EXISTS st_moon_calendar',
      ],
    },
    {
      version: 3,
      description: 'Add tarot spread storage and richer daily tarot metadata',
      up: [...V3_TABLES, ...V3_INDEXES],
      down: ['DROP TABLE IF EXISTS st_tarot_readings'],
    },
    {
      version: 4,
      description: 'Add journal compose metadata for title, intention, and attachments',
      up: [...V4_TABLES, ...V4_INDEXES],
      down: ['SELECT 1'],
    },
  ],
  navigation: {
    tabs: [
      { key: 'today', label: 'Today', icon: 'star' },
      { key: 'sky', label: 'Sky', icon: 'moon' },
      { key: 'journal', label: 'Journal', icon: 'book-open' },
      { key: 'more', label: 'More', icon: 'grid' },
    ],
    screens: [
      { name: 'birth-chart', title: 'Birth Chart' },
      { name: 'add-profile', title: 'Add Profile' },
      { name: 'profile', title: 'Profile' },
      { name: 'compatibility', title: 'Compatibility' },
      { name: 'compatibility-history', title: 'Past Comparisons' },
      { name: 'moon-calendar', title: 'Moon Calendar' },
      { name: 'zodiac-events', title: 'Zodiac Events' },
      { name: 'transit-timeline', title: 'Transit Timeline' },
      { name: 'transit-calendar', title: 'Transit Calendar' },
      { name: 'retrograde-dashboard', title: 'Retrogrades' },
      { name: 'journal-compose', title: 'New Entry' },
      { name: 'journal-entry', title: 'Journal Entry' },
      { name: 'solar-return', title: 'Solar Return' },
      { name: 'progressions', title: 'Progressions' },
      { name: 'daily-reading', title: 'Daily Reading' },
      { name: 'tarot-card', title: 'Card of the Day' },
      { name: 'tarot-reading', title: 'Reading' },
      { name: 'readings-history', title: 'Past Readings' },
    ],
  },
  requiresAuth: false,
  requiresNetwork: false,
  version: '0.2.0',
};
