import type {
  PaymentsActivityFeedSnapshot,
  PaymentsActivityRecord,
  PaymentsRequestRecord,
  PaymentsTransferRecord,
} from '@mylife/payments';

export const PAYMENTS_ACTIVITY_SERVER_NOW = '2026-04-24T16:00:00.000Z';
export const PAYMENTS_ACTIVITY_OWNER_USER_ID = 'user_sender';
export const PAYMENTS_ACTIVITY_WALLET_ID = 'wallet_sender';

const dinnerTransfer: PaymentsTransferRecord = {
  transferId: 'transfer_dinner_split',
  idempotencyKey: 'pay_send_mobile-dinner',
  kind: 'p2p',
  status: 'completed',
  sourceWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  destinationWalletId: 'wallet_avery',
  sourceBalanceBucket: 'available',
  destinationBalanceBucket: 'available',
  sourceAmountCents: 2_450,
  sourceCurrency: 'USD',
  destinationAmountCents: 2_450,
  destinationCurrency: 'USD',
  feeAmountCents: 0,
  feeWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  sourceRail: 'wallet',
  destinationRail: 'wallet',
  memo: 'Dinner split',
  externalReference: 'provider_p2p_0424',
  metadata: {
    source: 'phase_3d_mobile_demo',
  },
};

const coffeeRequest: PaymentsRequestRecord = {
  requestId: 'request_coffee_link',
  idempotencyKey: 'pay_request_mobile-coffee-link',
  status: 'open',
  requesterWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  payerWalletId: null,
  amountCents: 1_250,
  currency: 'USD',
  expiresAt: '2026-04-25T16:00:00.000Z',
  memo: 'Coffee run',
  metadata: {
    paymentLink: true,
    source: 'phase_3d_mobile_demo',
  },
  createdAt: '2026-04-24T14:20:00.000Z',
  updatedAt: '2026-04-24T14:20:00.000Z',
  requesterDisplayName: 'Trey',
  payerDisplayName: 'Payment link payer',
  paymentLinkId: 'link_coffee_0424',
  paymentLinkUrl: 'https://pay.mylife.app/r/coffee-0424',
  reminderCount: 1,
  lastReminderAt: '2026-04-24T15:00:00.000Z',
};

const cardTransfer: PaymentsTransferRecord = {
  transferId: 'transfer_card_market',
  idempotencyKey: 'card_capture_market_0424',
  kind: 'card_capture',
  status: 'completed',
  sourceWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  destinationWalletId: 'merchant_westside_market',
  sourceBalanceBucket: 'available',
  destinationBalanceBucket: 'available',
  sourceAmountCents: 3_280,
  sourceCurrency: 'USD',
  destinationAmountCents: 3_280,
  destinationCurrency: 'USD',
  feeAmountCents: 0,
  feeWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  sourceRail: 'card',
  destinationRail: 'merchant',
  memo: 'Groceries',
  externalReference: 'card_auth_market_0424',
  metadata: {
    source: 'phase_3d_mobile_demo',
  },
};

const escrowTransfer: PaymentsTransferRecord = {
  transferId: 'transfer_escrow_camera',
  idempotencyKey: 'escrow_hold_camera_0424',
  kind: 'escrow_hold',
  status: 'pending_review',
  sourceWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  destinationWalletId: 'merchant_camera_shop',
  sourceBalanceBucket: 'available',
  destinationBalanceBucket: 'escrow',
  sourceAmountCents: 22_500,
  sourceCurrency: 'USD',
  destinationAmountCents: 22_500,
  destinationCurrency: 'USD',
  feeAmountCents: 150,
  feeWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  sourceRail: 'wallet',
  destinationRail: 'merchant',
  memo: 'Marketplace escrow',
  externalReference: 'escrow_camera_0424',
  metadata: {
    source: 'phase_3d_mobile_demo',
    holdExpiresAt: '2026-04-25T18:00:00.000Z',
  },
};

const remittanceTransfer: PaymentsTransferRecord = {
  transferId: 'transfer_remit_sam',
  idempotencyKey: 'remit_sam_0423',
  kind: 'remittance_send',
  status: 'processing',
  sourceWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  destinationWalletId: null,
  sourceBalanceBucket: 'available',
  destinationBalanceBucket: 'pending',
  sourceAmountCents: 10_000,
  sourceCurrency: 'USD',
  destinationAmountCents: 171_200,
  destinationCurrency: 'MXN',
  feeAmountCents: 300,
  feeWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  sourceRail: 'wallet',
  destinationRail: 'remittance',
  memo: 'Family support',
  externalReference: 'remit_provider_0423',
  metadata: {
    source: 'phase_3d_mobile_demo',
  },
};

const payoutTransfer: PaymentsTransferRecord = {
  transferId: 'transfer_payout_bank',
  idempotencyKey: 'withdraw_bank_0423',
  kind: 'withdraw_wallet',
  status: 'pending_provider',
  sourceWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  destinationWalletId: 'settlement_bank_6789',
  sourceBalanceBucket: 'available',
  destinationBalanceBucket: 'pending',
  sourceAmountCents: 7_500,
  sourceCurrency: 'USD',
  destinationAmountCents: 7_500,
  destinationCurrency: 'USD',
  feeAmountCents: 75,
  feeWalletId: PAYMENTS_ACTIVITY_WALLET_ID,
  sourceRail: 'wallet',
  destinationRail: 'bank',
  memo: 'Cash out',
  externalReference: 'bank_payout_6789',
  metadata: {
    source: 'phase_3d_mobile_demo',
  },
};

export const PAYMENTS_ACTIVITY_DEMO_ITEMS: PaymentsActivityRecord[] = [
  {
    source: 'transfer',
    transfer: dinnerTransfer,
    occurredAt: '2026-04-24T15:25:00.000Z',
    counterparty: {
      id: 'user_avery',
      displayName: 'Avery Stone',
      handle: '@avery',
      verification: 'verified',
    },
    sourceDisplayName: 'Trey',
    destinationDisplayName: 'Avery Stone',
    providerName: 'MyPay Wallet',
    providerReference: 'provider_p2p_0424',
  },
  {
    source: 'request',
    request: coffeeRequest,
    counterparty: {
      id: 'payer_link',
      displayName: 'Payment link payer',
      verification: 'unverified',
    },
  },
  {
    source: 'transfer',
    transfer: cardTransfer,
    occurredAt: '2026-04-24T13:10:00.000Z',
    counterparty: {
      id: 'merchant_westside_market',
      displayName: 'Westside Market',
      descriptor: 'Card merchant',
      verification: 'verified',
    },
    sourceDisplayName: 'Trey',
    destinationDisplayName: 'Westside Market',
    providerName: 'Card Network',
    providerReference: 'card_auth_market_0424',
    cardTransactionId: 'card_txn_market_0424',
  },
  {
    source: 'transfer',
    transfer: escrowTransfer,
    occurredAt: '2026-04-24T12:15:00.000Z',
    counterparty: {
      id: 'merchant_camera_shop',
      displayName: 'Camera Shop',
      descriptor: 'Marketplace seller',
      verification: 'review',
    },
    sourceDisplayName: 'Trey',
    destinationDisplayName: 'Camera Shop',
    providerName: 'Marketplace Escrow',
    providerReference: 'escrow_camera_0424',
    market: {
      orderId: 'order_camera_0424',
      escrowId: 'escrow_camera_0424',
      itemTitle: 'Mirrorless camera kit',
      sellerUserId: 'seller_camera_shop',
      buyerUserId: PAYMENTS_ACTIVITY_OWNER_USER_ID,
    },
  },
  {
    source: 'transfer',
    transfer: remittanceTransfer,
    occurredAt: '2026-04-23T18:30:00.000Z',
    counterparty: {
      id: 'beneficiary_sam',
      displayName: 'Sam Rivera',
      verification: 'verified',
    },
    sourceDisplayName: 'Trey',
    destinationDisplayName: 'Sam Rivera',
    providerName: 'Remit Partner',
    providerReference: 'remit_provider_0423',
    quoteId: 'quote_us_mx_0423',
    remittance: {
      remittanceId: 'remit_sam_0423',
      corridor: 'US-MX',
      recipientName: 'Sam Rivera',
      recipientCountryCode: 'MX',
      payoutMethod: 'Bank deposit',
      exchangeRate: '17.120000',
      estimatedDeliveryAt: '2026-04-25T18:30:00.000Z',
    },
    cancellationWindow: {
      cancelable: true,
      cancelBy: '2026-04-24T18:30:00.000Z',
      reason: 'Cancelable until the provider marks pickup or bank deposit complete.',
    },
  },
  {
    source: 'transfer',
    transfer: payoutTransfer,
    occurredAt: '2026-04-23T10:05:00.000Z',
    counterparty: {
      id: 'bank_thread_6789',
      displayName: 'Thread Bank checking',
      descriptor: 'Bank ending 6789',
      verification: 'verified',
    },
    sourceDisplayName: 'Trey',
    destinationDisplayName: 'Thread Bank checking',
    providerName: 'Bank Partner',
    providerReference: 'bank_payout_6789',
  },
];

export const PAYMENTS_ACTIVITY_DEMO_BASE: Omit<
  PaymentsActivityFeedSnapshot,
  'filter' | 'selectedActivityId'
> = {
  ownerUserId: PAYMENTS_ACTIVITY_OWNER_USER_ID,
  walletId: PAYMENTS_ACTIVITY_WALLET_ID,
  now: PAYMENTS_ACTIVITY_SERVER_NOW,
  locale: 'en-US',
  items: PAYMENTS_ACTIVITY_DEMO_ITEMS,
  partnerBankName: 'Thread Bank',
  custodialEntityName: 'MyPay Custody Partner',
  supportContact: 'support@mylife.app',
  requestConstraints: {
    maxUses: 1,
    maxAmountCents: 50_000,
    expiresWithinHours: 72,
    reminderCooldownHours: 24,
    maxReminders: 2,
    rateLimitKey: 'requester:user_sender',
  },
};
