/**
 * LLM integration types.
 *
 * Optional LLM insights are ADDITIVE to on-device analytics.
 * Data leaves the device ONLY with explicit user consent.
 */

/** Supported LLM providers. */
export type LLMProvider = 'claude' | 'openai';

/** Stored LLM configuration (from hub_ai_config). */
export interface LLMConfig {
  provider: LLMProvider;
  apiKey: string;
  consentGiven: boolean;
  consentGivenAt: string | null;
}

/** An insight generated by the LLM (extends on-device InsightCard). */
export interface LLMInsight {
  title: string;
  description: string;
  modules: string[];
  source: 'llm';
}

/** Options for the LLM query. */
export interface LLMQueryOptions {
  /** Maximum tokens in response. */
  maxTokens?: number;
  /** Model to use (provider-specific). */
  model?: string;
  /** OpenAI Responses API reasoning effort. */
  reasoningEffort?: LLMReasoningEffort;
  /** OpenAI Responses API output verbosity. */
  verbosity?: LLMVerbosity;
  /** Whether OpenAI should store response state. Defaults to false for user privacy. */
  store?: boolean;
}

/** Result of an LLM query call. */
export interface LLMQueryResult {
  insights: LLMInsight[];
  tokensUsed: number;
  provider: LLMProvider;
}

/** A function that makes the actual HTTP call to an LLM API. */
export type LLMFetchFn = (
  url: string,
  options: {
    method: string;
    headers: Record<string, string>;
    body: string;
  },
) => Promise<{ ok: boolean; status: number; json: () => Promise<unknown> }>;

/** OpenAI Responses API reasoning effort values. */
export type LLMReasoningEffort = 'none' | 'low' | 'medium' | 'high' | 'xhigh';

/** OpenAI Responses API verbosity values. */
export type LLMVerbosity = 'low' | 'medium' | 'high';

/** Default OpenAI reasoning effort for GPT-5.5 insight generation. */
export const DEFAULT_OPENAI_REASONING_EFFORT: LLMReasoningEffort = 'medium';

/** Default OpenAI verbosity for concise GPT-5.5 insight generation. */
export const DEFAULT_OPENAI_VERBOSITY: LLMVerbosity = 'low';

/** Default models per provider. */
export const DEFAULT_MODELS: Record<LLMProvider, string> = {
  claude: 'claude-sonnet-4-5-20250514',
  openai: 'gpt-5.5',
};

/** Default max tokens for LLM response. */
export const DEFAULT_MAX_TOKENS = 1024;
