import type { ModuleDefinition } from '@mylife/module-registry';
import { CLASSES_MIGRATIONS } from './db';

export const CLASSES_MODULE: ModuleDefinition = {
  id: 'classes',
  name: 'MyClasses',
  tagline: 'Own your academic life',
  icon: '\u{1F393}',
  accentColor: '#3B82F6',
  tier: 'free',
  storageType: 'sqlite',
  tablePrefix: 'cs_',
  schemaVersion: 7,
  migrations: CLASSES_MIGRATIONS,
  syncPolicy: {
    defaultScope: 'personal_replica',
    shareable: false,
    entityRules: [
      {
        tableName: 'assignments',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'grades',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'classes',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'semesters',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
      {
        tableName: 'study_sessions',
        defaultScope: 'personal_replica',
        conflictStrategy: 'lww',
      },
    ],
  },
  navigation: {
    tabs: [
      { key: 'schedule', label: 'Schedule', icon: 'calendar' },
      { key: 'assignments', label: 'Assignments', icon: 'check-square' },
      { key: 'grades', label: 'Grades', icon: 'bar-chart-3' },
      { key: 'study', label: 'Study', icon: 'timer' },
      { key: 'degree', label: 'Degree', icon: 'graduation-cap' },
      { key: 'lifelong', label: 'Lifelong', icon: 'sparkles' },
      { key: 'applications', label: 'Applications', icon: 'briefcase' },
      { key: 'tests', label: 'Tests', icon: 'file-text' },
      { key: 'settings', label: 'Settings', icon: 'settings' },
    ],
    screens: [
      { name: 'class-detail', title: 'Class Details' },
      { name: 'class-add', title: 'Add Class' },
      { name: 'class-edit', title: 'Edit Class' },
      { name: 'teacher-detail', title: 'Teacher' },
      { name: 'teacher-add', title: 'Add Teacher' },
      { name: 'teacher-edit', title: 'Edit Teacher' },
      { name: 'assignment-detail', title: 'Assignment' },
      { name: 'assignment-add', title: 'Add Assignment' },
      { name: 'assignment-edit', title: 'Edit Assignment' },
      { name: 'degree-program-detail', title: 'Degree Program' },
      { name: 'degree-program-add', title: 'Add Degree Program' },
      { name: 'degree-program-edit', title: 'Edit Degree Program' },
      { name: 'degree-requirement-detail', title: 'Requirement' },
      { name: 'degree-requirement-add', title: 'Add Requirement' },
      { name: 'degree-requirement-edit', title: 'Edit Requirement' },
      { name: 'lifelong-courses', title: 'Courses' },
      { name: 'lifelong-course-detail', title: 'Course' },
      { name: 'lifelong-course-add', title: 'Add Course' },
      { name: 'lifelong-certifications', title: 'Certifications' },
      { name: 'lifelong-certification-detail', title: 'Certification' },
      { name: 'lifelong-certification-add', title: 'Add Certification' },
      { name: 'lifelong-goals', title: 'Goals' },
      { name: 'lifelong-goal-detail', title: 'Learning Goal' },
      { name: 'lifelong-goal-add', title: 'Add Learning Goal' },
      { name: 'application-detail', title: 'Application' },
      { name: 'application-add', title: 'Add Application' },
      { name: 'application-edit', title: 'Edit Application' },
      { name: 'standardized-test-detail', title: 'Test Score' },
      { name: 'standardized-test-add', title: 'Add Test Score' },
    ],
  },
  requiresAuth: false,
  requiresNetwork: false,
  version: '0.1.0',
};
