import type { ModuleId, ModuleDefinition } from './types';

/** All known module IDs as a readonly array, useful for iteration. */
export const MODULE_IDS: readonly ModuleId[] = [
  'books',
  'budget',
  'car',
  'classes',
  'closet',
  'cycle',
  'create',
  'dining',
  'fast',
  'flash',
  'forums',
  'friends',
  'garden',
  'habits',
  'health',
  'homes',
  'journal',
  'mail',
  'manhattan',
  'market',
  'meds',
  'mood',
  'mynews',
  'notes',
  'nutrition',
  'payments',
  'pets',
  'presence',
  'recipes',
  'rsvp',
  'shop',
  'sleep',
  'sports',
  'stars',
  'subs',
  'surf',
  'trails',
  'travel',
  'voice',
  'words',
  'workouts',
] as const;

/** Modules included in the free tier (no purchase required). */
export const FREE_MODULES: readonly ModuleId[] = [
  'classes',
  'fast',
  'forums',
  'friends',
  'journal',
  'market',
  'mood',
  'notes',
  'voice',
] as const;

/**
 * Modules that collect consumer health data subject to
 * WA MHMDA, NV SB 370, CT CTDPA, and similar health privacy laws.
 * These modules require affirmative consent before data collection begins.
 */
export const HEALTH_DATA_MODULE_IDS: readonly ModuleId[] = [
  'cycle',
  'fast',
  'habits',
  'health',
  'meds',
  'mood',
  'nutrition',
  'presence',
  'sleep',
  'workouts',
] as const;

/**
 * Maps each health data module to the types of consumer health data it collects.
 * Used in consent dialogs to inform users exactly what data is being collected.
 */
export const HEALTH_DATA_TYPES: Record<string, readonly string[]> = {
  cycle: ['menstrual cycle dates', 'cycle symptoms', 'reproductive health data'],
  fast: ['fasting periods', 'fasting duration', 'metabolic health indicators'],
  habits: ['wellness habits', 'exercise patterns', 'health-related routines'],
  health: ['vital signs', 'sleep data', 'heart rate', 'blood pressure', 'body measurements'],
  meds: ['medication names', 'dosage schedules', 'medication adherence'],
  mood: ['mental health journal entries', 'mood ratings', 'emotional state data'],
  nutrition: ['dietary intake', 'calorie tracking', 'nutritional data'],
  presence: ['screen time', 'app usage patterns', 'digital wellness metrics'],
  sleep: ['sleep journal entries', 'dream journal entries', 'sleep quality ratings'],
  workouts: ['exercise sessions', 'workout metrics', 'physical activity data'],
} as const;

/** Check if a module ID collects consumer health data. */
export function isHealthDataModule(moduleId: string): boolean {
  return (HEALTH_DATA_MODULE_IDS as readonly string[]).includes(moduleId);
}

/**
 * Complete metadata for every module in the MyLife suite.
 *
 * Each entry provides enough information for the hub app to render
 * module cards, navigation tabs, and onboarding flows without
 * loading the module's actual code.
 *
 * The `Record<ModuleId, ModuleDefinition>` annotation enforces:
 *   1. Every ModuleId has an entry (compile error if one is missing).
 *   2. Every key is a valid ModuleId (catches typos like `budge` vs `budget`).
 *   3. Every value structurally conforms to ModuleDefinition.
 *
 * Note: We intentionally use the explicit annotation rather than
 * `satisfies`, because callers assign individual entries to
 * `ModuleDefinition`-typed locals (see registry.test.ts). `satisfies`
 * without `as const` widens value property types (e.g. `id: string`) and
 * breaks that assignment; `as const satisfies` would narrow correctly but
 * would propagate `readonly` through nested array literals, forcing
 * consumers to accept `readonly` arrays they don't currently expect.
 */
export const MODULE_METADATA: Record<ModuleId, ModuleDefinition> = {
  books: {
    id: 'books',
    name: 'MyBooks',
    tagline: 'Track your reading life',
    icon: '\u{1F4DA}',
    accentColor: '#C9894D',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'bk_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'library', label: 'Library', icon: 'book' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'book-detail', title: 'Book Details' },
        { name: 'add-book', title: 'Add Book' },
        { name: 'edit-review', title: 'Edit Review' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  budget: {
    id: 'budget',
    name: 'MyBudget',
    tagline: 'Envelope budgeting made simple',
    icon: '\u{1F4B0}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'bg_',
    navigation: {
      tabs: [
        { key: 'budget', label: 'Budget', icon: 'wallet' },
        { key: 'transactions', label: 'Transactions', icon: 'list' },
        { key: 'subscriptions', label: 'Subscriptions', icon: 'repeat' },
        { key: 'reports', label: 'Reports', icon: 'pie-chart' },
        { key: 'accounts', label: 'Accounts', icon: 'credit-card' },
      ],
      screens: [
        { name: 'envelope-detail', title: 'Envelope' },
        { name: 'add-transaction', title: 'Add Transaction' },
        { name: 'subscription-detail', title: 'Subscription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  dining: {
    id: 'dining',
    name: 'MyDining',
    tagline: 'Remember every meal',
    icon: '\u{1F37D}\u{FE0F}',
    accentColor: '#DC2626',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'dn_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'utensils-crossed' },
        { key: 'restaurants', label: 'Restaurants', icon: 'map-pin' },
        { key: 'lists', label: 'Lists', icon: 'list' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'restaurant-detail', title: 'Restaurant' },
        { name: 'add-restaurant', title: 'Add Restaurant' },
        { name: 'visit-detail', title: 'Visit' },
        { name: 'add-visit', title: 'Log Visit' },
        { name: 'dish-detail', title: 'Dish' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  fast: {
    id: 'fast',
    name: 'MyFast',
    tagline: 'Intermittent fasting timer',
    icon: '\u{23F1}\u{FE0F}',
    accentColor: '#14B8A6',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'ft_',
    navigation: {
      tabs: [
        { key: 'timer', label: 'Timer', icon: 'clock' },
        { key: 'history', label: 'History', icon: 'calendar' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'fast-detail', title: 'Fast Details' },
        { name: 'choose-plan', title: 'Choose Plan' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  health: {
    id: 'health',
    name: 'MyHealth',
    tagline: 'Your complete health companion',
    icon: '\u{1FA7A}',
    accentColor: '#10B981',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'hl_',
    freeSections: ['fasting'],
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'activity' },
        { key: 'fasting', label: 'Fasting', icon: 'clock' },
        { key: 'vitals', label: 'Vitals', icon: 'heart' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'vault', label: 'Vault', icon: 'shield' },
      ],
      screens: [
        { name: 'fast-detail', title: 'Fast Details' },
        { name: 'choose-plan', title: 'Choose Plan' },
        { name: 'med-detail', title: 'Medication' },
        { name: 'add-med', title: 'Add Medication' },
        { name: 'schedule', title: 'Schedule' },
        { name: 'interactions', title: 'Interactions' },
        { name: 'measurement-log', title: 'Log Measurement' },
        { name: 'vital-detail', title: 'Vital Detail' },
        { name: 'cycle-tracker', title: 'Cycle Tracker' },
        { name: 'sleep-detail', title: 'Sleep Detail' },
        { name: 'mood-check-in', title: 'Mood Check-In' },
        { name: 'correlation', title: 'Correlations' },
        { name: 'wellness-timeline', title: 'Wellness Timeline' },
        { name: 'export', title: 'Export Data' },
        { name: 'add-document', title: 'Add Document' },
        { name: 'document-viewer', title: 'Document' },
        { name: 'emergency-info', title: 'Emergency Info' },
        { name: 'health-sync-settings', title: 'Health Sync' },
        { name: 'goal-detail', title: 'Goal' },
        { name: 'add-goal', title: 'New Goal' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  recipes: {
    id: 'recipes',
    name: 'BestChef',
    tagline: 'Find the best recipe for every dish',
    icon: '\u{1F373}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'rc_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'recipes', label: 'Recipes', icon: 'book-open' },
        { key: 'meal-plan', label: 'Meal Planner', icon: 'calendar' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'recipe-detail', title: 'Recipe' },
        { name: 'add-recipe', title: 'Add Recipe' },
        { name: 'cooking-mode', title: 'Cooking Mode' },
        { name: 'import-url', title: 'Import from URL' },
      ],
    },
    requiresAuth: false,
    // BestChef's headline function (cloud voting, dish catalog, leaderboards,
    // submissions, feed) requires network. The local kitchen subset works
    // offline, but the module's core value does not. Matches
    // RECIPES_MODULE.requiresNetwork in modules/bestchef/src/definition.ts.
    requiresNetwork: true,
    version: '0.1.0',
  },
  rsvp: {
    id: 'rsvp',
    name: 'MyRSVP',
    tagline: 'Events, invites, and RSVP tracking',
    icon: '\u{1F48C}',
    accentColor: '#FB7185',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'rv_',
    navigation: {
      tabs: [
        { key: 'events', label: 'Events', icon: 'calendar' },
        { key: 'guests', label: 'Guests', icon: 'users' },
        { key: 'polls', label: 'Polls', icon: 'bar-chart' },
        { key: 'feed', label: 'Feed', icon: 'message-circle' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'event-detail', title: 'Event Details' },
        { name: 'invite-management', title: 'Invites' },
        { name: 'check-in', title: 'Check-in' },
        { name: 'photo-album', title: 'Photo Album' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  surf: {
    id: 'surf',
    name: 'MySurf',
    tagline: 'Surf forecasts and spot intel',
    icon: '\u{1F3C4}',
    accentColor: '#3B82F6',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'forecast', label: 'Forecast', icon: 'cloud' },
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'spots', label: 'Spots', icon: 'map-pin' },
        { key: 'alerts', label: 'Alerts', icon: 'bell' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'spot-detail', title: 'Spot Details' },
        { name: 'buoy-detail', title: 'Buoy Data' },
        { name: 'session-log', title: 'Session Log' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  workouts: {
    id: 'workouts',
    name: 'MyWorkouts',
    tagline: 'Body-map guided workouts and builder',
    icon: '\u{1F4AA}',
    accentColor: '#EF4444',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'home' },
        { key: 'explore', label: 'Explore', icon: 'search' },
        { key: 'workouts', label: 'Workouts', icon: 'layers' },
        { key: 'progress', label: 'Progress', icon: 'trending-up' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'workout-detail', title: 'Workout' },
        { name: 'exercise-detail', title: 'Exercise' },
        { name: 'builder', title: 'Workout Builder' },
        { name: 'recordings', title: 'Form Recordings' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.2.0',
  },
  homes: {
    id: 'homes',
    name: 'MyHomes',
    tagline: 'Real estate, reimagined',
    icon: '\u{1F3E0}',
    accentColor: '#D97706',
    tier: 'premium',
    storageType: 'sqlite',
    navigation: {
      tabs: [
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'saved', label: 'Saved', icon: 'heart' },
        { key: 'alerts', label: 'Alerts', icon: 'bell' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'listing-detail', title: 'Listing' },
        { name: 'agent-profile', title: 'Agent' },
        { name: 'mortgage-calc', title: 'Mortgage Calculator' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  car: {
    id: 'car',
    name: 'MyCar',
    tagline: 'Your complete vehicle companion',
    icon: '\u{1F697}',
    accentColor: '#6366F1',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cr_',
    navigation: {
      tabs: [
        { key: 'dashboard', label: 'Dashboard', icon: 'gauge' },
        { key: 'maintenance', label: 'Maintenance', icon: 'wrench' },
        { key: 'fuel', label: 'Fuel', icon: 'droplet' },
        { key: 'trips', label: 'Trips', icon: 'map-pin' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'vehicle-detail', title: 'Vehicle' },
        { name: 'add-record', title: 'Add Record' },
        { name: 'service-history', title: 'Service History' },
        { name: 'insurance', title: 'Insurance' },
        { name: 'registration', title: 'Registration' },
        { name: 'tires', title: 'Tires' },
        { name: 'parking', title: 'Parking' },
        { name: 'diagnostics', title: 'Diagnostics' },
        { name: 'cost-analysis', title: 'Cost Analysis' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.2.0',
  },
  classes: {
    id: 'classes',
    name: 'MyClasses',
    tagline: 'Own your academic life',
    icon: '\u{1F393}',
    accentColor: '#3B82F6',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'cs_',
    navigation: {
      tabs: [
        { key: 'schedule', label: 'Schedule', icon: 'calendar' },
        { key: 'assignments', label: 'Assignments', icon: 'check-square' },
        { key: 'grades', label: 'Grades', icon: 'bar-chart-3' },
        { key: 'study', label: 'Study', icon: 'timer' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'class-detail', title: 'Class Details' },
        { name: 'assignment-detail', title: 'Assignment' },
        { name: 'grade-scenario', title: 'What-If Grade' },
        { name: 'study-session', title: 'Study Session' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  habits: {
    id: 'habits',
    name: 'MyHabits',
    tagline: 'Build habits that stick',
    icon: '\u{2705}',
    accentColor: '#8B5CF6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'hb_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'check-circle' },
        { key: 'habits', label: 'Habits', icon: 'list' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'habit-detail', title: 'Habit' },
        { name: 'add-habit', title: 'New Habit' },
        { name: 'streak-detail', title: 'Streak' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  meds: {
    id: 'meds',
    name: 'MyMeds',
    tagline: 'Never miss a dose',
    icon: '\u{1F48A}',
    accentColor: '#06B6D4',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'md_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'clock' },
        { key: 'medications', label: 'Medications', icon: 'pill' },
        { key: 'history', label: 'History', icon: 'calendar' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'med-detail', title: 'Medication' },
        { name: 'add-med', title: 'Add Medication' },
        { name: 'schedule', title: 'Schedule' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  words: {
    id: 'words',
    name: 'MyWords',
    tagline: 'Dictionary + thesaurus in 270 languages',
    icon: '\u{1F4D6}',
    accentColor: '#0EA5E9',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'wd_',
    navigation: {
      tabs: [
        { key: 'lookup', label: 'Lookup', icon: 'search' },
        { key: 'helper', label: 'Word Helper', icon: 'sparkles' },
        { key: 'languages', label: 'Languages', icon: 'globe' },
        { key: 'saved', label: 'Saved', icon: 'bookmark' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'word-detail', title: 'Word' },
        { name: 'saved-word-detail', title: 'Saved Word' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  closet: {
    id: 'closet',
    name: 'MyCloset',
    tagline: 'Your wardrobe, fully private',
    icon: '\u{1F457}',
    accentColor: '#E879A8',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cl_',
    navigation: {
      tabs: [
        { key: 'wardrobe', label: 'Wardrobe', icon: 'shirt' },
        { key: 'outfits', label: 'Outfits', icon: 'layers' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart-2' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'item-detail', title: 'Item' },
        { name: 'outfit-detail', title: 'Outfit' },
        { name: 'add-item', title: 'Add Item' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  cycle: {
    id: 'cycle',
    name: 'MyCycle',
    tagline: 'Private period and fertility tracker',
    icon: '\u{1F319}',
    accentColor: '#F472B6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'cy_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'calendar-check' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'log-day', title: 'Log Day' },
        { name: 'cycle-detail', title: 'Cycle Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  create: {
    id: 'create',
    name: 'MyCreate',
    tagline: 'Track your creative journey',
    icon: '\u{1F3A8}',
    accentColor: '#D946EF',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'ct_',
    navigation: {
      tabs: [
        { key: 'projects', label: 'Projects', icon: 'palette' },
        { key: 'practice', label: 'Practice', icon: 'timer' },
        { key: 'skills', label: 'Skills', icon: 'sparkles' },
        { key: 'portfolio', label: 'Portfolio', icon: 'image' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'project-detail', title: 'Project' },
        { name: 'add-project', title: 'Add Project' },
        { name: 'log-progress', title: 'Log Progress' },
        { name: 'skill-detail', title: 'Skill' },
        { name: 'portfolio-piece', title: 'Portfolio Piece' },
        { name: 'equipment', title: 'Equipment' },
        { name: 'settings', title: 'Settings' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  forums: {
    id: 'forums',
    name: 'MyForums',
    tagline: 'Community discussions, your way',
    icon: '\u{1F4AC}',
    accentColor: '#F43F5E',
    tier: 'free',
    storageType: 'supabase',
    tablePrefix: 'fr_',
    navigation: {
      tabs: [
        { key: 'feed', label: 'Feed', icon: 'rss' },
        { key: 'communities', label: 'Communities', icon: 'users' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'saved', label: 'Saved', icon: 'bookmark' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'community-detail', title: 'Community' },
        { name: 'thread-detail', title: 'Thread' },
        { name: 'create-thread', title: 'New Thread' },
        { name: 'reply-thread', title: 'Reply' },
        { name: 'create-community', title: 'New Community' },
        { name: 'member-list', title: 'Members' },
        { name: 'mod-dashboard', title: 'Moderation' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  flash: {
    id: 'flash',
    name: 'MyFlash',
    tagline: 'Never forget what matters',
    icon: '\u{26A1}',
    accentColor: '#FBBF24',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'fl_',
    navigation: {
      tabs: [
        { key: 'study', label: 'Study', icon: 'play-circle' },
        { key: 'decks', label: 'Decks', icon: 'layers' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart-2' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'deck-detail', title: 'Deck' },
        { name: 'card-editor', title: 'Edit Card' },
        { name: 'review', title: 'Review' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  friends: {
    id: 'friends',
    name: 'MyFriends',
    tagline: 'Remember who matters to you',
    icon: '\u{1FAC2}',
    accentColor: '#EC4899',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'fn_',
    migrations: [],
    navigation: {
      tabs: [
        { key: 'people', label: 'People', icon: 'users' },
        { key: 'hangouts', label: 'Hangouts', icon: 'calendar-heart' },
        { key: 'birthdays', label: 'Birthdays', icon: 'cake' },
        { key: 'memories', label: 'Memories', icon: 'heart' },
      ],
      screens: [
        { name: 'person-detail', title: 'Person' },
        { name: 'add-person', title: 'Add Person' },
        { name: 'edit-person', title: 'Edit Person' },
        { name: 'log-hangout', title: 'Log Hangout' },
        { name: 'hangout-detail', title: 'Hangout' },
        { name: 'gift-tracker', title: 'Gifts' },
        { name: 'add-memory', title: 'Add Memory' },
        { name: 'circles', title: 'Circles' },
        { name: 'settings', title: 'Settings' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  garden: {
    id: 'garden',
    name: 'MyGarden',
    tagline: 'Plant care and garden planner',
    icon: '\u{1F331}',
    accentColor: '#22C55E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'gd_',
    navigation: {
      tabs: [
        { key: 'garden', label: 'Garden', icon: 'flower-2' },
        { key: 'tasks', label: 'Tasks', icon: 'check-circle' },
        { key: 'journal', label: 'Journal', icon: 'book-open' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'plant-detail', title: 'Plant' },
        { name: 'add-plant', title: 'Add Plant' },
        { name: 'journal-entry', title: 'Journal Entry' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  journal: {
    id: 'journal',
    name: 'MyJournal',
    tagline: 'Private daily journal',
    icon: '\u{1F4D3}',
    accentColor: '#A78BFA',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'jn_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'edit-3' },
        { key: 'entries', label: 'Entries', icon: 'book-open' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'entry-detail', title: 'Entry' },
        { name: 'new-entry', title: 'New Entry' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  market: {
    id: 'market',
    name: 'MyMarket',
    tagline: 'Buy, sell, and trade with your community',
    icon: '\u{1F3EA}',
    accentColor: '#E11D48',
    tier: 'free',
    storageType: 'supabase',
    tablePrefix: 'mk_',
    navigation: {
      tabs: [
        { key: 'browse', label: 'Browse', icon: 'search' },
        { key: 'sell', label: 'Sell', icon: 'plus-circle' },
        { key: 'messages', label: 'Messages', icon: 'message-circle' },
        { key: 'saved', label: 'Saved', icon: 'heart' },
        { key: 'profile', label: 'Profile', icon: 'user' },
      ],
      screens: [
        { name: 'listing-detail', title: 'Listing' },
        { name: 'create-listing', title: 'New Listing' },
        { name: 'edit-listing', title: 'Edit Listing' },
        { name: 'chat-thread', title: 'Chat' },
        { name: 'category-browser', title: 'Categories' },
        { name: 'search-results', title: 'Search' },
        { name: 'seller-profile', title: 'Seller' },
        { name: 'checkout', title: 'Checkout' },
        { name: 'payment-settings', title: 'Payment Settings' },
        { name: 'verification', title: 'Verification' },
        { name: 'dispute', title: 'Dispute' },
        { name: 'dispute-detail', title: 'Dispute Detail' },
        { name: 'shipping-detail', title: 'Tracking' },
        { name: 'services', title: 'Services' },
        { name: 'service-detail', title: 'Service Provider' },
        { name: 'create-service-listing', title: 'Offer a Service' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  mail: {
    id: 'mail',
    name: 'MyMail',
    tagline: 'Self-hosted private email',
    icon: '\u{1F4EC}',
    accentColor: '#3B82F6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'ml_',
    navigation: {
      tabs: [
        { key: 'inbox', label: 'Inbox', icon: 'inbox' },
        { key: 'compose', label: 'Compose', icon: 'edit' },
        { key: 'folders', label: 'Folders', icon: 'folder' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'message-detail', title: 'Message' },
        { name: 'compose-message', title: 'Compose' },
        { name: 'server-setup', title: 'Server Setup' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  manhattan: {
    id: 'manhattan',
    name: 'Manhattan',
    tagline: 'Your city, planned',
    icon: '\u{1F5FD}',
    accentColor: '#E4572E',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'mh_',
    navigation: {
      tabs: [
        { key: 'discover', label: 'Discover', icon: 'compass' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'pins', label: 'Pins', icon: 'map-pin' },
        { key: 'plans', label: 'Plans', icon: 'list' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'event-detail', title: 'Event' },
        { name: 'pin-detail', title: 'Pin' },
        { name: 'plan-detail', title: 'Plan' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  mood: {
    id: 'mood',
    name: 'MyMood',
    tagline: 'Track your emotional wellness',
    icon: '\u{1F3AD}',
    accentColor: '#FB923C',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'mo_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'smile' },
        { key: 'history', label: 'History', icon: 'clock' },
        { key: 'insights', label: 'Insights', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'log-mood', title: 'Log Mood' },
        { name: 'day-detail', title: 'Day Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  mynews: {
    id: 'mynews',
    name: 'MyNews',
    tagline: 'Open journalism, improved by everyone',
    icon: '\u{1F4F0}',
    accentColor: '#8BCFF0',
    tier: 'premium',
    storageType: 'supabase',
    tablePrefix: 'nw_',
    navigation: {
      tabs: [
        { key: 'today', label: 'Today', icon: 'home' },
        { key: 'discover', label: 'Discover', icon: 'compass' },
        { key: 'desk', label: 'Desk', icon: 'edit-3' },
        { key: 'support', label: 'Support', icon: 'heart' },
        { key: 'me', label: 'Me', icon: 'user' },
      ],
      screens: [
        { name: 'article-detail', title: 'Article' },
        { name: 'journalist-detail', title: 'Journalist' },
        { name: 'suggestion-detail', title: 'Suggestion' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  notes: {
    id: 'notes',
    name: 'MyNotes',
    tagline: 'Plain markdown notes, no lock-in',
    icon: '\u{1F4DD}',
    accentColor: '#64748B',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'nt_',
    navigation: {
      tabs: [
        { key: 'notes', label: 'Notes', icon: 'file-text' },
        { key: 'folders', label: 'Folders', icon: 'folder' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'note-editor', title: 'Edit Note' },
        { name: 'note-preview', title: 'Preview' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  nutrition: {
    id: 'nutrition',
    name: 'MyNutrition',
    tagline: 'Track calories, macros, and 84+ nutrients',
    icon: '\u{1F957}',
    accentColor: '#F97316',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'nu_',
    navigation: {
      tabs: [
        { key: 'diary', label: 'Diary', icon: 'book-open' },
        { key: 'search', label: 'Search', icon: 'search' },
        { key: 'dashboard', label: 'Dashboard', icon: 'pie-chart' },
        { key: 'trends', label: 'Trends', icon: 'trending-up' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'food-detail', title: 'Food Details' },
        { name: 'add-food', title: 'Add Food' },
        { name: 'scan', title: 'Scan Barcode' },
        { name: 'photo', title: 'Photo Log' },
        { name: 'meal-edit', title: 'Edit Meal' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  payments: {
    id: 'payments',
    name: 'MyPay',
    tagline: 'Wallet, transfers, and money controls',
    icon: '\u{1F4B8}',
    accentColor: '#00C389',
    tier: 'premium',
    storageType: 'supabase',
    tablePrefix: 'pay_',
    navigation: {
      tabs: [
        { key: 'wallet', label: 'Wallet', icon: 'wallet' },
        { key: 'activity', label: 'Activity', icon: 'arrow-left-right' },
        { key: 'cards', label: 'Cards', icon: 'credit-card' },
        { key: 'protect', label: 'Protect', icon: 'shield-check' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'send-money', title: 'Send Money' },
        { name: 'request-money', title: 'Request Money' },
        { name: 'cash-out', title: 'Cash Out' },
        { name: 'add-funding-source', title: 'Add Funding Source' },
        { name: 'transaction-detail', title: 'Transaction' },
        { name: 'dispute-center', title: 'Disputes' },
        { name: 'dispute-detail', title: 'Dispute Detail' },
        { name: 'remittance-quote', title: 'Remittance Quote' },
        { name: 'remittance-confirm', title: 'Confirm Transfer' },
        { name: 'compliance-review', title: 'Compliance Review' },
      ],
    },
    requiresAuth: true,
    requiresNetwork: true,
    version: '0.1.0',
  },
  pets: {
    id: 'pets',
    name: 'MyPets',
    tagline: 'Pet health records and care tracker',
    icon: '\u{1F43E}',
    accentColor: '#F59E0B',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'pt_',
    navigation: {
      tabs: [
        { key: 'pets', label: 'Pets', icon: 'heart' },
        { key: 'health', label: 'Health', icon: 'activity' },
        { key: 'reminders', label: 'Reminders', icon: 'bell' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'pet-detail', title: 'Pet' },
        { name: 'add-pet', title: 'Add Pet' },
        { name: 'vet-visit', title: 'Vet Visit' },
        { name: 'vaccination', title: 'Vaccination' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  presence: {
    id: 'presence',
    name: 'MyPresence',
    tagline: 'Put your phone down. Pick your life up.',
    icon: '\u{1F9D8}',
    accentColor: '#0891B2',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'pr_',
    navigation: {
      tabs: [
        { key: 'home', label: 'Home', icon: 'smartphone' },
        { key: 'stats', label: 'Stats', icon: 'bar-chart' },
        { key: 'sessions', label: 'Sessions', icon: 'clock' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'onboarding', title: 'Get Started' },
        { name: 'intentions', title: 'App Intentions' },
        { name: 'intention-prompt', title: 'Intention' },
        { name: 'session-active', title: 'Focus Session' },
        { name: 'session-complete', title: 'Session Complete' },
        { name: 'reflection', title: 'Reflection' },
        { name: 'badges', title: 'Badges' },
        { name: 'insights', title: 'Insights' },
        { name: 'report', title: 'Daily Report' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  shop: {
    id: 'shop',
    name: 'MyShop',
    tagline: 'Your private shopping memory',
    icon: '\u{1F6CD}\u{FE0F}',
    accentColor: '#10B981',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'sh_',
    navigation: {
      tabs: [
        { key: 'index', label: 'Wishlist', icon: 'heart' },
        { key: 'purchases', label: 'Purchases', icon: 'receipt' },
        { key: 'warranties', label: 'Warranties', icon: 'shield-check' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  sports: {
    id: 'sports',
    name: 'MySports',
    tagline: 'Your sports life, together',
    icon: '\u26BD',
    accentColor: '#16A34A',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'sp_',
    schemaVersion: 8,
    migrations: [
      {
        version: 1,
        description: 'Initial sports schema -- teams + settings',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_teams (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    league TEXT NOT NULL,
    sport TEXT NOT NULL,
    conference TEXT,
    division TEXT,
    logo_url TEXT,
    primary_color TEXT,
    secondary_color TEXT,
    follow_tier TEXT NOT NULL DEFAULT 'casual' CHECK (follow_tier IN ('diehard','casual','occasional')),
    notify_start INTEGER NOT NULL DEFAULT 1,
    notify_end INTEGER NOT NULL DEFAULT 1,
    notify_close INTEGER NOT NULL DEFAULT 0,
    notify_trades INTEGER NOT NULL DEFAULT 0,
    is_rival INTEGER NOT NULL DEFAULT 0,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS idx_sp_teams_league ON sp_teams(league)`,
          `CREATE INDEX IF NOT EXISTS idx_sp_teams_sport ON sp_teams(sport)`,
          `CREATE INDEX IF NOT EXISTS idx_sp_teams_tier ON sp_teams(follow_tier)`,
          `CREATE INDEX IF NOT EXISTS idx_sp_teams_rival ON sp_teams(is_rival) WHERE is_rival = 1`,
        ],
        down: [
          'DROP TABLE IF EXISTS sp_settings',
          'DROP TABLE IF EXISTS sp_teams',
        ],
      },
      {
        version: 2,
        description: 'Sports V2 -- live scores cache (sp_games)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_games (
    id TEXT PRIMARY KEY,
    league TEXT NOT NULL,
    sport TEXT NOT NULL,
    home_team_id TEXT,
    home_team_name TEXT NOT NULL,
    home_score INTEGER,
    away_team_id TEXT,
    away_team_name TEXT NOT NULL,
    away_score INTEGER,
    start_at INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('scheduled','live','final')),
    period TEXT,
    clock TEXT,
    venue TEXT,
    broadcast TEXT,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_games_start_at_idx ON sp_games(start_at)`,
          `CREATE INDEX IF NOT EXISTS sp_games_status_idx ON sp_games(status)`,
          `CREATE INDEX IF NOT EXISTS sp_games_team_idx ON sp_games(home_team_id, away_team_id)`,
        ],
        down: ['DROP TABLE IF EXISTS sp_games'],
      },
      {
        version: 3,
        description:
          'Sports V3 -- local notifications dedupe log (sp_notifications_log)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_notifications_log (
    id TEXT PRIMARY KEY,
    team_id TEXT NOT NULL,
    game_id TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN ('start','final','close','overtime','rival_loss','trade')),
    fired_at INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    payload_json TEXT
  )`,
          `CREATE UNIQUE INDEX IF NOT EXISTS sp_notifications_log_dedupe_idx
    ON sp_notifications_log(team_id, game_id, event_type)`,
          `CREATE INDEX IF NOT EXISTS sp_notifications_log_fired_at_idx
    ON sp_notifications_log(fired_at DESC)`,
        ],
        down: ['DROP TABLE IF EXISTS sp_notifications_log'],
      },
      {
        version: 4,
        description:
          'Sports V4 -- betting journal + bankroll (sp_bets, sp_bet_legs, sp_bankroll)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_bets (
    id TEXT PRIMARY KEY,
    sport TEXT NOT NULL,
    league TEXT NOT NULL,
    game_id TEXT,
    team_id TEXT,
    bet_type TEXT NOT NULL CHECK (bet_type IN ('moneyline','spread','total','prop','parlay','future')),
    description TEXT NOT NULL,
    sportsbook TEXT NOT NULL,
    odds_american INTEGER NOT NULL,
    stake_cents INTEGER NOT NULL,
    potential_payout_cents INTEGER NOT NULL,
    units REAL NOT NULL,
    result TEXT NOT NULL DEFAULT 'pending' CHECK (result IN ('pending','won','lost','push','void')),
    profit_loss_cents INTEGER NOT NULL DEFAULT 0,
    placed_at INTEGER NOT NULL,
    settled_at INTEGER,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_bet_legs (
    id TEXT PRIMARY KEY,
    bet_id TEXT NOT NULL REFERENCES sp_bets(id) ON DELETE CASCADE,
    leg_index INTEGER NOT NULL,
    game_id TEXT,
    team_id TEXT,
    description TEXT NOT NULL,
    odds_american INTEGER NOT NULL,
    leg_type TEXT NOT NULL CHECK (leg_type IN ('moneyline','spread','total','prop')),
    result TEXT NOT NULL DEFAULT 'pending' CHECK (result IN ('pending','won','lost','push','void')),
    settled_at INTEGER,
    created_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_bankroll (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    starting_cents INTEGER NOT NULL,
    current_cents INTEGER NOT NULL,
    unit_size_cents INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_bets_placed_at_idx ON sp_bets(placed_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_bets_result_placed_at_idx ON sp_bets(result, placed_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_bets_game_id_idx ON sp_bets(game_id)`,
          `CREATE INDEX IF NOT EXISTS sp_bets_sport_league_idx ON sp_bets(sport, league)`,
          `CREATE INDEX IF NOT EXISTS sp_bet_legs_bet_id_idx ON sp_bet_legs(bet_id)`,
        ],
        down: [
          'DROP TABLE IF EXISTS sp_bet_legs',
          'DROP TABLE IF EXISTS sp_bets',
          'DROP TABLE IF EXISTS sp_bankroll',
        ],
      },
      {
        version: 5,
        description:
          'Sports V5 -- fantasy leagues + transactions (sp_fantasy_leagues, sp_fantasy_transactions)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_fantasy_leagues (
    id TEXT PRIMARY KEY,
    platform TEXT NOT NULL CHECK (platform IN ('espn','yahoo','sleeper','nfl','cbs','custom')),
    sport TEXT NOT NULL,
    league_name TEXT NOT NULL,
    season TEXT NOT NULL,
    format TEXT NOT NULL CHECK (format IN ('redraft','dynasty','keeper','bestball')),
    team_name TEXT NOT NULL,
    roster_json TEXT NOT NULL DEFAULT '[]',
    record_wins INTEGER NOT NULL DEFAULT 0,
    record_losses INTEGER NOT NULL DEFAULT 0,
    record_ties INTEGER NOT NULL DEFAULT 0,
    points_for REAL NOT NULL DEFAULT 0,
    points_against REAL NOT NULL DEFAULT 0,
    standings_position INTEGER,
    buy_in_cents INTEGER,
    prize_cents INTEGER,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_fantasy_transactions (
    id TEXT PRIMARY KEY,
    league_id TEXT NOT NULL REFERENCES sp_fantasy_leagues(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('draft','trade','waiver_add','waiver_drop','fa_add')),
    players_in_json TEXT NOT NULL DEFAULT '[]',
    players_out_json TEXT NOT NULL DEFAULT '[]',
    description TEXT NOT NULL,
    reasoning_md TEXT,
    happened_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_fantasy_leagues_platform_season ON sp_fantasy_leagues(platform, season)`,
          `CREATE INDEX IF NOT EXISTS sp_fantasy_leagues_sport ON sp_fantasy_leagues(sport)`,
          `CREATE INDEX IF NOT EXISTS sp_fantasy_transactions_league ON sp_fantasy_transactions(league_id, happened_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_fantasy_transactions_type ON sp_fantasy_transactions(type)`,
        ],
        down: [
          'DROP TABLE IF EXISTS sp_fantasy_transactions',
          'DROP TABLE IF EXISTS sp_fantasy_leagues',
        ],
      },
      {
        version: 6,
        description:
          'Sports V6 -- personal participation + rec leagues (sp_participation_sessions, sp_rec_leagues)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_participation_sessions (
    id TEXT PRIMARY KEY,
    sport TEXT NOT NULL,
    activity TEXT NOT NULL CHECK (activity IN ('game','practice','pickup','training')),
    started_at INTEGER NOT NULL,
    duration_minutes INTEGER,
    location TEXT,
    teammates_json TEXT NOT NULL DEFAULT '[]',
    stats_json TEXT NOT NULL DEFAULT '{}',
    personal_best INTEGER NOT NULL DEFAULT 0,
    mood_before INTEGER CHECK (mood_before IS NULL OR mood_before BETWEEN 1 AND 5),
    mood_after INTEGER CHECK (mood_after IS NULL OR mood_after BETWEEN 1 AND 5),
    injury_notes TEXT,
    notes_md TEXT,
    photo_ids_json TEXT NOT NULL DEFAULT '[]',
    created_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_rec_leagues (
    id TEXT PRIMARY KEY,
    sport TEXT NOT NULL,
    league_name TEXT NOT NULL,
    team_name TEXT NOT NULL,
    season TEXT NOT NULL,
    schedule_json TEXT NOT NULL DEFAULT '[]',
    roster_json TEXT NOT NULL DEFAULT '[]',
    record_wins INTEGER NOT NULL DEFAULT 0,
    record_losses INTEGER NOT NULL DEFAULT 0,
    record_ties INTEGER NOT NULL DEFAULT 0,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_participation_sport_started ON sp_participation_sessions(sport, started_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_participation_activity ON sp_participation_sessions(activity)`,
          `CREATE INDEX IF NOT EXISTS sp_participation_pb ON sp_participation_sessions(personal_best) WHERE personal_best = 1`,
          `CREATE INDEX IF NOT EXISTS sp_rec_leagues_sport_season ON sp_rec_leagues(sport, season)`,
        ],
        down: [
          'DROP TABLE IF EXISTS sp_participation_sessions',
          'DROP TABLE IF EXISTS sp_rec_leagues',
        ],
      },
      {
        version: 7,
        description:
          'Sports V7 -- events + venues + memorabilia (sp_attendance, sp_venues, sp_memorabilia)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_attendance (
    id TEXT PRIMARY KEY,
    game_id TEXT,
    venue_id TEXT,
    venue_name TEXT NOT NULL,
    section TEXT,
    row_label TEXT,
    seat TEXT,
    companions_json TEXT NOT NULL DEFAULT '[]',
    cost_cents INTEGER NOT NULL DEFAULT 0,
    tailgate_notes_md TEXT,
    parking_notes_md TEXT,
    rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    notes_md TEXT,
    photo_ids_json TEXT NOT NULL DEFAULT '[]',
    attended_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_venues (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT,
    country TEXT,
    sport TEXT,
    team TEXT,
    capacity INTEGER,
    visited INTEGER NOT NULL DEFAULT 0,
    first_visit_at INTEGER,
    last_visit_at INTEGER,
    rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    bucket_list INTEGER NOT NULL DEFAULT 0,
    lat REAL,
    lng REAL,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE TABLE IF NOT EXISTS sp_memorabilia (
    id TEXT PRIMARY KEY,
    item_type TEXT NOT NULL CHECK (item_type IN ('card','jersey','signed','ticket','ball','hat','other')),
    description TEXT NOT NULL,
    sport TEXT,
    team TEXT,
    player TEXT,
    acquired_at INTEGER,
    purchase_price_cents INTEGER NOT NULL DEFAULT 0,
    estimated_value_cents INTEGER NOT NULL DEFAULT 0,
    photo_ids_json TEXT NOT NULL DEFAULT '[]',
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_attendance_attended_at_idx ON sp_attendance(attended_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_attendance_game_idx ON sp_attendance(game_id)`,
          `CREATE INDEX IF NOT EXISTS sp_attendance_venue_idx ON sp_attendance(venue_id)`,
          `CREATE INDEX IF NOT EXISTS sp_venues_visited_idx ON sp_venues(visited)`,
          `CREATE INDEX IF NOT EXISTS sp_venues_bucket_list_idx ON sp_venues(bucket_list)`,
          `CREATE INDEX IF NOT EXISTS sp_venues_sport_idx ON sp_venues(sport)`,
          `CREATE INDEX IF NOT EXISTS sp_venues_team_idx ON sp_venues(team)`,
          `CREATE INDEX IF NOT EXISTS sp_memorabilia_acquired_idx ON sp_memorabilia(acquired_at DESC)`,
          `CREATE INDEX IF NOT EXISTS sp_memorabilia_item_type_idx ON sp_memorabilia(item_type)`,
          `CREATE INDEX IF NOT EXISTS sp_memorabilia_sport_idx ON sp_memorabilia(sport)`,
        ],
        down: [
          'DROP TABLE IF EXISTS sp_attendance',
          'DROP TABLE IF EXISTS sp_venues',
          'DROP TABLE IF EXISTS sp_memorabilia',
        ],
      },
      {
        version: 8,
        description:
          'Sports V8 -- predictions journal (sp_predictions)',
        up: [
          `CREATE TABLE IF NOT EXISTS sp_predictions (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('champion','mvp','roty','division','conference','player_of_year','over_under','custom')),
    sport TEXT,
    league TEXT,
    season TEXT NOT NULL,
    prediction_text TEXT NOT NULL,
    reasoning_md TEXT,
    confidence INTEGER CHECK (confidence IS NULL OR confidence BETWEEN 1 AND 5),
    predicted_at INTEGER NOT NULL,
    locks_at INTEGER,
    settled_at INTEGER,
    was_correct INTEGER CHECK (was_correct IS NULL OR was_correct IN (0, 1)),
    result_text TEXT,
    notes_md TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  )`,
          `CREATE INDEX IF NOT EXISTS sp_predictions_settled_at_idx ON sp_predictions(settled_at)`,
          `CREATE INDEX IF NOT EXISTS sp_predictions_category_idx ON sp_predictions(category)`,
          `CREATE INDEX IF NOT EXISTS sp_predictions_sport_idx ON sp_predictions(sport)`,
          `CREATE INDEX IF NOT EXISTS sp_predictions_season_idx ON sp_predictions(season)`,
          `CREATE INDEX IF NOT EXISTS sp_predictions_predicted_at_idx ON sp_predictions(predicted_at DESC)`,
        ],
        down: ['DROP TABLE IF EXISTS sp_predictions'],
      },
    ],
    navigation: {
      tabs: [
        { key: 'index', label: 'Scores', icon: 'radio' },
        { key: 'teams', label: 'Teams', icon: 'users' },
        { key: 'betting', label: 'Betting', icon: 'dollar-sign' },
        { key: 'fantasy', label: 'Fantasy', icon: 'trophy' },
        { key: 'play', label: 'Play', icon: 'activity' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [],
    },
    requiresAuth: false,
    requiresNetwork: true,
    version: '0.1.0',
  },
  sleep: {
    id: 'sleep',
    name: 'MySleep',
    tagline: 'Track your sleep, remember your dreams',
    icon: '\u{1F319}',
    accentColor: '#A78BFA',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'sl_',
    schemaVersion: 1,
    navigation: {
      tabs: [
        { key: 'log', label: 'Sleep', icon: 'moon' },
        { key: 'dreams', label: 'Dreams', icon: 'sparkles' },
        { key: 'insights', label: 'Insights', icon: 'bar-chart-3' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'entry-detail', title: 'Sleep Entry' },
        { name: 'dream-detail', title: 'Dream' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  stars: {
    id: 'stars',
    name: 'MyStars',
    tagline: 'Private astrology and birth charts',
    icon: '\u{2728}',
    accentColor: '#8B5CF6',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'st_',
    navigation: {
      tabs: [
        { key: 'chart', label: 'Chart', icon: 'compass' },
        { key: 'transits', label: 'Transits', icon: 'sun' },
        { key: 'compatibility', label: 'Match', icon: 'users' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'birth-chart', title: 'Birth Chart' },
        { name: 'add-profile', title: 'Add Profile' },
        { name: 'transit-detail', title: 'Transit Detail' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  subs: {
    id: 'subs',
    name: 'MySubs',
    tagline: 'Subscription cost tracker',
    icon: '\u{1F4B3}',
    accentColor: '#10B981',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'sb_',
    navigation: {
      tabs: [
        { key: 'dashboard', label: 'Dashboard', icon: 'credit-card' },
        { key: 'subscriptions', label: 'Subs', icon: 'list' },
        { key: 'calendar', label: 'Calendar', icon: 'calendar' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'sub-detail', title: 'Subscription' },
        { name: 'add-sub', title: 'Add Subscription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  trails: {
    id: 'trails',
    name: 'MyTrails',
    tagline: 'Offline hiking and trail guide',
    icon: '\u{1F97E}',
    accentColor: '#65A30D',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'tr_',
    navigation: {
      tabs: [
        { key: 'map', label: 'Map', icon: 'map' },
        { key: 'trails', label: 'Trails', icon: 'navigation' },
        { key: 'recordings', label: 'Recordings', icon: 'activity' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'trail-detail', title: 'Trail' },
        { name: 'recording', title: 'Recording' },
        { name: 'elevation-profile', title: 'Elevation' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  travel: {
    id: 'travel',
    name: 'MyTravel',
    tagline: 'Plan trips, collect memories',
    icon: '\u2708\uFE0F',
    accentColor: '#0EA5E9',
    tier: 'premium',
    storageType: 'sqlite',
    tablePrefix: 'tv_',
    navigation: {
      tabs: [
        { key: 'index', label: 'Trips', icon: 'plane' },
        { key: 'destinations', label: 'Destinations', icon: 'map-pin' },
        { key: 'journal', label: 'Journal', icon: 'book-open' },
        { key: 'logistics', label: 'Logistics', icon: 'briefcase' },
      ],
      screens: [
        { name: 'settings', title: 'Settings' },
        { name: 'trip-detail', title: 'Trip' },
        { name: 'destination-detail', title: 'Destination' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
  voice: {
    id: 'voice',
    name: 'MyVoice',
    tagline: 'Private on-device dictation',
    icon: '\u{1F399}\u{FE0F}',
    accentColor: '#EF4444',
    tier: 'free',
    storageType: 'sqlite',
    tablePrefix: 'vc_',
    navigation: {
      tabs: [
        { key: 'dictate', label: 'Dictate', icon: 'mic' },
        { key: 'history', label: 'History', icon: 'clock' },
        { key: 'settings', label: 'Settings', icon: 'settings' },
      ],
      screens: [
        { name: 'transcription-detail', title: 'Transcription' },
      ],
    },
    requiresAuth: false,
    requiresNetwork: false,
    version: '0.1.0',
  },
};
