import type { MkThemeProfile } from '../types';

// Coordinated light/dark palettes. Both clients consume this registry.
export const LAUNCH_PRESETS: readonly MkThemeProfile[] = [
  {
    version: 1,
    id: 'tidepool',
    name: 'Tidepool',
    register: 'Calm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#126C78',
        background: '#F1F7F7',
        surface: '#FFFFFF',
        text: '#18363A',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#72C9D3',
        background: '#101E22',
        surface: '#182A2E',
        text: '#E2F1F2',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'alpine',
    name: 'Alpine',
    register: 'Calm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#326647',
        background: '#F3F7F2',
        surface: '#FFFFFF',
        text: '#243629',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#98CAA1',
        background: '#141D17',
        surface: '#1E2A22',
        text: '#E5EFE6',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'driftwood',
    name: 'Driftwood',
    register: 'Warm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#79583B',
        background: '#F7F4EE',
        surface: '#FFFDF9',
        text: '#382F27',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#D9B592',
        background: '#211B17',
        surface: '#2D251F',
        text: '#F2E9DE',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'dune',
    name: 'Dune',
    register: 'Warm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#8A601E',
        background: '#FAF6EC',
        surface: '#FFFEF9',
        text: '#3B3222',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#DCC08B',
        background: '#211E17',
        surface: '#2C281F',
        text: '#F1EBDE',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'terracotta',
    name: 'Terracotta',
    register: 'Warm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#A14332',
        background: '#FAF3EF',
        surface: '#FFFCFA',
        text: '#402921',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#EBA48B',
        background: '#241916',
        surface: '#32231E',
        text: '#F6E6DD',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'rosewater',
    name: 'Rosewater',
    register: 'Warm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#A13D64',
        background: '#FAF2F5',
        surface: '#FFFCFD',
        text: '#3F2630',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#EAA7C0',
        background: '#23171E',
        surface: '#31222B',
        text: '#F5E4EC',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'orchid',
    name: 'Orchid',
    register: 'Vibrant',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#854399',
        background: '#F8F3FA',
        surface: '#FEFCFF',
        text: '#392540',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#D8A4E8',
        background: '#201724',
        surface: '#2D2333',
        text: '#F0E3F4',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'iris',
    name: 'Iris',
    register: 'Calm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#5E52A2',
        background: '#F5F4FB',
        surface: '#FFFFFF',
        text: '#2E2A43',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#BAB0ED',
        background: '#1B1927',
        surface: '#282436',
        text: '#EAE6F5',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'cobalt',
    name: 'Cobalt',
    register: 'Vibrant',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#245CB5',
        background: '#F2F6FD',
        surface: '#FFFFFF',
        text: '#202E45',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#94BAFA',
        background: '#141D2C',
        surface: '#1E2A3C',
        text: '#E5EDFA',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'graphite',
    name: 'Graphite',
    register: 'Focused',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#4E5965',
        background: '#F5F6F7',
        surface: '#FFFFFF',
        text: '#23272D',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#B4C1CD',
        background: '#151719',
        surface: '#22262A',
        text: '#ECEFF2',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'matcha',
    name: 'Matcha',
    register: 'Calm',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#52712E',
        background: '#F4F7ED',
        surface: '#FDFFF8',
        text: '#2B3724',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#B7CE8C',
        background: '#1B2115',
        surface: '#283020',
        text: '#ECF2DF',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
  {
    version: 1,
    id: 'citrus',
    name: 'Citrus',
    register: 'Vibrant',
    shape: { radius: 'lg' },
    density: 'comfortable',
    headingWeight: '700',
    light: {
      primary: {
        accent: '#926300',
        background: '#FCF8EC',
        surface: '#FFFEF7',
        text: '#3E321B',
        danger: '#AC3936',
        warning: '#805B0C',
        info: '#315EAA',
        success: '#24704D',
      },
    },
    dark: {
      primary: {
        accent: '#EAC669',
        background: '#232013',
        surface: '#302B1C',
        text: '#F7EFD8',
        danger: '#EDA5A0',
        warning: '#E6C17D',
        info: '#A7C8F2',
        success: '#93D5B3',
      },
    },
  },
];
