import type { DatabaseAdapter } from '@mylife/db';
import {
  createAudienceRule,
  createCommunityAudienceRule,
  type AudienceRule,
  type ChannelMessageAttachment,
  type Hlc,
  type StoredCommunity,
} from '@mylife/sync';
import {
  aggregateCommunityFiles,
  type AggregatedFile,
} from './community-files';
import {
  countUnreadChannelMessages,
  isChannelPostEvent,
  listChannelMessageEvents,
  listChannelMessages,
  listChannelPostCards,
  listChannelReactions,
  type MessageReactionGroup,
} from './community-core';
import {
  createCommunitySafetyIndex,
  isChannelMuted,
  isCommunityMuted,
  type CommunitySafetyIndex,
} from './community-safety';
import { type VerifiedPublicEntry } from './public-directory-client';
import { LINK_PREVIEW_MIME_TYPE } from './link-preview';
import { parseCanvasPostBody } from './canvas-core';

export type FeedControlKey =
  | 'friends'
  | 'communities'
  | 'messages'
  | 'posts'
  | 'files'
  | 'unread'
  | 'public';

export type FeedItemKind = 'post' | 'canvas' | 'reply' | 'mention' | 'unread' | 'file' | 'public';

export interface FeedControls {
  friends: boolean;
  communities: boolean;
  messages: boolean;
  posts: boolean;
  files: boolean;
  unread: boolean;
  public: boolean;
}

export const DEFAULT_FEED_CONTROLS: FeedControls = {
  friends: true,
  communities: true,
  messages: true,
  posts: true,
  files: true,
  unread: true,
  public: false,
};

// The base feed source controls, public EXCLUDED. Kept as a named export for
// back-compat; prefer getVisibleFeedControls(), which adds 'public' only when a
// real public source is available at render time (plan section 6).
export const VISIBLE_FEED_CONTROLS: FeedControlKey[] = [
  'friends',
  'communities',
  'messages',
  'posts',
  'files',
  'unread',
];

// Compute the visible feed source controls. 'public' appears ONLY when a real
// public source is configured and responded with at least one verified entry
// (publicSourcesAvailable). This is computed gating, never a constant flip.
export function getVisibleFeedControls(
  publicSourcesAvailable: boolean,
): FeedControlKey[] {
  return publicSourcesAvailable
    ? [...VISIBLE_FEED_CONTROLS, 'public']
    : [...VISIBLE_FEED_CONTROLS];
}

export const FEED_CONTROL_LABELS: Record<FeedControlKey, string> = {
  friends: 'Friends',
  communities: 'Communities',
  messages: 'Messages',
  posts: 'Posts',
  files: 'Files',
  unread: 'Unread',
  public: 'Public',
};

/** mk_settings key persisting the feed source toggles across launches (composition Phase 0). */
export const FEED_CONTROLS_SETTING_KEY = 'feed_controls';

/** Serialize the source toggles for mk_settings. */
export function serializeFeedControls(controls: FeedControls): string {
  return JSON.stringify(controls);
}

/**
 * Parse persisted source toggles, fail-safe to the defaults: malformed JSON, a
 * non-object payload, or a wrong-typed value never break the feed. Unknown keys
 * are dropped; missing keys keep their default, so the control set can grow
 * without a migration.
 */
export function parseFeedControls(raw: string | null): FeedControls {
  const out = { ...DEFAULT_FEED_CONTROLS };
  if (!raw) return out;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return out;
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return out;
  for (const key of Object.keys(out) as FeedControlKey[]) {
    const value = (parsed as Record<string, unknown>)[key];
    if (typeof value === 'boolean') out[key] = value;
  }
  return out;
}

export interface FeedItem {
  id: string;
  kind: FeedItemKind;
  communityId: string;
  communityName: string;
  channelId: string;
  channelName: string;
  authorDeviceId: string;
  title: string;
  body: string;
  reason: string;
  quickActionLabel: string;
  audienceRule: AudienceRule;
  sortAt: Hlc;
  rankScore: number;
  postId?: string;
  replyCount?: number;
  unreadCount?: number;
  file?: AggregatedFile;
  public?: VerifiedPublicEntry;
  // Plan 32 T0.1 enrichment (post-kind items only). These DECORATE the card; they
  // are never ranking inputs (NC-5). Every value derives from a verified local row
  // (NC-1): `media` is the post root's first image attachment, `reactions` is the
  // Plan 30 read model keyed on the root event id (react events are excluded from
  // replyCount by Plan 30 T0.3, so the count stays trustworthy).
  media?: { blobHash: string; mimeType: string } | null;
  reactions?: MessageReactionGroup[];
  // Plan 32 T5.1 enrichment (post-kind items only). A reference to the post
  // root's first link-preview attachment (mimeType
  // application/x-meerkat-link-preview+json), or null. Like `media`, only the
  // blob hash + mime cross the boundary; the url/title/image live inside the
  // hash-verified blob and are parsed LAZILY by the render layer
  // (LinkPreviewCard). The receiver NEVER fetches the url (NC-2); the card is
  // sender-generated bytes that rode the verified attachment pipeline.
  linkPreview?: { blobHash: string; mimeType: string } | null;
}

export interface FeedEvaluation {
  controls: FeedControls;
  items: FeedItem[];
  publicSourcesAvailable: boolean;
  excludedSources: string[];
}

export interface PublicFeedSource {
  /** A directory URL has been configured. */
  configured: boolean;
  /** ISO timestamp of the last real directory response, or null when unreachable. */
  respondedAt: string | null;
  /** Signature + content-id verified directory entries pulled from a responding host. */
  entries: VerifiedPublicEntry[];
}

export interface EvaluateFeedInput {
  db: DatabaseAdapter;
  communities: readonly StoredCommunity[];
  selfDeviceId: string;
  controls?: Partial<FeedControls>;
  now?: Date;
  limit?: number;
  publicSource?: PublicFeedSource;
}

const KIND_RANK: Record<FeedItemKind, number> = {
  mention: 600,
  reply: 500,
  unread: 400,
  post: 300,
  canvas: 300,
  file: 200,
  public: 100,
};

// Respect the caller's `public` control ONLY when a real source is available;
// otherwise it stays off (no source means the control is hidden, plan section 6).
function normalizeFeedControls(
  controls: Partial<FeedControls> | undefined,
  publicSourcesAvailable: boolean,
): FeedControls {
  const merged = { ...DEFAULT_FEED_CONTROLS, ...controls };
  return { ...merged, public: publicSourcesAvailable ? merged.public : false };
}

// Build a public feed item from a verified directory entry. Every number carried
// here came from a verified entry (announcing_hosts is the directory's real count,
// event_count is the verified snapshot count). Nothing is fabricated.
function buildPublicFeedItem(entry: VerifiedPublicEntry): FeedItem {
  const hostLabel = entry.announcing_hosts === 1 ? 'host' : 'hosts';
  return {
    id: `public:${entry.publication_id}`,
    kind: 'public',
    communityId: '',
    communityName: entry.title,
    channelId: '',
    channelName: '',
    authorDeviceId: entry.owner_device_id,
    title: entry.title,
    body: entry.description,
    reason: `Public ${entry.kind} served by ${entry.announcing_hosts} ${hostLabel}.`,
    quickActionLabel: 'Open public',
    audienceRule: createAudienceRule({ type: 'public' }),
    sortAt: { wall: entry.latest_wall, counter: 0 },
    rankScore: rankScore('public'),
    public: entry,
  };
}

function compareHlc(a: Hlc, b: Hlc): number {
  if (a.wall !== b.wall) return a.wall < b.wall ? -1 : 1;
  return a.counter - b.counter;
}

function compareHlcDesc(a: Hlc, b: Hlc): number {
  return -compareHlc(a, b);
}

function channelMuted(
  db: DatabaseAdapter,
  communityId: string,
  channelId: string,
): boolean {
  return isChannelMuted(db, communityId, channelId);
}

function eventHiddenBySafety(safety: CommunitySafetyIndex, event: { id: string; authorDeviceId: string; postId?: string }): boolean {
  if (safety.blockedPersonIds.has(event.authorDeviceId)) return true;
  if (safety.hiddenMessageIds.has(event.id)) return true;
  if (event.postId && safety.hiddenPostIds.has(event.postId)) return true;
  return false;
}

function rankScore(kind: FeedItemKind, unreadCount = 0, replyCount = 0): number {
  return KIND_RANK[kind] + Math.min(unreadCount, 20) + Math.min(replyCount, 20) / 100;
}

// Plan 32 T0.1: the first IMAGE attachment on a signed event, or null. Only the
// blob hash + mime cross the boundary; the bytes are fetched lazily from the local
// blob store by the render layer. A non-image attachment (a PDF, a link-preview
// blob) is never surfaced as inline media.
function firstImageMedia(
  attachments: readonly ChannelMessageAttachment[] | undefined,
): { blobHash: string; mimeType: string } | null {
  const image = (attachments ?? []).find((attachment) =>
    attachment.mimeType.toLowerCase().startsWith('image/'),
  );
  return image ? { blobHash: image.blobHash, mimeType: image.mimeType } : null;
}

// Plan 32 T5.1: the first LINK-PREVIEW attachment on a signed event, or null.
// Parallel to firstImageMedia: only the blob hash + mime cross the boundary; the
// preview JSON (url / title / description / downscaled image) is parsed lazily
// from the local hash-verified blob by the render layer, exactly like media
// loads its bytes at render. A receiver NEVER fetches the url (NC-2). A post with
// no link-preview attachment yields null (no card, no crash).
function firstLinkPreview(
  attachments: readonly ChannelMessageAttachment[] | undefined,
): { blobHash: string; mimeType: string } | null {
  const preview = (attachments ?? []).find(
    (attachment) => attachment.mimeType === LINK_PREVIEW_MIME_TYPE,
  );
  return preview ? { blobHash: preview.blobHash, mimeType: preview.mimeType } : null;
}

function sortedFeedItems(items: FeedItem[]): FeedItem[] {
  return [...items].sort((a, b) => {
    if (a.rankScore !== b.rankScore) return b.rankScore - a.rankScore;
    const byTime = compareHlcDesc(a.sortAt, b.sortAt);
    if (byTime !== 0) return byTime;
    return a.id < b.id ? -1 : a.id === b.id ? 0 : 1;
  });
}

export function evaluateLocalFeed(input: EvaluateFeedInput): FeedEvaluation {
  const publicSource = input.publicSource;
  // TC-5: a configured source that responded with ZERO verified entries keeps
  // this false and the Public control hidden (responded-but-empty is the Discover
  // Empty state, never a visible-but-empty Public control).
  const publicSourcesAvailable =
    !!publicSource?.configured
    && publicSource.respondedAt !== null
    && publicSource.entries.length > 0;
  const controls = normalizeFeedControls(input.controls, publicSourcesAvailable);
  const items: FeedItem[] = [];

  // Public feed items come ONLY from verified entries a responding host served.
  if (controls.public && publicSource) {
    for (const entry of publicSource.entries) {
      if (!entry.verified) continue;
      items.push(buildPublicFeedItem(entry));
    }
  }
  const hasPublicItems = items.length > 0;

  const excludedSources = [
    'Friend-only posts are waiting on the friends graph.',
    'Direct messages and group DMs are not feed sources yet.',
  ];
  if (!hasPublicItems) {
    excludedSources.push(
      'Public hosted sources are hidden because no public source is available.',
    );
  }

  if (!controls.communities) {
    return {
      controls,
      items: sortedFeedItems(items).slice(0, input.limit ?? 50),
      publicSourcesAvailable,
      excludedSources,
    };
  }

  for (const community of input.communities) {
    if (isCommunityMuted(input.db, community.communityId)) continue;
    const safety = createCommunitySafetyIndex(input.db, community.communityId);
    const audienceRule = createCommunityAudienceRule(community.communityId);
    const visibleMessagesByChannel = new Map<string, ReturnType<typeof listChannelMessages>>();
    for (const channel of community.descriptor.channels) {
      if (channelMuted(input.db, community.communityId, channel.id)) continue;

      const channelEvents = listChannelMessageEvents(input.db, community.communityId, channel.id);
      const channelMessages = listChannelMessages(
        input.db,
        community.communityId,
        channel.id,
        channelEvents,
      );
      visibleMessagesByChannel.set(channel.id, channelMessages);
      if (controls.messages) {
        for (const event of channelMessages) {
          if (!event.mentions?.includes(input.selfDeviceId)) continue;
          if (event.authorDeviceId === input.selfDeviceId) continue;
          if (eventHiddenBySafety(safety, event)) continue;
          items.push({
            id: `mention:${event.id}`,
            kind: 'mention',
            communityId: community.communityId,
            communityName: community.descriptor.name,
            channelId: channel.id,
            channelName: channel.name,
            authorDeviceId: event.authorDeviceId,
            title: 'Mention',
            body: event.body,
            reason: `You were mentioned in #${channel.name}.`,
            quickActionLabel: isChannelPostEvent(event) ? 'Open thread' : 'Open channel',
            audienceRule,
            sortAt: event.hlc,
            rankScore: rankScore('mention'),
            postId: isChannelPostEvent(event) ? event.postId : undefined,
          });
        }
      }

      if (controls.messages && controls.unread) {
        const unreadCount = countUnreadChannelMessages(
          input.db,
          community.communityId,
          channel.id,
          channelMessages,
        );
        if (unreadCount > 0 && channelMessages.length > 0) {
          const latest = [...channelMessages].reverse().find((event) => !eventHiddenBySafety(safety, event));
          if (!latest) continue;
          items.push({
            id: `unread:${community.communityId}:${channel.id}`,
            kind: 'unread',
            communityId: community.communityId,
            communityName: community.descriptor.name,
            channelId: channel.id,
            channelName: channel.name,
            authorDeviceId: latest.authorDeviceId,
            title: `${unreadCount} unread in #${channel.name}`,
            body: latest.body,
            reason: 'This channel has unread local activity.',
            quickActionLabel: 'Open channel',
            audienceRule,
            sortAt: latest.hlc,
            rankScore: rankScore('unread', unreadCount),
            unreadCount,
          });
        }
      }

      if (controls.posts) {
        // Plan 30 read model, computed ONCE per channel and keyed by the reacted-to
        // event id. Reaction events never appear as feed items and never inflate
        // replyCount / lastActivity (Plan 30 T0.3); this only decorates the card.
        const channelReactions = listChannelReactions(
          input.db,
          community.communityId,
          channel.id,
          input.selfDeviceId,
          channelEvents,
          safety,
        );
        for (const post of listChannelPostCards(
          input.db,
          community.communityId,
          channel.id,
          channelMessages,
        )) {
          if (eventHiddenBySafety(safety, post.root)) continue;
          const replyToOwnPost =
            post.root.authorDeviceId === input.selfDeviceId
            && post.replyCount > 0
            && post.lastAuthorDeviceId !== input.selfDeviceId;
          // 4.5: a canvas post's root body is the mkcanvaspost token; it feeds
          // the 'canvas' feed kind so the card renders the canvas framing, not
          // the raw token. Replies to your canvas post still rank as replies.
          const isCanvasPost = parseCanvasPostBody(post.root.body) !== null;
          const kind: FeedItemKind = replyToOwnPost ? 'reply' : isCanvasPost ? 'canvas' : 'post';
          items.push({
            id: `${kind}:${post.postId}`,
            kind,
            communityId: community.communityId,
            communityName: community.descriptor.name,
            channelId: channel.id,
            channelName: channel.name,
            authorDeviceId: replyToOwnPost ? post.lastAuthorDeviceId : post.root.authorDeviceId,
            title: isCanvasPost ? (post.title ?? 'Canvas post') : (post.title ?? 'Post'),
            body: isCanvasPost ? 'A freeform canvas post. Open the thread to see it.' : post.root.body,
            reason: replyToOwnPost
              ? 'Someone replied to your post.'
              : `A community post from #${channel.name}.`,
            quickActionLabel: 'Open thread',
            audienceRule,
            sortAt: post.lastActivity,
            rankScore: rankScore(kind, 0, post.replyCount),
            postId: post.postId,
            replyCount: post.replyCount,
            media: firstImageMedia(post.root.attachments),
            linkPreview: firstLinkPreview(post.root.attachments),
            reactions: channelReactions.get(post.root.id) ?? [],
          });
        }
      }
    }

    if (controls.files) {
      const files = aggregateCommunityFiles(
        input.db,
        community.communityId,
        community.descriptor.channels,
        visibleMessagesByChannel,
      );
      for (const file of files) {
        if (channelMuted(input.db, community.communityId, file.channelId)) continue;
        if (safety.blockedPersonIds.has(file.authorDeviceId)) continue;
        if (safety.hiddenFileIds.has(file.id)) continue;
        if (safety.hiddenMessageIds.has(file.messageId)) continue;
        items.push({
          id: `file:${file.id}`,
          kind: 'file',
          communityId: community.communityId,
          communityName: community.descriptor.name,
          channelId: file.channelId,
          channelName: file.channelName,
          authorDeviceId: file.authorDeviceId,
          title: file.name,
          body: file.mimeType,
          reason: `A file was shared in #${file.channelName}.`,
          quickActionLabel: 'Open files',
          audienceRule: createCommunityAudienceRule(community.communityId),
          sortAt: { wall: file.hlcWall, counter: file.hlcCounter },
          rankScore: rankScore('file'),
          file,
        });
      }
    }
  }

  return {
    controls,
    items: sortedFeedItems(items).slice(0, input.limit ?? 50),
    publicSourcesAvailable,
    excludedSources,
  };
}
