/**
 * Built-in packing template catalog.
 *
 * Each template is a list of common-sense items keyed by category. Consumed by
 * `createListFromTemplate` to seed a new packing list with reasonable defaults.
 */

import type { PackingTemplateKey } from '../models/schemas';

export interface PackingTemplateItem {
  label: string;
  category: string;
}

export const PACKING_TEMPLATES: Record<PackingTemplateKey, PackingTemplateItem[]> = {
  weekend: [
    { label: 'Shirts (3)', category: 'clothing' },
    { label: 'Pants / shorts (2)', category: 'clothing' },
    { label: 'Underwear (3)', category: 'clothing' },
    { label: 'Socks (3 pairs)', category: 'clothing' },
    { label: 'Pajamas', category: 'clothing' },
    { label: 'Light jacket', category: 'clothing' },
    { label: 'Toothbrush + toothpaste', category: 'toiletries' },
    { label: 'Deodorant', category: 'toiletries' },
    { label: 'Shampoo / conditioner', category: 'toiletries' },
    { label: 'Face wash', category: 'toiletries' },
    { label: 'Phone charger', category: 'electronics' },
    { label: 'Headphones', category: 'electronics' },
    { label: 'ID / driver license', category: 'documents' },
    { label: 'Wallet', category: 'documents' },
    { label: 'Reusable water bottle', category: 'gear' },
    { label: 'Book / kindle', category: 'misc' },
  ],
  beach: [
    { label: 'Swimsuit (2)', category: 'clothing' },
    { label: 'Beach coverup', category: 'clothing' },
    { label: 'Shorts (3)', category: 'clothing' },
    { label: 'T-shirts (4)', category: 'clothing' },
    { label: 'Flip flops', category: 'clothing' },
    { label: 'Sandals', category: 'clothing' },
    { label: 'Underwear (5)', category: 'clothing' },
    { label: 'Sunhat', category: 'clothing' },
    { label: 'Sunscreen SPF 50', category: 'toiletries' },
    { label: 'After-sun lotion', category: 'toiletries' },
    { label: 'Toothbrush + toothpaste', category: 'toiletries' },
    { label: 'Sunglasses', category: 'gear' },
    { label: 'Beach towel', category: 'gear' },
    { label: 'Dry bag', category: 'gear' },
    { label: 'Snorkel gear', category: 'gear' },
    { label: 'Waterproof phone case', category: 'electronics' },
    { label: 'Phone charger', category: 'electronics' },
    { label: 'Passport', category: 'documents' },
    { label: 'Insurance card', category: 'documents' },
    { label: 'Reef-safe bug spray', category: 'toiletries' },
  ],
  ski: [
    { label: 'Base layers top (2)', category: 'clothing' },
    { label: 'Base layers bottom (2)', category: 'clothing' },
    { label: 'Ski jacket', category: 'clothing' },
    { label: 'Ski pants', category: 'clothing' },
    { label: 'Fleece mid-layer', category: 'clothing' },
    { label: 'Ski socks (3 pairs)', category: 'clothing' },
    { label: 'Beanie', category: 'clothing' },
    { label: 'Neck gaiter / buff', category: 'clothing' },
    { label: 'Gloves / mittens', category: 'clothing' },
    { label: 'Apres-ski boots', category: 'clothing' },
    { label: 'Goggles', category: 'gear' },
    { label: 'Helmet', category: 'gear' },
    { label: 'Ski / snowboard', category: 'gear' },
    { label: 'Boots', category: 'gear' },
    { label: 'Hand warmers', category: 'gear' },
    { label: 'Sunscreen (face stick)', category: 'toiletries' },
    { label: 'Lip balm SPF', category: 'toiletries' },
    { label: 'Moisturizer', category: 'toiletries' },
    { label: 'Lift ticket / pass', category: 'documents' },
    { label: 'Phone charger', category: 'electronics' },
  ],
  business: [
    { label: 'Suit / blazer', category: 'clothing' },
    { label: 'Dress shirts (3)', category: 'clothing' },
    { label: 'Dress pants (2)', category: 'clothing' },
    { label: 'Tie / accessories', category: 'clothing' },
    { label: 'Dress shoes', category: 'clothing' },
    { label: 'Belt', category: 'clothing' },
    { label: 'Socks (5 pairs)', category: 'clothing' },
    { label: 'Underwear (5)', category: 'clothing' },
    { label: 'Pajamas', category: 'clothing' },
    { label: 'Laptop + charger', category: 'electronics' },
    { label: 'Phone charger', category: 'electronics' },
    { label: 'Noise-cancelling headphones', category: 'electronics' },
    { label: 'Portable battery', category: 'electronics' },
    { label: 'Business cards', category: 'documents' },
    { label: 'Passport / ID', category: 'documents' },
    { label: 'Corporate card', category: 'documents' },
    { label: 'Toothbrush + toothpaste', category: 'toiletries' },
    { label: 'Shaving kit', category: 'toiletries' },
    { label: 'Notebook + pen', category: 'misc' },
  ],
  backpacking: [
    { label: 'Backpack 50-70L', category: 'gear' },
    { label: 'Sleeping bag', category: 'gear' },
    { label: 'Sleeping pad', category: 'gear' },
    { label: 'Tent', category: 'gear' },
    { label: 'Headlamp + batteries', category: 'gear' },
    { label: 'Water filter', category: 'gear' },
    { label: 'Stove + fuel', category: 'gear' },
    { label: 'Mess kit', category: 'gear' },
    { label: 'Pocket knife', category: 'gear' },
    { label: 'First aid kit', category: 'gear' },
    { label: 'Hiking boots', category: 'clothing' },
    { label: 'Hiking socks (3 pairs)', category: 'clothing' },
    { label: 'Base layers', category: 'clothing' },
    { label: 'Rain jacket', category: 'clothing' },
    { label: 'Insulating layer', category: 'clothing' },
    { label: 'Quick-dry pants', category: 'clothing' },
    { label: 'Hat / buff', category: 'clothing' },
    { label: 'Biodegradable soap', category: 'toiletries' },
    { label: 'Toothbrush + paste', category: 'toiletries' },
    { label: 'Trail permit', category: 'documents' },
    { label: 'Map + compass', category: 'gear' },
    { label: 'Trail snacks', category: 'misc' },
  ],
};
