export {
  seedWorkoutExerciseLibrary,
  getWorkoutExercises,
  getWorkoutExerciseById,
  getWorkoutExerciseCount,
  getWorkoutCategoryCounts,
  createWorkout,
  updateWorkout,
  deleteWorkout,
  getWorkouts,
  getWorkoutById,
  createWorkoutSession,
  completeWorkoutSession,
  annotateWorkoutSession,
  getWorkoutSessions,
  deleteWorkoutSession,
  createWorkoutFormRecording,
  getWorkoutFormRecordings,
  deleteWorkoutFormRecording,
  getWorkoutDashboard,
  getWorkoutMetrics,
  // Set weight tracking
  recordSetWeight,
  getSetWeightsForSession,
  getSetWeightsForExercise,
  getPreviousPerformance,
  // 1RM history
  record1RM,
  get1RMHistory,
  getLatest1RM,
  // Body measurements
  createBodyMeasurement,
  getBodyMeasurements,
  deleteBodyMeasurement,
  // Workout plans
  createWorkoutPlan,
  getWorkoutPlans,
  getWorkoutPlanById,
  updateWorkoutPlan,
  deleteWorkoutPlan,
  // Plan subscriptions
  subscribeToPlan,
  unsubscribeFromPlan,
  getActivePlanSubscription,
  // Overload rules
  createOverloadRule,
  getOverloadRules,
  getOverloadRuleForExercise,
  updateOverloadRule,
  deleteOverloadRule,
  getExercisePerformanceHistory,
  // Generation history
  createGenerationEntry,
  markGenerationAccepted,
  getGenerationHistory,
  // GPS routes
  createGpsRoute,
  completeGpsRoute,
  getGpsRoutes,
  getGpsRouteById,
  deleteGpsRoute,
  // GPS points
  insertGpsPoints,
  getGpsPoints,
  // Plate inventories
  createPlateInventory,
  getPlateInventories,
  getPlateInventoryById,
  updatePlateInventory,
  deletePlateInventory,
  // Progress photos
  createProgressPhoto,
  getProgressPhotos,
  getProgressPhotoById,
  deleteProgressPhoto,
  getProgressPhotoCount,
  // Trainers
  createTrainer,
  getActiveTrainer,
  getTrainerById,
  deactivateTrainer,
  // Exercise videos
  createExerciseVideo,
  getExerciseVideos,
  getExerciseVideoById,
  getPrimaryVideo,
  setPrimaryVideo,
  updateVideoOrder,
  deleteExerciseVideo,
  getExerciseVideoCount,
  // legacy
  createWorkoutLog,
  getWorkoutLogs,
  deleteWorkoutLog,
  createWorkoutProgram,
  getWorkoutPrograms,
  setActiveWorkoutProgram,
  deleteWorkoutProgram,
} from './crud';
