/**
 * Plan 38 Phase 0 -- community organization descriptor fields.
 *
 * D.6 is the load-bearing requirement here: the channel tuple and the
 * top-level organization slot use CONDITIONAL canonical append, and a
 * descriptor signed under the PRE-Plan-38 serializer must keep verifying
 * byte-for-byte. The frozen fixture in fixtures/legacy-community-descriptor.json
 * was generated by the old serializer and is never regenerated.
 */

import { describe, it, expect } from 'vitest';
import type { DeviceIdentity } from '../types';
import {
  channelArchived,
  channelKind,
  communityCategories,
  communityDescriptorHash,
  communityLayout,
  createCommunity,
  forkCommunity,
  orderedChannels,
  reviseCommunity,
  verifyCommunityDescriptor,
  type CommunityChannel,
  type SignedCommunityDescriptor,
} from '../protocol/community';
import { generateDeviceIdentity } from '../identity/device-identity';
import legacyFixture from './fixtures/legacy-community-descriptor.json';

const legacyGenesis = legacyFixture.genesis as SignedCommunityDescriptor;
const legacyRevision2 = legacyFixture.revision2 as SignedCommunityDescriptor;
const legacyOwner = legacyFixture.ownerIdentity as DeviceIdentity;

const ORGANIZED_CHANNELS: CommunityChannel[] = [
  { id: 'films', name: 'Films', kind: 'library', categoryId: 'media', order: 1 },
  { id: 'general', name: 'General', topic: 'Anything goes', order: 0 },
  { id: 'attic', name: 'Attic', archived: true, order: 2 },
];

describe('D.6 legacy-fixture compatibility (old signatures keep verifying)', () => {
  it('verifies the frozen legacy genesis byte-for-byte', () => {
    expect(verifyCommunityDescriptor(legacyGenesis)).toBe(true);
  });

  it('verifies the frozen legacy revision chain against its predecessor', () => {
    expect(verifyCommunityDescriptor(legacyRevision2, legacyGenesis)).toBe(true);
  });

  it('reproduces the exact legacy canonical bytes: the new serializer hashes the genesis to the previousHash the OLD serializer recorded', () => {
    expect(communityDescriptorHash(legacyGenesis)).toBe(legacyRevision2.descriptor.previousHash);
  });

  it('revises the legacy community WITHOUT organization fields and stays on the legacy canonical form', () => {
    const revision3 = reviseCommunity(legacyOwner, legacyRevision2, { name: 'Legacy, renamed' }, '2026-07-05T01:00:00.000Z');
    expect(verifyCommunityDescriptor(revision3, legacyRevision2)).toBe(true);
    expect(revision3.descriptor.categories).toBeUndefined();
    expect(revision3.descriptor.layout).toBeUndefined();
  });

  it('upgrades the legacy community with organization fields in a signed revision that verifies', () => {
    const revision3 = reviseCommunity(
      legacyOwner,
      legacyRevision2,
      {
        channels: legacyRevision2.descriptor.channels.map((c, i) => ({ ...c, order: i, topic: `Topic ${i}` })),
        categories: [{ id: 'all', name: 'All', order: 0 }],
        layout: 'library_first',
      },
      '2026-07-05T01:00:00.000Z',
    );
    expect(verifyCommunityDescriptor(revision3, legacyRevision2)).toBe(true);
    expect(communityLayout(revision3.descriptor)).toBe('library_first');
  });
});

describe('conditional canonical append (explicit defaults are canonically absent)', () => {
  it('keeps a signature valid when default values are made explicit on a signed descriptor', () => {
    const explicit: SignedCommunityDescriptor = {
      signature: legacyGenesis.signature,
      descriptor: {
        ...legacyGenesis.descriptor,
        channels: legacyGenesis.descriptor.channels.map((c) => ({ ...c, kind: 'chat' as const, archived: false })),
        categories: [],
        layout: 'chat_first',
      },
    };
    expect(verifyCommunityDescriptor(explicit)).toBe(true);
  });

  it('breaks the signature when a channel kind is tampered to library', () => {
    const tampered: SignedCommunityDescriptor = {
      signature: legacyGenesis.signature,
      descriptor: {
        ...legacyGenesis.descriptor,
        channels: legacyGenesis.descriptor.channels.map((c, i) => (i === 0 ? { ...c, kind: 'library' as const } : c)),
      },
    };
    expect(verifyCommunityDescriptor(tampered)).toBe(false);
  });

  it('breaks the signature when categories or layout are tampered onto a signed descriptor', () => {
    const withCategories: SignedCommunityDescriptor = {
      signature: legacyGenesis.signature,
      descriptor: { ...legacyGenesis.descriptor, categories: [{ id: 'x', name: 'X', order: 0 }] },
    };
    const withLayout: SignedCommunityDescriptor = {
      signature: legacyGenesis.signature,
      descriptor: { ...legacyGenesis.descriptor, layout: 'library_first' },
    };
    expect(verifyCommunityDescriptor(withCategories)).toBe(false);
    expect(verifyCommunityDescriptor(withLayout)).toBe(false);
  });

  it('breaks the signature when a topic, order, or archived flag is tampered', () => {
    for (const patch of [{ topic: 'injected' }, { order: 5 }, { archived: true }] as const) {
      const tampered: SignedCommunityDescriptor = {
        signature: legacyGenesis.signature,
        descriptor: {
          ...legacyGenesis.descriptor,
          channels: legacyGenesis.descriptor.channels.map((c, i) => (i === 0 ? { ...c, ...patch } : c)),
        },
      };
      expect(verifyCommunityDescriptor(tampered)).toBe(false);
    }
  });

  it('rejects a descriptor whose categories is not an array (fail-closed structure check)', () => {
    const malformed: SignedCommunityDescriptor = {
      signature: legacyGenesis.signature,
      descriptor: { ...legacyGenesis.descriptor, categories: 'nope' as unknown as [] },
    };
    expect(verifyCommunityDescriptor(malformed)).toBe(false);
  });
});

describe('organized community round-trip', () => {
  const owner = generateDeviceIdentity('Organizer');
  const signed = createCommunity(owner, {
    name: 'Organized Space',
    channels: ORGANIZED_CHANNELS,
    categories: [
      { id: 'media', name: 'Media', order: 1 },
      { id: 'talk', name: 'Talk', order: 0 },
    ],
    layout: 'library_first',
  });

  it('creates, signs, and verifies a genesis carrying kind/category/order/topic/archived/layout', () => {
    expect(verifyCommunityDescriptor(signed)).toBe(true);
    expect(communityLayout(signed.descriptor)).toBe('library_first');
    expect(channelKind(signed.descriptor.channels[0]!)).toBe('library');
  });

  it('revises organization fields and the chain still verifies', () => {
    const revised = reviseCommunity(owner, signed, {
      layout: 'chat_first',
      categories: [{ id: 'media', name: 'Media Vault', order: 0 }],
    });
    expect(verifyCommunityDescriptor(revised, signed)).toBe(true);
    expect(communityLayout(revised.descriptor)).toBe('chat_first');
    expect(communityCategories(revised.descriptor)).toEqual([{ id: 'media', name: 'Media Vault', order: 0 }]);
  });

  it('forks keep the organization (exit right covers structure)', () => {
    const newOwner = generateDeviceIdentity('Forker');
    const fork = forkCommunity(newOwner, signed);
    expect(verifyCommunityDescriptor(fork)).toBe(true);
    expect(communityLayout(fork.descriptor)).toBe('library_first');
    expect(fork.descriptor.categories).toEqual(signed.descriptor.categories);
    expect(channelKind(fork.descriptor.channels[0]!)).toBe('library');
  });
});

describe('fail-safe readers', () => {
  it('channelKind: absent = chat, known values pass, unknown values report unknown (never chat-silently)', () => {
    expect(channelKind({ id: 'a', name: 'A' })).toBe('chat');
    expect(channelKind({ id: 'a', name: 'A', kind: 'library' })).toBe('library');
    expect(channelKind({ id: 'a', name: 'A', kind: 'newsroom' as unknown as 'chat' })).toBe('unknown');
  });

  it('channelArchived: only an explicit true archives', () => {
    expect(channelArchived({ id: 'a', name: 'A' })).toBe(false);
    expect(channelArchived({ id: 'a', name: 'A', archived: 'yes' as unknown as boolean })).toBe(false);
    expect(channelArchived({ id: 'a', name: 'A', archived: true })).toBe(true);
  });

  it('communityLayout: absent and unknown fail safe to chat_first', () => {
    expect(communityLayout(legacyGenesis.descriptor)).toBe('chat_first');
    expect(communityLayout({ ...legacyGenesis.descriptor, layout: 'grid' as unknown as 'chat_first' })).toBe('chat_first');
  });

  it('communityCategories: drops malformed entries and sorts by order then id', () => {
    const categories = communityCategories({
      ...legacyGenesis.descriptor,
      categories: [
        { id: 'b', name: 'B', order: 1 },
        { id: 'a', name: 'A', order: 1 },
        { id: 'bad', name: 'Bad', order: Number.NaN },
        { id: 'first', name: 'First', order: 0 },
        { id: 'no-name', order: 2 } as unknown as { id: string; name: string; order: number },
      ],
    });
    expect(categories.map((c) => c.id)).toEqual(['first', 'a', 'b']);
  });

  it('communityCategories: duplicate ids collapse to the first sorted occurrence (pre-fix owner tolerance)', () => {
    // Pre-fix mobile owner code could mint two categories with ONE id
    // (position-based suffix reuse after delete-then-add); such descriptors are
    // signed and replicate. The reader must yield one group per id or every
    // assigned channel renders twice.
    const categories = communityCategories({
      ...legacyGenesis.descriptor,
      categories: [
        { id: 'cat-b-2', name: 'B', order: 0 },
        { id: 'cat-b-2', name: 'B!', order: 1 },
        { id: 'other', name: 'Other', order: 2 },
      ],
    });
    expect(categories.map((c) => c.id)).toEqual(['cat-b-2', 'other']);
    expect(categories[0]!.name).toBe('B');
  });

  it('orderedChannels: sorts by explicit order (position fallback), stable ties, archived hidden by default', () => {
    const descriptor = { ...legacyGenesis.descriptor, channels: ORGANIZED_CHANNELS };
    expect(orderedChannels(descriptor).map((c) => c.id)).toEqual(['general', 'films']);
    expect(orderedChannels(descriptor, { includeArchived: true }).map((c) => c.id)).toEqual(['general', 'films', 'attic']);
    const unordered = {
      ...legacyGenesis.descriptor,
      channels: [
        { id: 'x', name: 'X' },
        { id: 'y', name: 'Y' },
        { id: 'front', name: 'Front', order: -1 },
      ],
    };
    expect(orderedChannels(unordered).map((c) => c.id)).toEqual(['front', 'x', 'y']);
  });
});
