import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { AlertAggregation, ReportConfig, ProcessInfo } from "../types.js";
import { formatBytes, formatPercent } from "../utils/format.js";
import { logger } from "../utils/logger.js";

export function generateReport(
  aggregation: AlertAggregation,
  config: ReportConfig,
): string {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  const timeStr = now.toTimeString().slice(0, 8);

  const maxSeverity = aggregation.alerts.some((a) => a.severity === "critical")
    ? "Critical"
    : "Warning";

  const { cpu, memory, disk } = aggregation.snapshot;

  // Build process tables
  const byCpu = [...aggregation.snapshot.topProcesses].sort(
    (a, b) => b.cpuPercent - a.cpuPercent,
  );
  const byMem = [...aggregation.snapshot.topProcesses].sort(
    (a, b) => b.memoryMB - a.memoryMB,
  );

  const report = `# System Monitor Alert Report

**Generated:** ${dateStr} ${timeStr}
**Alert window:** ${fmtTime(aggregation.windowStart)} — ${fmtTime(aggregation.windowEnd)}
**Severity:** ${maxSeverity}

## Trigger Summary

| Metric | Value | Threshold | Severity | Duration |
|--------|-------|-----------|----------|----------|
${aggregation.alerts.map((a) => `| ${a.metric.toUpperCase()} | ${formatPercent(a.value)} | ${formatPercent(a.threshold)} | ${a.severity} | ${a.sustainedSince ? Math.round((now.getTime() - new Date(a.sustainedSince).getTime()) / 1000) + "s" : "—"} |`).join("\n")}

## System State at Time of Alert

| Metric | Value |
|--------|-------|
| CPU (user/sys/idle) | ${formatPercent(cpu.userPercent)} / ${formatPercent(cpu.systemPercent)} / ${formatPercent(cpu.idlePercent)} |
| Load Average (1/5/15m) | ${cpu.loadAvg.map((l) => l.toFixed(2)).join(" / ")} |
| Memory Used | ${formatBytes(memory.usedBytes)} / ${formatBytes(memory.totalBytes)} (${formatPercent(memory.usedPercent)}) |
| Memory Pressure | ${memory.pressureLevel} |
| Wired Memory | ${formatBytes(memory.wiredBytes)} |
| Compressed Memory | ${formatBytes(memory.compressedBytes)} |
${disk.volumes.map((v) => `| Disk ${v.mountPoint} | ${v.usedGB.toFixed(0)} GB / ${v.totalGB.toFixed(0)} GB (${v.usedPercent}%) |`).join("\n")}

## Top Processes by CPU

| PID | Process | CPU% | Memory |
|-----|---------|------|--------|
${formatProcessTable(byCpu)}

## Top Processes by Memory

| PID | Process | Memory | CPU% |
|-----|---------|--------|------|
${formatProcessTableByMem(byMem)}

---
*Auto-generated by system-monitor daemon. Cooldown active for next 5 minutes.*
*History log: system-monitor/logs/history.jsonl*
`;

  // Write to file
  mkdirSync(config.outputDir, { recursive: true });
  const filePath = getUniqueFilename(config.outputDir, config.namingPrefix, dateStr);
  writeFileSync(filePath, report, "utf-8");
  logger.info(`Report written: ${filePath}`);

  return filePath;
}

function fmtTime(isoStr: string): string {
  const d = new Date(isoStr);
  return d.toTimeString().slice(0, 8);
}

function formatProcessTable(processes: ProcessInfo[]): string {
  return processes
    .slice(0, 20)
    .map((p) => `| ${p.pid} | ${p.command} | ${p.cpuPercent.toFixed(1)}% | ${formatMB(p.memoryMB)} |`)
    .join("\n");
}

function formatProcessTableByMem(processes: ProcessInfo[]): string {
  return processes
    .slice(0, 20)
    .map((p) => `| ${p.pid} | ${p.command} | ${formatMB(p.memoryMB)} | ${p.cpuPercent.toFixed(1)}% |`)
    .join("\n");
}

function formatMB(mb: number): string {
  if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`;
  return `${mb.toFixed(0)} MB`;
}

function getUniqueFilename(dir: string, prefix: string, dateStr: string): string {
  const base = join(dir, `${prefix}-${dateStr}.md`);
  if (!existsSync(base)) return base;

  for (let i = 2; i <= 100; i++) {
    const candidate = join(dir, `${prefix}-${dateStr}-${i}.md`);
    if (!existsSync(candidate)) return candidate;
  }

  return base; // fallback: overwrite
}
