import { describe, expect, it } from 'vitest';
import { buildStorageDiagnostics, type StorageDiagnosticsRows } from '../diagnostics';

const T0 = '2026-07-14T12:00:00.000Z';
const T1 = '2026-07-14T12:01:00.000Z';
const T2 = '2026-07-14T12:02:00.000Z';

function mixedRows(): StorageDiagnosticsRows {
  return {
    destinations: [
      {
        id: 'drive',
        kind: 'google_drive',
        label: 'Drive',
        account_hint: null,
        credential_ref: null,
        root_ref: null,
        state: 'ready',
        capability_json: '{}',
        created_at: T0,
        updated_at: T2,
      },
      {
        id: 'dropbox',
        kind: 'dropbox',
        label: 'Dropbox',
        account_hint: null,
        credential_ref: null,
        root_ref: null,
        state: 'revoked',
        capability_json: '{}',
        created_at: T1,
        updated_at: T2,
      },
      {
        id: 's3',
        kind: 's3',
        label: 'Archive',
        account_hint: null,
        credential_ref: null,
        root_ref: null,
        state: 'degraded',
        capability_json: '{}',
        created_at: T2,
        updated_at: T2,
      },
    ],
    policies: [
      {
        data_class: 'database',
        primary_destination_id: 'drive',
        mirror_destination_id: 's3',
        local_cache_bytes: 4096,
        retention_json: '{"keep":3}',
        updated_at: T2,
      },
      {
        data_class: 'attachment',
        primary_destination_id: 'missing-destination',
        mirror_destination_id: null,
        local_cache_bytes: 2048,
        retention_json: '{"keep":1}',
        updated_at: T1,
      },
    ],
    objects: [
      {
        object_id: 'a',
        destination_id: 'drive',
        data_class: 'attachment',
        ciphertext_hash: 'aa'.repeat(64),
        plaintext_hash_encrypted: null,
        encrypted_bytes: 10,
        remote_ref: 'drive://a',
        remote_version: '1',
        state: 'verified',
        last_verified_at: T1,
      },
      {
        object_id: 'b',
        destination_id: 'drive',
        data_class: 'attachment',
        ciphertext_hash: 'bb'.repeat(64),
        plaintext_hash_encrypted: null,
        encrypted_bytes: 20,
        remote_ref: 'drive://b',
        remote_version: '1',
        state: 'verifying',
        last_verified_at: null,
      },
      {
        object_id: 'c',
        destination_id: 'dropbox',
        data_class: 'library_object',
        ciphertext_hash: 'cc'.repeat(64),
        plaintext_hash_encrypted: null,
        encrypted_bytes: 30,
        remote_ref: 'dropbox://c',
        remote_version: '1',
        state: 'verified',
        last_verified_at: T0,
      },
      {
        object_id: 'd',
        destination_id: 's3',
        data_class: 'database',
        ciphertext_hash: 'dd'.repeat(64),
        plaintext_hash_encrypted: null,
        encrypted_bytes: 40,
        remote_ref: null,
        remote_version: null,
        state: 'error',
        last_verified_at: null,
      },
    ],
    jobs: [
      {
        id: 'job-running',
        kind: 'backup',
        destination_id: 'drive',
        state: 'running',
        cursor_json: null,
        total_objects: 3,
        completed_objects: 1,
        total_bytes: 300,
        completed_bytes: 100,
        attempts: 0,
        last_error_code: null,
        created_at: T0,
        updated_at: T2,
      },
      {
        id: 'job-paused',
        kind: 'mirror',
        destination_id: 's3',
        state: 'paused',
        cursor_json: null,
        total_objects: 2,
        completed_objects: 1,
        total_bytes: 200,
        completed_bytes: 50,
        attempts: 2,
        last_error_code: 'unreachable',
        created_at: T1,
        updated_at: T2,
      },
      {
        id: 'job-done',
        kind: 'verify',
        destination_id: 'dropbox',
        state: 'succeeded',
        cursor_json: null,
        total_objects: 1,
        completed_objects: 1,
        total_bytes: 30,
        completed_bytes: 30,
        attempts: 0,
        last_error_code: null,
        created_at: T0,
        updated_at: T1,
      },
    ],
    health: [
      {
        destination_id: 'drive',
        state: 'ok',
        used_bytes: 100,
        cap_bytes: 100,
        verified_read_write: 1,
        checked_at: T2,
        error_code: null,
      },
      {
        destination_id: 'dropbox',
        state: 'auth_required',
        used_bytes: null,
        cap_bytes: null,
        verified_read_write: 0,
        checked_at: T2,
        error_code: 'auth_required',
      },
      {
        destination_id: 's3',
        state: 'unreachable',
        used_bytes: 50,
        cap_bytes: 1000,
        verified_read_write: 0,
        checked_at: T2,
        error_code: 'offline',
      },
    ],
    backups: [
      {
        backup_id: 'backup-complete',
        destination_id: 'drive',
        manifest_ref: 'manifest-1',
        manifest_ciphertext_hash: '11'.repeat(64),
        schema_version: 41,
        object_count: 1,
        encrypted_bytes: 100,
        state: 'complete',
        completed_at: T1,
      },
      {
        backup_id: 'backup-writing',
        destination_id: 'drive',
        manifest_ref: 'manifest-2',
        manifest_ciphertext_hash: '22'.repeat(64),
        schema_version: 41,
        object_count: 2,
        encrypted_bytes: 200,
        state: 'verifying',
        completed_at: null,
      },
      {
        backup_id: 'backup-deleted',
        destination_id: 'dropbox',
        manifest_ref: 'manifest-3',
        manifest_ciphertext_hash: '33'.repeat(64),
        schema_version: 40,
        object_count: 1,
        encrypted_bytes: 50,
        state: 'deleted',
        completed_at: null,
      },
      {
        backup_id: 'backup-corrupt',
        destination_id: 's3',
        manifest_ref: 'manifest-4',
        manifest_ciphertext_hash: '44'.repeat(64),
        schema_version: 41,
        object_count: 3,
        encrypted_bytes: 300,
        state: 'corrupt',
        completed_at: null,
      },
    ],
  };
}

describe('buildStorageDiagnostics', () => {
  it('folds mixed persisted state without optimistic completion', () => {
    // Arrange
    const rows = mixedRows();

    // Act
    const diagnostics = buildStorageDiagnostics(rows);

    // Assert
    expect(diagnostics).toMatchInlineSnapshot(`
      {
        "activeJobs": [
          {
            "attempts": 2,
            "completedBytes": 50,
            "completedObjects": 1,
            "destinationId": "s3",
            "errorCode": "unreachable",
            "id": "job-paused",
            "kind": "mirror",
            "state": "paused",
            "totalBytes": 200,
            "totalObjects": 2,
            "updatedAt": "2026-07-14T12:02:00.000Z",
          },
          {
            "attempts": 0,
            "completedBytes": 100,
            "completedObjects": 1,
            "destinationId": "drive",
            "errorCode": null,
            "id": "job-running",
            "kind": "backup",
            "state": "running",
            "totalBytes": 300,
            "totalObjects": 3,
            "updatedAt": "2026-07-14T12:02:00.000Z",
          },
        ],
        "backups": [
          {
            "backupId": "backup-complete",
            "complete": true,
            "completedAt": "2026-07-14T12:01:00.000Z",
            "destinationId": "drive",
            "encryptedBytes": 100,
            "objectCount": 1,
            "schemaVersion": 41,
            "state": "complete",
          },
          {
            "backupId": "backup-writing",
            "complete": false,
            "completedAt": null,
            "destinationId": "drive",
            "encryptedBytes": 200,
            "objectCount": 2,
            "schemaVersion": 41,
            "state": "verifying",
          },
          {
            "backupId": "backup-deleted",
            "complete": false,
            "completedAt": null,
            "destinationId": "dropbox",
            "encryptedBytes": 50,
            "objectCount": 1,
            "schemaVersion": 40,
            "state": "deleted",
          },
          {
            "backupId": "backup-corrupt",
            "complete": false,
            "completedAt": null,
            "destinationId": "s3",
            "encryptedBytes": 300,
            "objectCount": 3,
            "schemaVersion": 41,
            "state": "corrupt",
          },
        ],
        "destinations": [
          {
            "activeJobs": [
              {
                "attempts": 0,
                "completedBytes": 100,
                "completedObjects": 1,
                "destinationId": "drive",
                "errorCode": null,
                "id": "job-running",
                "kind": "backup",
                "state": "running",
                "totalBytes": 300,
                "totalObjects": 3,
                "updatedAt": "2026-07-14T12:02:00.000Z",
              },
            ],
            "backups": [
              {
                "backupId": "backup-complete",
                "complete": true,
                "completedAt": "2026-07-14T12:01:00.000Z",
                "destinationId": "drive",
                "encryptedBytes": 100,
                "objectCount": 1,
                "schemaVersion": 41,
                "state": "complete",
              },
              {
                "backupId": "backup-writing",
                "complete": false,
                "completedAt": null,
                "destinationId": "drive",
                "encryptedBytes": 200,
                "objectCount": 2,
                "schemaVersion": 41,
                "state": "verifying",
              },
            ],
            "capBytes": 100,
            "healthCheckedAt": "2026-07-14T12:02:00.000Z",
            "healthErrorCode": null,
            "healthState": "ok",
            "id": "drive",
            "kind": "google_drive",
            "label": "Drive",
            "lastVerificationAt": "2026-07-14T12:01:00.000Z",
            "objectCounts": {
              "deleted": 0,
              "deleting": 0,
              "error": 0,
              "missing": 0,
              "queued": 0,
              "total": 2,
              "verified": 1,
              "verifying": 1,
              "writing": 0,
            },
            "runningJobs": [
              {
                "attempts": 0,
                "completedBytes": 100,
                "completedObjects": 1,
                "destinationId": "drive",
                "errorCode": null,
                "id": "job-running",
                "kind": "backup",
                "state": "running",
                "totalBytes": 300,
                "totalObjects": 3,
                "updatedAt": "2026-07-14T12:02:00.000Z",
              },
            ],
            "state": "ready",
            "usedBytes": 100,
            "verifiedReadWrite": true,
          },
          {
            "activeJobs": [],
            "backups": [
              {
                "backupId": "backup-deleted",
                "complete": false,
                "completedAt": null,
                "destinationId": "dropbox",
                "encryptedBytes": 50,
                "objectCount": 1,
                "schemaVersion": 40,
                "state": "deleted",
              },
            ],
            "capBytes": null,
            "healthCheckedAt": "2026-07-14T12:02:00.000Z",
            "healthErrorCode": "auth_required",
            "healthState": "auth_required",
            "id": "dropbox",
            "kind": "dropbox",
            "label": "Dropbox",
            "lastVerificationAt": "2026-07-14T12:00:00.000Z",
            "objectCounts": {
              "deleted": 0,
              "deleting": 0,
              "error": 0,
              "missing": 0,
              "queued": 0,
              "total": 1,
              "verified": 1,
              "verifying": 0,
              "writing": 0,
            },
            "runningJobs": [],
            "state": "revoked",
            "usedBytes": null,
            "verifiedReadWrite": false,
          },
          {
            "activeJobs": [
              {
                "attempts": 2,
                "completedBytes": 50,
                "completedObjects": 1,
                "destinationId": "s3",
                "errorCode": "unreachable",
                "id": "job-paused",
                "kind": "mirror",
                "state": "paused",
                "totalBytes": 200,
                "totalObjects": 2,
                "updatedAt": "2026-07-14T12:02:00.000Z",
              },
            ],
            "backups": [
              {
                "backupId": "backup-corrupt",
                "complete": false,
                "completedAt": null,
                "destinationId": "s3",
                "encryptedBytes": 300,
                "objectCount": 3,
                "schemaVersion": 41,
                "state": "corrupt",
              },
            ],
            "capBytes": 1000,
            "healthCheckedAt": "2026-07-14T12:02:00.000Z",
            "healthErrorCode": "offline",
            "healthState": "unreachable",
            "id": "s3",
            "kind": "s3",
            "label": "Archive",
            "lastVerificationAt": null,
            "objectCounts": {
              "deleted": 0,
              "deleting": 0,
              "error": 1,
              "missing": 0,
              "queued": 0,
              "total": 1,
              "verified": 0,
              "verifying": 0,
              "writing": 0,
            },
            "runningJobs": [],
            "state": "degraded",
            "usedBytes": 50,
            "verifiedReadWrite": false,
          },
        ],
        "issues": [
          {
            "backupIds": [],
            "count": 1,
            "destinationIds": [
              "dropbox",
            ],
            "kind": "auth_required",
          },
          {
            "backupIds": [],
            "count": 1,
            "destinationIds": [
              "drive",
            ],
            "kind": "quota",
          },
          {
            "backupIds": [],
            "count": 1,
            "destinationIds": [
              "s3",
            ],
            "kind": "degraded",
          },
          {
            "backupIds": [
              "drive:backup-writing",
              "s3:backup-corrupt",
            ],
            "count": 2,
            "destinationIds": [],
            "kind": "unverified-backup",
          },
        ],
        "policies": [
          {
            "dataClass": "attachment",
            "localCacheBytes": 2048,
            "mirror": null,
            "primary": {
              "availableForNewWrites": false,
              "id": "missing-destination",
              "label": null,
              "state": "missing",
            },
            "retentionJson": "{"keep":1}",
            "updatedAt": "2026-07-14T12:01:00.000Z",
          },
          {
            "dataClass": "database",
            "localCacheBytes": 4096,
            "mirror": {
              "availableForNewWrites": true,
              "id": "s3",
              "label": "Archive",
              "state": "degraded",
            },
            "primary": {
              "availableForNewWrites": true,
              "id": "drive",
              "label": "Drive",
              "state": "ready",
            },
            "retentionJson": "{"keep":3}",
            "updatedAt": "2026-07-14T12:02:00.000Z",
          },
        ],
        "runningJobs": [
          {
            "attempts": 0,
            "completedBytes": 100,
            "completedObjects": 1,
            "destinationId": "drive",
            "errorCode": null,
            "id": "job-running",
            "kind": "backup",
            "state": "running",
            "totalBytes": 300,
            "totalObjects": 3,
            "updatedAt": "2026-07-14T12:02:00.000Z",
          },
        ],
      }
    `);
  });

  it('derives current auth and quota issues from active job checkpoints', () => {
    // Arrange
    const rows: StorageDiagnosticsRows = {
      destinations: [
        {
          id: 'auth-destination',
          kind: 'google_drive',
          label: 'Auth destination',
          account_hint: null,
          credential_ref: null,
          root_ref: null,
          state: 'error',
          capability_json: '{}',
          created_at: T0,
          updated_at: T1,
        },
        {
          id: 'quota-destination',
          kind: 's3',
          label: 'Quota destination',
          account_hint: null,
          credential_ref: null,
          root_ref: null,
          state: 'ready',
          capability_json: '{}',
          created_at: T0,
          updated_at: T1,
        },
      ],
      policies: [],
      objects: [],
      jobs: [
        {
          id: 'auth-job',
          kind: 'backup',
          destination_id: 'auth-destination',
          state: 'paused',
          cursor_json: '{}',
          total_objects: 1,
          completed_objects: 0,
          total_bytes: 10,
          completed_bytes: 0,
          attempts: 0,
          last_error_code: 'auth_required',
          created_at: T0,
          updated_at: T1,
        },
        {
          id: 'quota-job',
          kind: 'mirror',
          destination_id: 'quota-destination',
          state: 'paused',
          cursor_json: '{}',
          total_objects: 1,
          completed_objects: 0,
          total_bytes: 10,
          completed_bytes: 0,
          attempts: 0,
          last_error_code: 'quota_exceeded',
          created_at: T0,
          updated_at: T1,
        },
      ],
      health: [],
      backups: [],
    };

    // Act
    const diagnostics = buildStorageDiagnostics(rows);

    // Assert
    expect(diagnostics.issues).toEqual([
      {
        kind: 'auth_required',
        count: 1,
        destinationIds: ['auth-destination'],
        backupIds: [],
      },
      {
        kind: 'quota',
        count: 1,
        destinationIds: ['quota-destination'],
        backupIds: [],
      },
    ]);
  });
});
