// ── Module Definition ────────────────────────────────────────────────
export { SHOP_MODULE } from './definition';

// ── Schema + Migrations ─────────────────────────────────────────────
export {
  BASE_TABLES,
  CREATE_SETTINGS,
  CREATE_WISHLISTS,
  CREATE_WISHLIST_ITEMS,
  CREATE_PHOTOS,
  CREATE_PURCHASES,
  CREATE_USAGE_LOG,
  CREATE_WARRANTIES,
  CREATE_SIZES,
  CREATE_PREFERENCES,
  CREATE_GIFT_PEOPLE,
  CREATE_GIFTS_GIVEN,
  CREATE_GIFT_BUDGETS,
  WISHLIST_TABLES,
  WISHLIST_INDEXES,
  PURCHASES_TABLES,
  PURCHASES_INDEXES,
  USAGE_LOG_TABLES,
  USAGE_LOG_INDEXES,
  WARRANTIES_TABLES,
  WARRANTIES_INDEXES,
  SIZES_TABLES,
  SIZES_INDEXES,
  PREFERENCES_TABLES,
  PREFERENCES_INDEXES,
  GIFTS_TABLES,
  GIFTS_INDEXES,
  ALTER_WISHLIST_ITEMS_GIFT_FOR_PERSON,
  CREATE_THIRTY_DAY_RULE,
  THIRTY_DAY_RULE_TABLES,
  THIRTY_DAY_RULE_INDEXES,
  CREATE_COMPARISONS,
  COMPARISONS_TABLES,
  COMPARISONS_INDEXES,
  CREATE_STORE_NOTES,
  STORE_NOTES_TABLES,
  STORE_NOTES_INDEXES,
  getMigrations,
} from './db';

// ── CRUD ────────────────────────────────────────────────────────────
export {
  createWishlist,
  getWishlistById,
  listWishlists,
  updateWishlist,
  deleteWishlist,
  generateShareToken,
  getWishlistByShareToken,
  createWishlistItem,
  getWishlistItemById,
  updateWishlistItem,
  deleteWishlistItem,
  listItemsByWishlist,
  listItemsByCategory,
  listItemsByPriority,
  listItemsByGiftForPerson,
  markAsPurchased,
  moveItemToList,
  searchItems,
  createPhoto,
  getPhotoById,
  deletePhoto,
  listPhotosByItem,
  createPurchase,
  getPurchaseById,
  updatePurchase,
  deletePurchase,
  listPurchases,
  markReturned,
  updateSatisfaction,
  getPendingSatisfactionReviews,
  logUse,
  getUsageCount,
  getUsageHistory,
  deleteUsageEntry,
  createWarranty,
  getWarrantyById,
  updateWarranty,
  deleteWarranty,
  listWarranties,
  listActiveWarranties,
  listExpiredWarranties,
  listExpiringSoon,
  fileClaim,
  getWarrantiesByPurchase,
  type ListWarrantiesOptions,
  createSize,
  getSizeById,
  updateSize,
  deleteSize,
  listSizes,
  listSizesByType,
  listSizesByBrand,
  searchSizesByBrand,
  type ListSizesOptions,
  createPreference,
  getPreferenceById,
  updatePreference,
  deletePreference,
  listPreferences,
  listPreferencesByCategory,
  getPreference,
  createGift,
  getGiftById,
  updateGift,
  deleteGift,
  listGifts,
  listGiftsByPerson,
  listGiftsByOccasion,
  getGiftHistory,
  getTotalSpentOnPerson,
  getUpcomingOccasions,
  type ListGiftsOptions,
  type UpcomingOccasion,
  createGiftPerson,
  getGiftPersonById,
  updateGiftPerson,
  deleteGiftPerson,
  listGiftPeople,
  setGiftBudget,
  getGiftBudget,
  getGiftBudgetById,
  listGiftBudgetsForPerson,
  deleteGiftBudget,
  addToWaitList,
  getWaitItemById,
  listWaitingItems,
  listAllWaitItems,
  markBought,
  markSkipped,
  deleteWaitItem,
  type ListWaitItemsOptions,
  createComparison,
  getComparisonById,
  updateComparison,
  deleteComparison,
  listComparisons,
  listComparisonsByCategory,
  listRecentComparisons,
  linkComparisonToPurchase,
  searchComparisonsByCategory,
  type ListComparisonsOptions,
  upsertStoreNote,
  getStoreNoteById,
  getStoreNoteByName,
  listStoreNotes,
  deleteStoreNote,
} from './db';

// ── Engines ─────────────────────────────────────────────────────────
export {
  calculateDueReviews,
  scheduleReviewReminder,
  type DueReview,
  type ReviewPeriod,
  type ReminderSchedule,
} from './engine/satisfaction-tracker';

export {
  calculateReturnDeadline,
  getExpiringReturns,
} from './engine/return-deadline';

export {
  calculateCostPerUse,
  getWorthItStatus,
  projectBreakEven,
  DEFAULT_WORTH_IT_THRESHOLD_CENTS,
  type WorthItStatus,
} from './engine/cost-per-use';

export {
  getUpcomingExpiries,
  shouldRemindForWarranty,
  getDaysUntilExpiry,
  getWarrantyStatus,
  getExpiringReturns as getExpiringReturnsMs,
  type WarrantyStatus,
} from './engine/warranty-reminders';

export {
  getMyShare,
  getRemainingBudget,
  getOverBudgetWarning,
  summarizePersonSpending,
  type OverBudgetWarning,
  type PersonSpendingSummary,
} from './engine/gift-budget';

export {
  getMonthlySummary,
  getCategoryBreakdown,
  getCostOfOwnership,
  getSaleRatio,
  getSixMonthTrend,
  type MonthlySummary,
  type CategoryBreakdownRow,
  type SaleRatio,
  type MonthTrendRow,
} from './engine/spending-summary';

export {
  getImpulseStats,
  getImpulseRegretRate,
  getTopImpulseCategories,
  type ImpulseStats,
  type ImpulseRegretRate,
  type TopImpulseCategory,
  type DateRange as ImpulseDateRange,
} from './engine/impulse-tracker';

export {
  getDaysWaiting,
  getDaysRemaining,
  isReadyForDecision,
  getConversionRate,
  getTotalSavedBySkipping,
  type ConversionRate,
} from './engine/thirty-day-rule';

export {
  generateReview,
  type GenerateReviewArgs,
  type YearReview,
  type CategoryBreakdownRow as YearReviewCategoryRow,
  type OccasionBreakdownRow,
  type GiftSummary,
  type WarrantyUtilization,
  type WishlistConversion,
  type ImpulseAudit,
  type MonthlyTrendRow,
} from './engine/year-in-review';

// ── Zod Schemas + Types ─────────────────────────────────────────────
export {
  PrioritySchema,
  CategorySchema,
  OccasionSchema,
  PhotoKindSchema,
  WishlistSchema,
  WishlistInputSchema,
  WishlistPatchSchema,
  WishlistItemSchema,
  WishlistItemInputSchema,
  WishlistItemPatchSchema,
  PhotoSchema,
  PhotoInputSchema,
  WishlistFilterSchema,
  WishlistItemFilterSchema,
  PaymentMethodSchema,
  SatisfactionRatingSchema,
  SatisfactionPeriodSchema,
  PurchaseSchema,
  PurchaseInputSchema,
  PurchasePatchSchema,
  PurchaseFilterSchema,
  UsageLogEntrySchema,
  UsageLogInputSchema,
  CoverageTypeSchema,
  WarrantySchema,
  WarrantyInputSchema,
  WarrantyUpdateSchema,
  ClaimInputSchema,
  SizeTypeSchema,
  SizeSchema,
  SizeInputSchema,
  SizeUpdateSchema,
  PreferenceCategorySchema,
  PreferenceSchema,
  PreferenceInputSchema,
  PreferenceUpdateSchema,
  GiftOccasionSchema,
  GiftSchema,
  GiftInputSchema,
  GiftUpdateSchema,
  GiftPersonSchema,
  GiftPersonInputSchema,
  GiftPersonUpdateSchema,
  GiftBudgetSchema,
  GiftBudgetInputSchema,
  ThirtyDayRuleDecisionSchema,
  ThirtyDayRuleItemSchema,
  ThirtyDayRuleInputSchema,
  ComparisonItemSchema,
  ComparisonSchema,
  ComparisonInputSchema,
  ComparisonUpdateSchema,
  StoreNoteSchema,
  StoreNoteInputSchema,
} from './models/schemas';

export type {
  UsageLogEntry,
  UsageLogInput,
  UsageLogInputParsed,
  CoverageType,
  Warranty,
  WarrantyInput,
  WarrantyInputParsed,
  WarrantyUpdate,
  ClaimInput,
  SizeType,
  Size,
  SizeInputParsed,
  SizeUpdate,
  PreferenceCategory,
  Preference,
  PreferenceInputParsed,
  PreferenceUpdate,
  GiftOccasion,
  Gift,
  GiftInput,
  GiftInputParsed,
  GiftUpdate,
  GiftPerson,
  GiftPersonInput,
  GiftPersonInputParsed,
  GiftPersonUpdate,
  GiftBudget,
  GiftBudgetInput,
  GiftBudgetInputParsed,
  ThirtyDayRuleDecision,
  ThirtyDayRuleItem,
  ThirtyDayRuleInput,
  ThirtyDayRuleInputParsed,
  ComparisonItem,
  Comparison,
  ComparisonInput,
  ComparisonInputParsed,
  ComparisonUpdate,
  StoreNote,
  StoreNoteInput,
  StoreNoteInputParsed,
} from './models/schemas';

// ── Public Types ────────────────────────────────────────────────────
export * from './types';

// ── Cross-Module Integrations ──────────────────────────────────────
export {
  mapShopCategoryToBudgetCategory,
  buildBudgetTransactionSuggestion,
  summarizeMonthlyShopSpendingForBudget,
  type BudgetTransactionSuggestion,
} from './integrations/budget-link';
export {
  getGiftIdeasForPerson,
  getGiftHistoryForPerson,
  getSizeMemoryForPerson,
  surfaceInFriendProfile,
} from './integrations/friends-link';
export {
  isClothingPurchase,
  buildClosetItemSuggestionFromPurchase,
  getSharedClothingSizes,
  getClosetSuggestionsFromPurchases,
  type ClosetItemSuggestion,
} from './integrations/closet-link';
export {
  isGamingPurchase,
  buildGameLibrarySuggestion,
  getGameWishlistItems,
  type GameLibrarySuggestion,
} from './integrations/gaming-link';
export {
  isMusicPurchase,
  buildMusicCollectionSuggestion,
  getMusicWishlistItems,
  type MusicCollectionSuggestion,
} from './integrations/music-link';
export {
  isAutoPartsPurchase,
  buildMaintenanceLogEntry,
  getCarRelatedWarranties,
  type MaintenanceLogEntry,
} from './integrations/car-link';
export {
  isPetSupplyPurchase,
  buildPetSupplyEntry,
  getVetRecommendedPurchases,
  type PetSupplyEntry,
} from './integrations/pets-link';
