/**
 * MyShop public type surface. V1 Zod-inferred types for wishlist are the source
 * of truth; remaining placeholder interfaces will be replaced by real shapes
 * as later phases ship (purchases, warranties, sizes, preferences, gifts,
 * comparisons).
 */

export type {
  Priority,
  Category,
  Occasion,
  PhotoKind,
  Wishlist,
  WishlistInput,
  WishlistPatch,
  WishlistItem,
  WishlistItemInput,
  WishlistItemPatch,
  WishlistFilter,
  WishlistItemFilter,
  Photo,
  PhotoInput,
  PaymentMethod,
  SatisfactionRating,
  SatisfactionPeriod,
  Purchase,
  PurchaseInput,
  PurchasePatch,
  PurchaseFilter,
  SizeType,
  Size,
  SizeInput,
  SizeUpdate,
  PreferenceCategory,
  Preference,
  PreferenceInput,
  PreferenceUpdate,
  GiftOccasion,
  Gift,
  GiftInput,
  GiftUpdate,
  GiftPerson,
  GiftPersonInput,
  GiftPersonUpdate,
  GiftBudget,
  GiftBudgetInput,
  ThirtyDayRuleDecision,
  ThirtyDayRuleItem,
  ThirtyDayRuleInput,
  ComparisonItem,
  Comparison,
  ComparisonInput,
  ComparisonUpdate,
  StoreNote,
  StoreNoteInput,
} from './models/schemas';
