// ── Module Definition ────────────────────────────────────────────────
export { MARKET_MODULE } from './definition';

// ── UI barrel ────────────────────────────────────────────────────────
// `./ui/index.ts` exports only web-safe tokens, typography, and pure
// logic helpers; full RN component surface lives in `./ui/index.native.ts`
// which Metro picks on mobile.
export * from './ui';

// ── Types & Schemas ──────────────────────────────────────────────────
export {
  ListingStatusSchema,
  PricingTypeSchema,
  ConditionSchema,
  ListingTypeSchema,
  FulfillmentTypeSchema,
  CategorySchema,
  ListingSchema,
  CreateListingInputSchema,
  ListingPhotoSchema,
  ConversationSchema,
  MessageContentTypeSchema,
  MessageEncryptionAlgorithmSchema,
  MessageSchema,
  CreateMessageInputSchema,
  ConversationRequestStatusSchema,
  DevicePlatformSchema,
  SecureKeyAlgorithmSchema,
  PostQuantumKemSchema,
  SecureDeviceSchema,
  SignedPreKeySchema,
  OneTimePreKeyKindSchema,
  OneTimePreKeySchema,
  RecipientPreKeyBundleSchema,
  PublishDeviceBundleInputSchema,
  ConversationRequestSchema,
  CreateConversationRequestInputSchema,
  EncryptedEnvelopeTypeSchema,
  SecureEnvelopeSchema,
  CreateSecureEnvelopeInputSchema,
  WatchlistItemSchema,
  ReviewSchema,
  SellerStatsSchema,
  SavedSearchSchema,
  ReportReasonSchema,
  ReportSchema,
  BlockSchema,
  // B+C feature schemas
  OfferStatusSchema,
  OfferSchema,
  CreateOfferInputSchema,
  PriceHistorySchema,
  PaymentStatusSchema,
  FeePayerSchema,
  PaymentSchema,
  EscrowStatusSchema,
  EscrowSchema,
  DisputeReasonSchema,
  DisputeStatusSchema,
  DisputeResolutionTypeSchema,
  DisputeSchema,
  DisputeEvidenceTypeSchema,
  DisputeEvidenceSchema,
  CreateDisputeInputSchema,
  ShippingCarrierSchema,
  ShipmentStatusSchema,
  ShipmentSchema,
  ShipmentEventSchema,
  AddTrackingInputSchema,
  ServicePortfolioItemSchema,
  ServiceAreaSchema,
  ServiceAvailabilitySchema,
  VerificationLevelSchema,
  SellerVerificationSchema,
  // Stripe Connect schemas
  ConnectAccountStatusSchema,
  ConnectAccountSchema,
  CreatePaymentIntentInputSchema,
  RefundInputSchema,
  StripeWebhookEventTypeSchema,
} from './types';
export type {
  ListingStatus,
  PricingType,
  Condition,
  ListingType,
  FulfillmentType,
  Category,
  Listing,
  CreateListingInput,
  ListingPhoto,
  Conversation,
  MessageContentType,
  MessageEncryptionAlgorithm,
  Message,
  CreateMessageInput,
  ConversationRequestStatus,
  DevicePlatform,
  SecureKeyAlgorithm,
  PostQuantumKem,
  SecureDevice,
  SignedPreKey,
  OneTimePreKeyKind,
  OneTimePreKey,
  RecipientPreKeyBundle,
  PublishDeviceBundleInput,
  ConversationRequest,
  CreateConversationRequestInput,
  EncryptedEnvelopeType,
  SecureEnvelope,
  CreateSecureEnvelopeInput,
  WatchlistItem,
  Review,
  SellerStats,
  SavedSearch,
  ReportReason,
  Report,
  Block,
  // B+C feature types
  OfferStatus,
  Offer,
  CreateOfferInput,
  PriceHistory,
  PaymentStatus,
  FeePayer,
  Payment,
  EscrowStatus,
  Escrow,
  DisputeReason,
  DisputeStatus,
  DisputeResolutionType,
  Dispute,
  DisputeEvidenceType,
  DisputeEvidence,
  CreateDisputeInput,
  ShippingCarrier,
  ShipmentStatus,
  Shipment,
  ShipmentEvent,
  AddTrackingInput,
  ServicePortfolioItem,
  ServiceArea,
  ServiceAvailability,
  VerificationLevel,
  SellerVerification,
  // Stripe Connect types
  ConnectAccountStatus,
  ConnectAccount,
  CreatePaymentIntentInput,
  RefundInput,
  StripeWebhookEventType,
} from './types';

// ── SQLite Cache Schema ──────────────────────────────────────────────
export { CACHE_TABLES, CACHE_INDEXES, V3_CACHE_TABLES, V3_CACHE_INDEXES } from './db/schema';

// ── Local CRUD (SQLite cache) ────────────────────────────────────────
export type { DatabaseAdapter } from './db/crud';
export {
  getCachedCategories,
  upsertCachedCategory,
  getCachedListings,
  getCachedListingById,
  upsertCachedListing,
  deleteCachedListing,
  getCachedWatchlist,
  upsertCachedWatchlistItem,
  deleteCachedWatchlistItem,
  getCachedConversations,
  getCachedMessages,
  upsertCachedConversation,
  upsertCachedMessage,
} from './db/crud';

// ── Cloud Client (Supabase) ──────────────────────────────────────────
export {
  cloudGetCategories,
  cloudGetListings,
  cloudGetListingById,
  cloudCreateListing,
  cloudUpdateListingStatus,
  cloudSearchListings,
  cloudGetListingsWithinRadius,
  cloudGetConversations,
  cloudStartConversation,
  cloudCreateConversationRequest,
  cloudRespondToConversationRequest,
  cloudRegisterSecureDevice,
  cloudGetRecipientPreKeyBundles,
  cloudGetMessages,
  cloudSendMessage,
  cloudGetSecureEnvelopes,
  cloudSendSecureEnvelope,
  cloudGetWatchlist,
  cloudToggleWatch,
  cloudGetSellerReviews,
  cloudGetSellerStats,
  cloudGetSavedSearches,
  // B+C cloud functions
  cloudMakeOffer,
  cloudRespondToOffer,
  cloudGetOffersForListing,
  cloudGetMyOffers,
  cloudUpdateListingPrice,
  cloudGetPriceHistory,
  cloudReportListing,
  cloudReportUser,
  cloudBlockUser,
  cloudUnblockUser,
  cloudGetSellerVerification,
  cloudAddTracking,
  cloudGetShipment,
  cloudGetServicePortfolio,
  cloudGetServiceAvailability,
} from './cloud/client';

// ── Encryption Helpers ───────────────────────────────────────────────
export {
  encryptMarketMessageBody,
  decryptMarketMessageBody,
} from './encryption';

// ── Business Logic Engines ──────────────────────────────────────────
export {
  calculateVerificationLevel,
  resolveEffectiveLevel,
  canCreateListing,
  LISTING_LIMITS,
} from './verification';
export type { VerificationStats } from './verification';

export {
  isValidTransition,
  isWithinFilingWindow,
  isSellerResponseExpired,
  calculateRefundAmount,
  calculateResponseDeadline,
  FILING_WINDOW_DAYS,
  SELLER_RESPONSE_DAYS,
  AUTO_RELEASE_DAYS,
} from './disputes';

export {
  isValidTrackingNumber,
  buildTrackingUrl,
  normalizeCarrierStatus,
  calculateProcessingFee,
  CARRIER_NAMES,
  CARRIER_TRACKING_URLS,
} from './shipping';

// ── Payments (Stripe Connect) ───────────────────────────────────────
export type {
  StripeClient,
  StripeWebhookEvent,
  StripeConnectConfig,
  OnboardingResult,
  AccountStatus,
  PaymentIntentResult,
  RefundResult,
  InitiatePaymentParams,
  InitiatePaymentResult,
  EscrowState,
  ProcessRefundParams,
  DisputeRefundParams,
  FeeEstimate,
  WebhookAction,
} from './payments';
export {
  DEFAULT_CONFIG,
  createConnectedAccount,
  getAccountStatus,
  createDashboardLink,
  createPaymentIntent,
  capturePaymentIntent,
  cancelPaymentIntent,
  createRefund,
  getPaymentIntentStatus,
  calculateFeeSplit,
  initiatePayment,
  captureAndHold,
  evaluateEscrowState,
  calculateAutoReleaseDate,
  processRefund,
  handleDisputeRefund,
  estimateFees,
  mapStripeStatusToPaymentStatus,
  verifyWebhookEvent,
  processWebhookEvent,
  handleWebhook,
  HANDLED_EVENTS,
} from './payments';

// ── Crypto (Signal-style E2E) ───────────────────────────────────────
export {
  generateKeyPair,
  performDH,
  hkdfDeriveKey,
  encryptMessage,
  decryptMessage,
  computeSafetyNumber,
  generateRegistrationId,
} from './crypto';
