export {
  ALL_TABLES,
  CREATE_INDEXES,
  V2_TABLES,
  V2_INDEXES,
  V3_TABLES,
  V3_INDEXES,
  V4_TABLES,
  V4_INDEXES,
  V5_TABLES,
  V5_INDEXES,
  V6_TABLES,
  V6_INDEXES,
  V7_TABLES,
  V7_INDEXES,
  V8_TABLES,
  V8_INDEXES,
  V9_TABLES,
  V9_INDEXES,
  V10_TABLES,
  V10_INDEXES,
  V11_TABLES,
  V11_INDEXES,
  V12_TABLES,
  V12_INDEXES,
} from './schema';
export {
  createTrail,
  getTrail,
  getTrails,
  updateTrail,
  deleteTrail,
  createRecording,
  getRecording,
  getRecordings,
  getRecordingsByTrail,
  deleteRecording,
  createWaypoint,
  getWaypointsByRecording,
  getTrailStats,
  // Offline regions
  createOfflineRegion,
  getOfflineRegion,
  getOfflineRegions,
  getReadyRegions,
  getStaleRegions,
  updateRegionProgress,
  markRegionReady,
  markRegionError,
  resetRegionToPending,
  deleteOfflineRegion,
  // Alert settings
  getAlertSettings,
  createAlertSettings,
  updateAlertSettings,
  // Deviation events
  createDeviationEvent,
  getDeviationsByRecording,
  acknowledgeDeviation,
  // Weather cache
  cacheWeather,
  getCachedWeather,
  cleanExpiredCache,
  // Segments
  createSegment,
  getSegmentsByTrail,
  createSegmentEffort,
  getEffortsBySegment,
  getPersonalBest,
  recalculatePersonalBest,
  // Packing
  createPackingTemplate,
  getPackingTemplates,
  getPackingTemplate,
  createPackingItem,
  getPackingItems,
  checkItem,
  uncheckItem,
  uncheckAll,
  deletePackingTemplate,
  deletePackingItem,
  getPackingProgress,
  // Trips
  createTrip,
  getTrip,
  getTrips,
  deleteTrip,
  createTripDay,
  getTripDays,
  deleteTripDay,
  createTripActivity,
  getTripActivities,
  deleteTripActivity,
  reorderActivities,
  // Trail database
  upsertDatabaseEntry,
  getDatabaseEntries,
  searchDatabaseTrails,
  getDatabaseEntry,
  saveDatabaseTrailToMyTrails,
  // Planned routes
  createPlannedRoute,
  getPlannedRoute,
  getPlannedRoutes,
  deletePlannedRoute,
  createRouteWaypoint,
  getRouteWaypoints,
  deleteRouteWaypoint,
  // Reviews
  createReview,
  getReviewsByTrail,
  updateReview,
  deleteReview,
  getAverageRating,
  getReviewCount,
  getRecentConditions,
  getRatingDistribution,
  getSetting,
  setSetting,
} from './crud';
