export { PETS_MODULE } from './definition';

export type {
  PetSpecies,
  PetSex,
  VetVisitType,
  MedicationFrequency,
  MedicationLogStatus,
  ExpenseCategory,
  ReminderStatus,
  WeightTrendDirection,
  ExerciseActivityType,
  GroomingType,
  TrainingLocation,
  PetTimelineKind,
  BreedAlertSeverity,
  PortionUnit,
  MealLabel,
  TransitionStatus,
  FeedingStatus,
  Pet,
  VetVisit,
  Vaccination,
  Medication,
  MedicationLog,
  WeightEntry,
  FeedingSchedule,
  FeedingLog,
  DietaryInfo,
  FoodTransition,
  PetExpense,
  EmergencyContact,
  ExerciseLog,
  GroomingRecord,
  TrainingLog,
  PetPhoto,
  CreatePetInput,
  UpdatePetInput,
  CreateVetVisitInput,
  CreateVaccinationInput,
  CreateMedicationInput,
  RecordMedicationLogInput,
  CreateWeightEntryInput,
  CreateFeedingScheduleInput,
  UpdateFeedingScheduleInput,
  CreateFeedingLogInput,
  UpsertDietaryInfoInput,
  CreateFoodTransitionInput,
  CreatePetExpenseInput,
  CreateEmergencyContactInput,
  CreateExerciseLogInput,
  CreateGroomingRecordInput,
  CreateTrainingLogInput,
  CreatePetPhotoInput,
  PetListFilter,
  VaccinationReminder,
  GroomingReminder,
  WeightTrend,
  PetDashboard,
  PetTimelineItem,
  BreedHealthAlert,
  PetSitterCard,
  PetExportBundle,
  CoverageType,
  ClaimStatus,
  CommandStatus,
  MilestoneTag,
  ExerciseGoal,
  InsurancePolicy,
  InsuranceClaim,
  ExpenseBudget,
  GroomingInterval,
  TrainingCommand,
  DismissedAlert,
  SetExerciseGoalInput,
  CreateInsurancePolicyInput,
  CreateInsuranceClaimInput,
  SetExpenseBudgetInput,
  SetGroomingIntervalInput,
  AddTrainingCommandInput,
} from './types';

export {
  PetSpeciesSchema,
  PetSexSchema,
  VetVisitTypeSchema,
  MedicationFrequencySchema,
  MedicationLogStatusSchema,
  ExpenseCategorySchema,
  ReminderStatusSchema,
  WeightTrendDirectionSchema,
  ExerciseActivityTypeSchema,
  GroomingTypeSchema,
  TrainingLocationSchema,
  PetTimelineKindSchema,
  BreedAlertSeveritySchema,
  PetSchema,
  VetVisitSchema,
  VaccinationSchema,
  MedicationSchema,
  MedicationLogSchema,
  WeightEntrySchema,
  FeedingScheduleSchema,
  FeedingLogSchema,
  DietaryInfoSchema,
  FoodTransitionSchema,
  PortionUnitSchema,
  MealLabelSchema,
  TransitionStatusSchema,
  FeedingStatusSchema,
  CreateFeedingLogInputSchema,
  UpdateFeedingScheduleInputSchema,
  UpsertDietaryInfoInputSchema,
  CreateFoodTransitionInputSchema,
  CoverageTypeSchema,
  ClaimStatusSchema,
  CommandStatusSchema,
  MilestoneTagSchema,
  ExerciseGoalSchema,
  InsurancePolicySchema,
  InsuranceClaimSchema,
  ExpenseBudgetSchema,
  GroomingIntervalSchema,
  TrainingCommandSchema,
  DismissedAlertSchema,
  SetExerciseGoalInputSchema,
  CreateInsurancePolicyInputSchema,
  CreateInsuranceClaimInputSchema,
  SetExpenseBudgetInputSchema,
  SetGroomingIntervalInputSchema,
  AddTrainingCommandInputSchema,
  PetExpenseSchema,
  EmergencyContactSchema,
  ExerciseLogSchema,
  GroomingRecordSchema,
  TrainingLogSchema,
  PetPhotoSchema,
  CreatePetInputSchema,
  UpdatePetInputSchema,
  CreateVetVisitInputSchema,
  CreateVaccinationInputSchema,
  CreateMedicationInputSchema,
  RecordMedicationLogInputSchema,
  CreateWeightEntryInputSchema,
  CreateFeedingScheduleInputSchema,
  CreatePetExpenseInputSchema,
  CreateEmergencyContactInputSchema,
  CreateExerciseLogInputSchema,
  CreateGroomingRecordInputSchema,
  CreateTrainingLogInputSchema,
  CreatePetPhotoInputSchema,
  PetListFilterSchema,
  VaccinationReminderSchema,
  GroomingReminderSchema,
  WeightTrendSchema,
  PetDashboardSchema,
  PetTimelineItemSchema,
  BreedHealthAlertSchema,
  CORE_VACCINE_SCHEDULES,
} from './types';

export {
  createPet,
  getPetById,
  listPets,
  updatePet,
  deletePet,
  createVetVisit,
  listVetVisitsForPet,
  createVaccination,
  listVaccinationsForPet,
  listDueVaccinationReminders,
  createMedication,
  getMedicationById,
  listMedicationsForPet,
  listDueMedications,
  recordMedicationLog,
  listMedicationLogs,
  createWeightEntry,
  listWeightEntriesForPet,
  createFeedingSchedule,
  listFeedingSchedulesForPet,
  updateFeedingSchedule,
  deleteFeedingSchedule,
  createFeedingLog,
  listFeedingLogsForDate,
  deleteFeedingLog,
  upsertDietaryInfo,
  getDietaryInfo,
  createFoodTransition,
  getActiveTransition,
  completeTransition,
  setExerciseGoal,
  getExerciseGoal,
  deleteExerciseGoal,
  updateEmergencyContact,
  deleteEmergencyContact,
  getPrimaryEmergencyContact,
  createInsurancePolicy,
  getInsurancePoliciesForPet,
  deleteInsurancePolicy,
  createInsuranceClaim,
  listClaimsForPolicy,
  updateClaimStatus,
  setExpenseBudget,
  getExpenseBudgets,
  setGroomingInterval,
  getGroomingIntervals,
  updateGroomingRecord,
  deleteGroomingRecord,
  createGroomingRecordWithInterval,
  addTrainingCommand,
  updateCommandStatus,
  listTrainingCommands,
  dismissAlert,
  getDismissedAlerts,
  undismissAlert,
  updatePetPhoto,
  deletePetPhoto,
  getPhotosByMilestone,
  createPetExpense,
  listExpensesForPet,
  createEmergencyContact,
  listEmergencyContacts,
  createExerciseLog,
  listExerciseLogsForPet,
  createGroomingRecord,
  listGroomingRecordsForPet,
  listDueGroomingReminders,
  createTrainingLog,
  listTrainingLogsForPet,
  createPetPhoto,
  listPetPhotosForPet,
  getPetHealthTimeline,
  buildPetSitterCard,
  exportPetData,
  getPetDashboard,
} from './db';

export {
  getReminderStatus,
  computeNextMedicationDueAt,
  collectVaccinationReminders,
  collectMedicationReminders,
} from './engine/reminders';
export type { MedicationReminder } from './engine/reminders';

export {
  calculatePetAgeYears,
  calculateWeightTrend,
  calculateOwnershipCost,
  calculateAverageMonthlyCost,
} from './engine/weight';
export { getBreedHealthAlerts } from './engine/alerts';

export {
  getDailyFeedingStatus,
  calculateTransitionRatio,
} from './engine/feeding';
export type {
  ScheduleStatus,
  DailyFeedingResult,
  TransitionRatio,
} from './engine/feeding';

export {
  calculateExerciseProgress,
  calculateExerciseStreak,
  getExerciseSummary,
  getBreedExerciseRecommendation,
} from './engine/exercise';
export type { ExerciseProgress, ExerciseStreak, ExerciseSummary } from './engine/exercise';

export {
  calculateAnnualInsuranceCost,
  calculateClaimReimbursementRate,
  getInsuranceSummary,
} from './engine/insurance';
export type { InsuranceSummary } from './engine/insurance';

export {
  calculateMonthlySpending,
  calculateBudgetProgress,
  getCostOfOwnershipBreakdown,
  getExpenseTrend,
} from './engine/expenses';
export type { MonthlySpending, BudgetProgress, CostBreakdownItem, MonthlyTrendItem } from './engine/expenses';

export {
  calculateNextGroomingDate,
  getGroomingOverview,
  getOverdueGroomingTasks,
} from './engine/grooming-intervals';
export type { GroomingOverviewItem } from './engine/grooming-intervals';

export {
  calculateCommandProgress,
  getTrainingSummary,
  calculateTrainingStreak,
} from './engine/training';
export type { CommandProgress, TrainingSummary, TrainingStreak } from './engine/training';

export {
  getPhotoTimeline,
  getMilestonePhotos,
  getPhotoStats,
} from './engine/photos';
export type { PhotoTimelineGroup, PhotoStats } from './engine/photos';

export {
  TRAINING_CURRICULUM,
  getLessonPlan,
  getNextLesson,
  getLevelProgress,
} from './engine/lessons';
export type { Lesson, LessonLevel } from './engine/lessons';

export {
  generateLostPetPoster,
  generateFoundPetPoster,
} from './engine/poster';
export type { PosterInput } from './engine/poster';
export {
  formatPetSitterCard,
  serializePetExportBundle,
  serializePetExportCsvSections,
} from './engine/export';

// ── Cross-Module Integrations ──
export { PET_FRIENDLY_TAG, isPetFriendly } from './integrations/dining';
export {
  importPetSupplyFromPurchase,
  getPendingPetImports,
  type PetSupplyEntry,
} from './integrations/shop-import';
