CREATE TABLE restaurants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  legal_name text NOT NULL,
  display_name text NOT NULL,
  stripe_account_id text,
  charges_enabled boolean DEFAULT false,
  payouts_enabled boolean DEFAULT false,
  country char(2) DEFAULT 'US',
  timezone text DEFAULT 'America/New_York',
  cuisines text[] DEFAULT '{}',
  price_tier integer DEFAULT 2,
  hours jsonb DEFAULT '{}',
  policies jsonb DEFAULT '{}',
  branding jsonb DEFAULT '{}',
  capabilities jsonb DEFAULT '{}',
  status text DEFAULT 'onboarding' CHECK (status IN ('onboarding', 'active', 'paused', 'terminated')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
