/**
 * Strategy Risk Manager
 *
 * Pre-trade risk controls for automated strategy deployments.
 * Every order signal generated by a deployed strategy passes through
 * these checks before reaching the broker adapter or paper engine.
 *
 * Kill switches automatically halt strategy execution when drawdown
 * or daily loss limits are breached.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RiskConfig {
  /** Max position size as % of equity for a single symbol (default 10%) */
  maxPositionSizePercent: number
  /** Max total exposure as % of equity across all positions (default 100%) */
  maxTotalExposurePercent: number
  /** Max daily loss as % of equity — triggers kill switch (default 3%) */
  maxDailyLossPercent: number
  /** Max drawdown from peak equity — triggers kill switch (default 10%) */
  maxDrawdownPercent: number
}

export const DEFAULT_RISK_CONFIG: RiskConfig = {
  maxPositionSizePercent: 10,
  maxTotalExposurePercent: 100,
  maxDailyLossPercent: 3,
  maxDrawdownPercent: 10,
}

export interface PortfolioSnapshot {
  equity: number
  positions: PositionSnapshot[]
}

export interface PositionSnapshot {
  symbol: string
  quantity: number
  currentPrice: number
  marketValue: number
}

export interface OrderToCheck {
  symbol: string
  side: 'buy' | 'sell'
  quantity: number
  price: number
}

export interface RiskCheckResult {
  allowed: boolean
  reason?: string
}

export interface KillSwitchStatus {
  triggered: boolean
  reason?: string
  triggeredAt?: number
}

// ---------------------------------------------------------------------------
// Daily P&L Tracker — per-deployment
// ---------------------------------------------------------------------------

export interface DailyPnLEntry {
  date: string // YYYY-MM-DD
  startEquity: number
  currentEquity: number
  peakEquity: number
  realizedPnL: number
  trades: number
}

export class DailyPnLTracker {
  private entries = new Map<string, DailyPnLEntry>()
  private allTimePeakEquity: number

  constructor(initialEquity: number) {
    this.allTimePeakEquity = initialEquity
  }

  /**
   * Get or create the daily entry for today.
   */
  getToday(equity: number): DailyPnLEntry {
    const date = new Date().toISOString().slice(0, 10)
    let entry = this.entries.get(date)
    if (!entry) {
      entry = {
        date,
        startEquity: equity,
        currentEquity: equity,
        peakEquity: equity,
        realizedPnL: 0,
        trades: 0,
      }
      this.entries.set(date, entry)
    }
    return entry
  }

  /**
   * Record a completed trade and update daily P&L.
   */
  recordTrade(pnl: number, currentEquity: number): void {
    const entry = this.getToday(currentEquity)
    entry.realizedPnL += pnl
    entry.currentEquity = currentEquity
    entry.trades += 1

    if (currentEquity > entry.peakEquity) {
      entry.peakEquity = currentEquity
    }
    if (currentEquity > this.allTimePeakEquity) {
      this.allTimePeakEquity = currentEquity
    }
  }

  /**
   * Update current equity without recording a trade.
   */
  updateEquity(currentEquity: number): void {
    const entry = this.getToday(currentEquity)
    entry.currentEquity = currentEquity
    if (currentEquity > entry.peakEquity) {
      entry.peakEquity = currentEquity
    }
    if (currentEquity > this.allTimePeakEquity) {
      this.allTimePeakEquity = currentEquity
    }
  }

  /**
   * Get the daily P&L as a percentage of start-of-day equity.
   */
  getDailyPnLPercent(currentEquity: number): number {
    const entry = this.getToday(currentEquity)
    if (entry.startEquity === 0) return 0
    return ((currentEquity - entry.startEquity) / entry.startEquity) * 100
  }

  /**
   * Get the drawdown from the all-time peak equity.
   */
  getDrawdownPercent(currentEquity: number): number {
    if (this.allTimePeakEquity === 0) return 0
    return ((this.allTimePeakEquity - currentEquity) / this.allTimePeakEquity) * 100
  }

  getAllTimePeak(): number {
    return this.allTimePeakEquity
  }

  getEntries(): DailyPnLEntry[] {
    return Array.from(this.entries.values())
  }
}

// ---------------------------------------------------------------------------
// Risk Manager
// ---------------------------------------------------------------------------

export class RiskManager {
  private config: RiskConfig
  private pnlTracker: DailyPnLTracker
  private killSwitch: KillSwitchStatus = { triggered: false }

  constructor(config?: Partial<RiskConfig>, initialEquity: number = 100_000) {
    this.config = { ...DEFAULT_RISK_CONFIG, ...config }
    this.pnlTracker = new DailyPnLTracker(initialEquity)
  }

  // ── Pre-trade checks ─────────────────────────────────────

  /**
   * Run all pre-trade risk checks for a proposed order.
   * Returns { allowed: true } if the order can proceed, or
   * { allowed: false, reason: string } if blocked.
   */
  checkOrder(
    order: OrderToCheck,
    portfolio: PortfolioSnapshot,
    config?: Partial<RiskConfig>,
  ): RiskCheckResult {
    const cfg = config ? { ...this.config, ...config } : this.config

    // Kill switch already triggered — block everything
    if (this.killSwitch.triggered) {
      return {
        allowed: false,
        reason: `Kill switch active: ${this.killSwitch.reason}`,
      }
    }

    // 1. Max position size per symbol
    const orderValue = order.quantity * order.price
    const maxPositionValue = (cfg.maxPositionSizePercent / 100) * portfolio.equity

    if (order.side === 'buy') {
      const existingPosition = portfolio.positions.find((p) => p.symbol === order.symbol)
      const existingValue = existingPosition?.marketValue ?? 0
      const totalPositionValue = existingValue + orderValue

      if (totalPositionValue > maxPositionValue) {
        return {
          allowed: false,
          reason: `Position in ${order.symbol} would reach $${totalPositionValue.toFixed(2)} (${((totalPositionValue / portfolio.equity) * 100).toFixed(1)}% of equity), exceeding max ${cfg.maxPositionSizePercent}%`,
        }
      }
    }

    // 2. Max total exposure
    const currentExposure = portfolio.positions.reduce((sum, p) => sum + Math.abs(p.marketValue), 0)
    const newExposure = order.side === 'buy'
      ? currentExposure + orderValue
      : currentExposure // sells reduce exposure
    const maxExposure = (cfg.maxTotalExposurePercent / 100) * portfolio.equity

    if (newExposure > maxExposure) {
      return {
        allowed: false,
        reason: `Total exposure would reach $${newExposure.toFixed(2)} (${((newExposure / portfolio.equity) * 100).toFixed(1)}% of equity), exceeding max ${cfg.maxTotalExposurePercent}%`,
      }
    }

    // 3. Max daily loss — kill switch check
    const dailyLossResult = this.checkDailyLoss(portfolio.equity, cfg)
    if (!dailyLossResult.allowed) {
      return dailyLossResult
    }

    // 4. Max drawdown — kill switch check
    const drawdownResult = this.checkDrawdown(portfolio.equity, cfg)
    if (!drawdownResult.allowed) {
      return drawdownResult
    }

    return { allowed: true }
  }

  // ── Kill switch checks ────────────────────────────────────

  /**
   * Check if the daily loss limit has been breached.
   * If breached, triggers the kill switch.
   */
  checkDailyLoss(currentEquity: number, config?: Partial<RiskConfig>): RiskCheckResult {
    const cfg = config ? { ...this.config, ...config } : this.config
    const dailyLossPercent = this.pnlTracker.getDailyPnLPercent(currentEquity)

    // dailyLossPercent is negative when losing money
    if (dailyLossPercent <= -cfg.maxDailyLossPercent) {
      const reason = `Daily loss limit breached: ${dailyLossPercent.toFixed(2)}% (limit: -${cfg.maxDailyLossPercent}%)`
      this.triggerKillSwitch(reason)
      return { allowed: false, reason }
    }

    return { allowed: true }
  }

  /**
   * Check if the max drawdown from peak has been breached.
   * If breached, triggers the kill switch.
   */
  checkDrawdown(currentEquity: number, config?: Partial<RiskConfig>): RiskCheckResult {
    const cfg = config ? { ...this.config, ...config } : this.config
    const drawdownPercent = this.pnlTracker.getDrawdownPercent(currentEquity)

    if (drawdownPercent >= cfg.maxDrawdownPercent) {
      const reason = `Max drawdown breached: ${drawdownPercent.toFixed(2)}% from peak (limit: ${cfg.maxDrawdownPercent}%)`
      this.triggerKillSwitch(reason)
      return { allowed: false, reason }
    }

    return { allowed: true }
  }

  // ── Kill switch management ────────────────────────────────

  triggerKillSwitch(reason: string): void {
    this.killSwitch = {
      triggered: true,
      reason,
      triggeredAt: Date.now(),
    }
  }

  resetKillSwitch(): void {
    this.killSwitch = { triggered: false }
  }

  getKillSwitchStatus(): KillSwitchStatus {
    return { ...this.killSwitch }
  }

  // ── P&L tracking ──────────────────────────────────────────

  recordTrade(pnl: number, currentEquity: number): void {
    this.pnlTracker.recordTrade(pnl, currentEquity)
  }

  updateEquity(currentEquity: number): void {
    this.pnlTracker.updateEquity(currentEquity)
  }

  getDailyPnLPercent(currentEquity: number): number {
    return this.pnlTracker.getDailyPnLPercent(currentEquity)
  }

  getDrawdownPercent(currentEquity: number): number {
    return this.pnlTracker.getDrawdownPercent(currentEquity)
  }

  getDailyPnLEntries(): DailyPnLEntry[] {
    return this.pnlTracker.getEntries()
  }

  // ── Config management ─────────────────────────────────────

  getConfig(): RiskConfig {
    return { ...this.config }
  }

  updateConfig(config: Partial<RiskConfig>): void {
    this.config = { ...this.config, ...config }
  }
}
