export {
  ALL_TABLES, CREATE_INDEXES, SEED_SETTINGS,
  CREATE_MAINTENANCE_SCHEDULES, CREATE_SCHEDULE_INDEXES,
  CREATE_TRIPS, CREATE_TRIP_INDEXES,
  CREATE_INSURANCE_POLICIES, CREATE_INSURANCE_DOCUMENTS, CREATE_INSURANCE_INDEXES,
  CREATE_REGISTRATIONS, CREATE_REGISTRATION_DOCUMENTS, CREATE_REGISTRATION_INDEXES,
  CREATE_GPS_TRIPS, CREATE_GPS_TRIP_INDEXES,
  CREATE_TIRE_SETS, CREATE_TIRE_MEASUREMENTS, CREATE_TIRE_ROTATIONS, CREATE_TIRE_INDEXES,
  CREATE_PARKING_LOCATIONS, CREATE_PARKING_INDEXES,
  CREATE_RECALLS, CREATE_RECALL_INDEXES,
  CREATE_DIAGNOSTIC_SNAPSHOTS, CREATE_DIAGNOSTIC_CODES, CREATE_LIVE_DATA_LOGS, CREATE_DIAGNOSTIC_INDEXES,
} from './schema';
export {
  createVehicle,
  getVehicles,
  getVehicleById,
  updateVehicle,
  deleteVehicle,
  countVehicles,
  createMaintenance,
  getMaintenanceByVehicle,
  deleteMaintenance,
  createFuelLog,
  getFuelLogsByVehicle,
  deleteFuelLog,
  getSetting,
  setSetting,
  createSchedule,
  getSchedulesByVehicle,
  getActiveSchedules,
  getScheduleById,
  updateSchedule,
  deactivateSchedule,
  deleteSchedule,
  autoLinkMaintenanceToSchedule,
} from './crud';
export {
  createTrip,
  getTripsByVehicle,
  getTripsByPurpose,
  deleteTrip,
} from './trips';
export {
  createPolicy,
  getPoliciesByVehicle,
  getPolicyById,
  updatePolicy,
  deletePolicy,
  createInsuranceDocument,
  getDocumentsByPolicy,
  deleteInsuranceDocument,
} from './insurance';
export {
  createRegistration,
  getRegistrationByVehicle,
  getRegistrationById,
  updateRegistration,
  deleteRegistration,
  createRegDocument,
  getRegDocumentsByRegistration,
  deleteRegDocument,
} from './registrations';
export {
  createGpsTrip,
  getGpsTripsByVehicle,
  getGpsTripById,
  deleteGpsTrip,
} from './gps-trips';
export {
  createTireSet,
  getTireSetsByVehicle,
  getCurrentTireSet,
  updateTireSet,
  deleteTireSet,
  createMeasurement,
  getMeasurementsByTireSet,
  deleteMeasurement,
  createRotation,
  getRotationsByTireSet,
  deleteRotation,
} from './tires';
export {
  saveParking,
  getActiveParking,
  clearParking,
  getParkingHistory,
} from './parking';
export {
  createRecall,
  getRecallsByVehicle,
  getUnacknowledgedRecalls,
  acknowledgeRecall,
  deleteRecall,
  recallExists,
} from './recalls';
export {
  createSnapshot,
  getSnapshotsByVehicle,
  getSnapshotById,
  deleteSnapshot,
  createDiagnosticCode,
  getCodesBySnapshot,
  createLiveDataLog,
  getRecentLiveData,
  clearLiveDataLogs,
} from './diagnostics';
