import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import type { DatabaseAdapter } from '@mylife/db';
import { createModuleTestDatabase } from '@mylife/db';
import { MEDS_MODULE } from '../definition';
import { createMedicationExtended } from '../medication';
import { logDose } from '../reminders/scheduler';
import { createMoodEntry } from '../mood/check-in';
import { addActivity } from '../mood/activities';
import { logMeasurement } from '../measurements/crud';
import { generateDoctorReport, generateTherapyReport } from '../export';

describe('export reports', () => {
  let adapter: DatabaseAdapter;
  let closeDb: () => void;

  beforeEach(() => {
    const testDb = createModuleTestDatabase('meds', MEDS_MODULE.migrations!);
    adapter = testDb.adapter;
    closeDb = testDb.close;
  });

  afterEach(() => {
    closeDb();
  });

  describe('generateDoctorReport', () => {
    it('produces markdown with expected sections', () => {
      createMedicationExtended(adapter, 'm1', {
        name: 'Lisinopril',
        dosage: '10mg',
        frequency: 'daily',
      });

      logDose(adapter, 'dl1', {
        medicationId: 'm1',
        scheduledTime: '2026-01-15T08:00:00Z',
        status: 'taken',
      });

      logMeasurement(adapter, 'ms1', {
        type: 'blood_pressure',
        value: '120/80',
        unit: 'mmHg',
        measuredAt: '2026-01-15T09:00:00Z',
      });

      createMoodEntry(adapter, 'me1', {
        mood: 'content',
        energyLevel: 'low',
        pleasantness: 'pleasant',
        recordedAt: '2026-01-15T10:00:00Z',
      });

      const report = generateDoctorReport(adapter, '2026-01-01', '2026-01-31');

      // Check 7 expected sections
      expect(report).toContain('# Health Report');
      expect(report).toContain('## Medications');
      expect(report).toContain('Lisinopril');
      expect(report).toContain('## Adherence Summary');
      expect(report).toContain('## Health Measurements');
      expect(report).toContain('120/80');
      expect(report).toContain('## Mood Summary');
      expect(report).toContain('## Symptom Summary');
      expect(report).toContain('## Correlation Highlights');
      expect(report).toContain('Generated by MyMeds');
    });

    it('works with empty database (graceful empty state)', () => {
      const report = generateDoctorReport(adapter, '2026-01-01', '2026-01-31');

      expect(report).toContain('# Health Report');
      expect(report).toContain('No medications recorded');
      expect(report).toContain('No measurements recorded');
      expect(report).toContain('No mood entries recorded');
      expect(report).toContain('No symptoms logged');
      expect(report).toContain('Generated by MyMeds');
    });

    it('includes adherence percentage', () => {
      createMedicationExtended(adapter, 'm1', { name: 'Test' });

      logDose(adapter, 'dl1', {
        medicationId: 'm1',
        scheduledTime: '2026-01-15T08:00:00Z',
        status: 'taken',
      });
      logDose(adapter, 'dl2', {
        medicationId: 'm1',
        scheduledTime: '2026-01-16T08:00:00Z',
        status: 'skipped',
      });

      const report = generateDoctorReport(adapter, '2026-01-01', '2026-01-31');
      expect(report).toContain('50%');
      expect(report).toContain('1/2 doses taken');
    });

    it('includes symptom summary table', () => {
      // Seed a symptom and log it
      adapter.execute(
        `INSERT INTO md_symptoms (id, name, is_custom, created_at)
         VALUES (?, ?, 0, datetime('now'))`,
        ['s1', 'headache'],
      );
      adapter.execute(
        `INSERT INTO md_symptom_logs (id, symptom_id, severity, logged_at, created_at)
         VALUES (?, ?, 3, ?, ?)`,
        ['sl1', 's1', '2026-01-15T12:00:00Z', '2026-01-15T12:00:00Z'],
      );

      const report = generateDoctorReport(adapter, '2026-01-01', '2026-01-31');
      expect(report).toContain('headache');
      expect(report).toContain('| Symptom | Occurrences |');
    });
  });

  describe('generateTherapyReport', () => {
    it('produces markdown with additional mood detail', () => {
      createMedicationExtended(adapter, 'm1', { name: 'Lexapro', dosage: '10mg' });

      createMoodEntry(adapter, 'me1', {
        mood: 'content',
        energyLevel: 'low',
        pleasantness: 'pleasant',
        intensity: 4,
        notes: 'Feeling better today',
        recordedAt: '2026-01-15T10:00:00Z',
      });

      addActivity(adapter, 'a1', 'me1', 'meditation');

      const report = generateTherapyReport(adapter, '2026-01-01', '2026-01-31');

      // Should contain doctor report sections plus detailed mood log
      expect(report).toContain('# Health Report');
      expect(report).toContain('## Detailed Mood Log');
      expect(report).toContain('**content**');
      expect(report).toContain('Intensity: 4/5');
      expect(report).toContain('Feeling better today');
      expect(report).toContain('meditation');
      expect(report).toContain('Generated by MyMeds');
    });

    it('works with empty database (graceful empty state)', () => {
      const report = generateTherapyReport(adapter, '2026-01-01', '2026-01-31');

      expect(report).toContain('# Health Report');
      expect(report).toContain('## Detailed Mood Log');
      expect(report).toContain('No mood entries in this period');
      expect(report).toContain('Generated by MyMeds');
    });
  });
});
