import { chromium } from '@playwright/test';
const origin = process.argv[2];
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('console', (m) => console.log('[console]', m.type(), m.text().slice(0, 300)));
page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 300)));
await page.goto(origin);
await page.waitForTimeout(6000);
console.log('[body]', (await page.locator('body').innerText()).slice(0, 200));
await browser.close();
