import type { ModuleDefinition, Migration } from '@mylife/module-registry';
import { nutritionCrossModule } from './cross-module';
import { ALL_TABLES, CREATE_INDEXES, SEED_SETTINGS } from './db/schema';
import { NUTRITION_MIGRATION_V2, NUTRITION_MIGRATION_V3, NUTRITION_MIGRATION_V4, NUTRITION_MIGRATION_V5, NUTRITION_MIGRATION_V6, NUTRITION_MIGRATION_V7, NUTRITION_MIGRATION_V8 } from './db/migrations';

const NUTRITION_MIGRATION_V1: Migration = {
  version: 1,
  description: 'Initial nutrition schema -- foods, nutrients, food log, goals, settings, barcode cache + FTS + indexes + seeds',
  up: [
    ...ALL_TABLES,
    ...CREATE_INDEXES,
    ...SEED_SETTINGS,
  ],
  down: [
    'DROP TABLE IF EXISTS nu_foods_fts',
    'DROP TABLE IF EXISTS nu_barcode_cache',
    'DROP TABLE IF EXISTS nu_food_log_items',
    'DROP TABLE IF EXISTS nu_food_log',
    'DROP TABLE IF EXISTS nu_food_nutrients',
    'DROP TABLE IF EXISTS nu_daily_goals',
    'DROP TABLE IF EXISTS nu_nutrients',
    'DROP TABLE IF EXISTS nu_settings',
    'DROP TABLE IF EXISTS nu_foods',
  ],
};

export const NUTRITION_MODULE: ModuleDefinition = {
  id: 'nutrition',
  name: 'MyNutrition',
  tagline: 'Your food diary stays on your device. Your insights span your whole life.',
  icon: '\u{1F96C}',
  accentColor: '#F97316',
  tier: 'premium',
  storageType: 'sqlite',
  migrations: [NUTRITION_MIGRATION_V1, NUTRITION_MIGRATION_V2, NUTRITION_MIGRATION_V3, NUTRITION_MIGRATION_V4, NUTRITION_MIGRATION_V5, NUTRITION_MIGRATION_V6, NUTRITION_MIGRATION_V7, NUTRITION_MIGRATION_V8],
  schemaVersion: 8,
  tablePrefix: 'nu_',
  crossModule: nutritionCrossModule,
  navigation: {
    tabs: [
      { key: 'home', label: 'Home', icon: 'home' },
      { key: 'diary', label: 'Diary', icon: 'book-open' },
      { key: 'search', label: 'Search', icon: 'search' },
      { key: 'trends', label: 'Trends', icon: 'trending-up' },
      { key: 'community', label: 'Community', icon: 'users' },
      { key: 'settings', label: 'Settings', icon: 'settings' },
    ],
    screens: [
      { name: 'dashboard', title: 'Dashboard' },
      { name: 'food-detail', title: 'Food Details' },
      { name: 'add-food', title: 'Add Food' },
      { name: 'scan', title: 'Scan Barcode' },
      { name: 'photo', title: 'Photo Log' },
      { name: 'meal-edit', title: 'Edit Meal' },
      { name: 'water', title: 'Water Tracking' },
      { name: 'energy-balance', title: 'Energy Balance' },
      { name: 'sync-settings', title: 'Sync Settings' },
      { name: 'diary-notes', title: 'Daily Notes' },
      { name: 'restaurants', title: 'Restaurants' },
      { name: 'restaurant-detail', title: 'Restaurant Menu' },
      { name: 'add-restaurant', title: 'Add Restaurant' },
      { name: 'community-profile', title: 'Community Profile' },
      { name: 'community-challenge', title: 'Challenge Detail' },
      { name: 'community-feed', title: 'Activity Feed' },
      { name: 'insights', title: 'Nutrition Insights' },
    ],
  },
  requiresAuth: false,
  requiresNetwork: false,
  version: '0.3.0',
  syncPolicy: {
    defaultScope: 'personal_replica',
    shareable: false,
    isSensitive: true,
    entityRules: [
      { tableName: 'food_log', defaultScope: 'personal_replica', conflictStrategy: 'manual_review', requiresManualResolver: true, resolverComponent: 'NutritionMealConflictResolver' },
      { tableName: 'food_log_items', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'foods', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'nutrients', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'food_nutrients', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'daily_goals', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'water_log', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'energy_log', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'daily_notes', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'restaurants', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'menu_items', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'photo_log', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'favorites', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'meal_templates', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'meal_template_items', defaultScope: 'personal_replica', conflictStrategy: 'lww' },
      { tableName: 'barcode_cache', defaultScope: 'device_local', conflictStrategy: 'lww' },
      { tableName: 'settings', defaultScope: 'device_local', conflictStrategy: 'lww' },
    ],
  },
};
